### ISSUE TITLE
[log][v2] When refreshing the page, the browser console will not be detach from the log stream

### ISSUE THREAD

**Issue by A-kirami** [tauri-apps/plugins-workspace#1000]
As the number of page refreshes increases, the number of logs in the browser console also increases accordingly. Each time a log is called, multiple logs will be printed to the browser console.

```js
import { attachConsole, info } from '@tauri-apps/plugin-log'

(async () => {
  await attachConsole();
  info('App is ready')
})();
```

![image](https://github.com/tauri-apps/plugins-workspace/assets/66513481/9287a3d3-9c9d-46f7-ace1-74d44765128d)

**Comment by kamiya4047** [comment]
The `attachConsole()` returns a Promise that resolves to an unlisten function.
You will need to call it to unattach the console.

```js
const unattachConsole = attachConsole();

// some code

unattachConsole.then(f => f());
```

**Comment by A-kirami** [comment]
> The `attachConsole()` returns a Promise that resolves to an unlisten function. You will need to call it to unattach the console.
> 
> ```js
> const unattachConsole = attachConsole();
> 
> // some code
> 
> unattachConsole.then(f => f());
> ```

I understand this, but it will automatically detach after refreshing the page in v1, and I think v1 is a normal behavior.

**Comment by FabianLars** [comment]
Hmm, i assume this is fixed by https://github.com/tauri-apps/tauri/pull/8930 so we just have to update tauri to beta.8 in this repo

**Comment by martpie** [comment]
I can confirm it was fixed in the latest version of Tauri. It is VERY useful, and not only for `attachConsole`, but any even listener where you get the cleanup function asynchronously: they are a pain to call in React as `useEffect` are not meant to be async.

Thank you!
