### ISSUE TITLE
Shell open can't open file if the file is being used by a program on Windows

### ISSUE THREAD

**Issue by Legend-Master** [tauri-apps/plugins-workspace#1003]
`open` from shell plugin can't open file if the file is being used by a program on Windows, for example, the log file from the log plugin

We're currently using [open](https://github.com/Byron/open-rs) to handle open files in shell plugin, and this is a bug in that crate

> https://github.com/tauri-apps/plugins-workspace/blob/9d4b25cf85fbf38f2506f5a5bcd79465d61bab54/plugins/shell/src/scope.rs#L211

I have discussed with the author of open on https://github.com/Byron/open-rs/issues/90 and we both think maybe it's better to use [opener](https://github.com/Seeker14491/opener) (this crate is used by rustup by the way) for this case

But this crate doesn't support open with specific program, so maybe if we still want to support that, we can use opener for handling default open, and open for open with specific program

Another added benefit is that we can add reveal from opener, as it's a highly requested feature https://github.com/tauri-apps/plugins-workspace/issues/999

> Opens the default file explorer and reveals a file or folder in its containing folder.

**Comment by amrbashir** [comment]
I kind of disagree with the author that `ShellExecuteW` shouldn't be used in `open-rs` since they have a `with_detached` method and `ShellExecuteW` would be perfect for that usecase. 

Anyways, I don't want to switch to `opener` as it is currently using (sorta?) unmaintained crates `winapi` and `dbus` and our use-case is simple.

I think I will switch our windows implementation to use `ShellExecuteW` and keep using `open-rs` on other platforms.

Also #999 is currently being worked on in https://github.com/tauri-apps/plugins-workspace/tree/feat/shell-show-item-in-dir

**Comment by Byron** [comment]
Would you be willing to contribute the `ShellExecuteW` version to `open` if you think it can fit?

Your usecase would be reason enough to even consider some standalone-windows-only-special-case that can be used for exactly these occasions. Making `open` able to actually open things is important to me, and supporting `tauri` in any way even more so.

**Comment by amrbashir** [comment]
Thank you for considering, I personally would like to keep using `open` as it has minimal dependencies and have been covering our simple use-case for so long.

> Would you be willing to contribute the `ShellExecuteW` version to `open` if you think it can fit?

yes, I can open a PR sometime later

**Comment by Legend-Master** [comment]
> Anyways, I don't want to switch to opener as it is currently using (sorta?) unmaintained crates winapi and dbus and our use-case is simple.

There's a hanging PR on switching to windows crate https://github.com/Seeker14491/opener/pull/28

Anyway, if we can support this in open, that'll be great as open has way fewer dependencies

> Also https://github.com/tauri-apps/plugins-workspace/issues/999 is currently being worked on in https://github.com/tauri-apps/plugins-workspace/tree/feat/shell-show-item-in-dir

It's great to see it being worked on!
