### ISSUE TITLE
[shell][v2] The program fails to start after adding the scope configuration for the shell plugin.

### ISSUE THREAD

**Issue by myWsq** [tauri-apps/plugins-workspace#1009]
tauri.config.json
```json
{
  "plugins": {
    "shell": {
      "open": true,
      "scope": [
        {
          "name": "bin/meilisearch",
          "sidecar": true
        }
      ]
    }
  }
}
```

Error message:

```
thread 'main' panicked at src/main.rs:27:10:
error while running tauri application: PluginInitialization("shell", "unknown field `scope`, expected `open`")
```

Plugin version

```yaml
name = "tauri-plugin-shell"
version = "2.0.0-beta.1"
```

**Comment by FabianLars** [comment]
In beta scopes are now part of the new access control list: https://beta.tauri.app/references/v2/acl/#scopes - here's an example for shell in particular: https://github.com/tauri-apps/plugins-workspace/blob/53c0e898608b2fe96d20e417905674ca41d8a089/examples/api/src-tauri/capabilities/base.json#L33-L42

Please bear with us while we're working on the docs for v2 :)
