### ISSUE TITLE
[updater] install mode is not passive by default if windows field is not declared

### ISSUE THREAD

**Issue by Legend-Master** [tauri-apps/plugins-workspace#1015]
`Config::windows` is default to `None` instead of `Some(WindowsConfig::default())`

https://github.com/tauri-apps/plugins-workspace/blob/99bea2559c2c0648c2519c50a18cd124dacef57b/plugins/updater/src/config.rs#L84

https://github.com/tauri-apps/plugins-workspace/blob/99bea2559c2c0648c2519c50a18cd124dacef57b/plugins/updater/src/updater.rs#L557-L574

**Comment by Legend-Master** [comment]
Also, I'm not sure why `installerArgs` / `installer-args` / `installer_args` doesn't work in `tauri.conf.json`

> Error failed to build bundler settings: unknown field `installerArgs`, expected `install-mode` or `installMode`

**Comment by FabianLars** [comment]
> Also, I'm not sure why installerArgs / installer-args / installer_args doesn't work in tauri.conf.json

Did you add this to the plugins section or the bundle config? The latter only has the installMode and is meant for the first installation.

That's the only thing i can see that'd cause this.

**Comment by Legend-Master** [comment]
I did something like this, is this correct?

```json
{
    "plugins": {
        "updater": {
            "windows": {
                "installMode": "passive",
                "installerArgs": ["/NS"]
            }
        }
    }
}
```

**Comment by FabianLars** [comment]
yeah, that should be correct
