### ISSUE TITLE
[http] In the source code JavaScript, fetch and use the new Request object to invoke to Rust. Array. from (req. headers. entries) will always be an empty array, right

### ISSUE THREAD

**Issue by lingoh** [tauri-apps/plugins-workspace#1026]
async function fetch(input, init) {
    const maxRedirections = init?.maxRedirections;
    const connectTimeout = init?.maxRedirections;
    const proxy = init?.proxy;
    // Remove these fields before creating the request
    if (init) {
        delete init.maxRedirections;
        delete init.connectTimeout;
        delete init.proxy;
    }
    const req = new Request(input, init);
    const buffer = await req.arrayBuffer();
    const reqData = buffer.byteLength ? Array.from(new Uint8Array(buffer)) : null;
    const rid = await invoke("plugin:http|fetch", {
        clientConfig: {
            method: req.method,
            url: req.url,
            headers: Array.from(req.headers.entries()),
            data: reqData,
            maxRedirections,
            connectTimeout,
            proxy,
        },
    });
....

Invoke can only pass strings, right?

**Comment by amrbashir** [comment]
I believe you maybe experiencing a similar issue to https://github.com/tauri-apps/plugins-workspace/issues/966 which was fixed in #983 and will be released soon.
