### ISSUE TITLE
[log] Does tauri-plugin-log support writing to multiple files?

### ISSUE THREAD

**Issue by ulizkoigor** [tauri-apps/plugins-workspace#1032]
### Describe the bug

Hello! Please tell me, can tauri-plugin-log write the trace level to one file, the debug level to the second file, and the error level to the third file? How do I set it up? Thanks

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 122.0.2365.66
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.75.0 (82e1608df 2023-12-21)
    ✔ cargo: 1.75.0 (1d8b05cdd 2023-11-20)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.11.0
    - pnpm: 8.15.1
    - npm: 9.8.1

[-] Packages
    - tauri [RUST]: 1.5.4
    - tauri-build [RUST]: 1.5.1
    - wry [RUST]: 0.24.7
    - tao [RUST]: 0.16.7
    - @tauri-apps/api [NPM]: 1.5.3
    - @tauri-apps/cli [NPM]: 1.5.9 (outdated, latest: 1.5.10)

[-] App
    - build-type: build
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
```

**Comment by FabianLars** [comment]
Soooo, this is currently not supported and i'm not sure if it makes sense to have an option _specifically_ for this. Maybe it makes more sense to expose a setter for the [dispatch](https://docs.rs/fern/latest/fern/struct.Dispatch.html) being used by the plugin but that will overwrite all the other Builder methods 🤔 
Or maybe better a `LogTarget::Dispatch` that basically calls the plugin's main Dispatch [`chain()`](https://docs.rs/fern/latest/fern/struct.Dispatch.html#method.chain) method

**Comment by Legend-Master** [comment]
I think this is currently doable already

```rust
tauri_plugin_log::Builder::new()
    .clear_targets()
    .targets([
        Target::new(TargetKind::LogDir {
            file_name: Some("info".into()),
        })
        .filter(|metadata| metadata.level() == Level::Info),
        Target::new(TargetKind::LogDir {
            file_name: Some("debug".into()),
        })
        .filter(|metadata| metadata.level() == Level::Debug),
    ])
    .build()
```

**Comment by FabianLars** [comment]
How about we ignore that i forgot how arrays work? 😂
