### ISSUE TITLE
[http]error while running tauri application: PluginInitialization("http", "invalid type: map, expected unit")

### ISSUE THREAD

**Issue by lingoh** [tauri-apps/plugins-workspace#1055]
error while running tauri application: PluginInitialization("http", "invalid type: map, expected unit")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

The latest version of HTTP has the following startup error configuration for tauri.conf.json
{
  "plugins": {
    "http": {
      "scope": ["https://api.github.com/repos/tauri-apps/*"]
    }
  }
}

**Comment by FabianLars** [comment]
https://github.com/tauri-apps/plugins-workspace/issues/1009#issuecomment-1974753387

**Comment by lingoh** [comment]
"src-tauri/capabilities/base.json
{
  "permissions": [
    {
      "identifier": "http:default",
      "allow": [{ "url": "https://*.tauri.app" }],
      "deny": [{ "url": "https://private.tauri.app" }]
    }
  ]
}

error: failed to run custom build command for ` (/src-tauri)`

Caused by:
  process didn't exit successfully: `/src-tauri/target/debug/build/tapp-4e257a465ff45908/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=TAURI_CONFIG
  cargo:rerun-if-changed=tauri.conf.json
  cargo:rustc-cfg=desktop
  cargo:rustc-env=TAURI_ANDROID_PACKAGE_PREFIX=com_tapp
  cargo:rustc-cfg=dev
  cargo:rerun-if-changed=permissions
  cargo:PERMISSION_FILES_PATH=/src-tauri/target/debug/build/tiktok-6ab4fb0f0d71786c/out/app-manifest/__app__-permission-files
  cargo:rerun-if-changed=capabilities
  failed to parse JSON: data did not match any variant of untagged enum CapabilityFile: data did not match any variant of untagged enum CapabilityFile
