### ISSUE TITLE
[http] Cookies cannot be passed to the server in custom requests

### ISSUE THREAD

**Issue by lingoh** [tauri-apps/plugins-workspace#1057]
It should be that the cookie was lost after being passed from the fetch to the trust end, and cannot be passed to the remote server
in tauri-plugin-http = "2.0.0-beta.2"

the custom header was only responsible for transmitting to Rust, and Rust, as a true request, was not responsible for transmitting it as is, resulting in the server not receiving it at all

**Comment by amrbashir** [comment]
could you provide an example to test this?

also try enabling the `cookies` feature in Cargo.toml

```toml
tauri-plugin-http = { version = "2.0.0-beta", features = ["cookies"] } 
```

**Comment by skyf0l** [comment]
I'd like reqwest on the rust side to be an extension of javascript fetch: with cookies set and when I make a request to "/something" the host is that of the current page ( like fetch in fact).
