### ISSUE TITLE
[http][v2] acl regression for url containing params

### ISSUE THREAD

**Issue by vangork** [tauri-apps/plugins-workspace#1061]
For url with params like: `https//www.domain.com/page?key1=value1&key2=value2`, even the acl has been set to allow all:
```
{
  "identifier": "http:default",
  "allow": [
    {"url": "https://*"}
  ]
}
```
It won't be allowed with error of `url not allowed on the configured scope`. It only affects the latest version of [http v2.0.0-beta.2](https://github.com/tauri-apps/plugins-workspace/releases/tag/http-v2.0.0-beta.2). Earlier version doesn't have this issue.

**Comment by FabianLars** [comment]
thanks for the report, i assume this will be fixed by https://github.com/tauri-apps/plugins-workspace/pull/1059

**Comment by vangork** [comment]
Resolved.
