### ISSUE TITLE
[single-instance] Can not find function `init` while using Android

### ISSUE THREAD

**Issue by naman-crabnebula** [tauri-apps/plugins-workspace#1074]
So, I was making a demo android application, and tried various plugins with it.

While using Tauri Plugin Single Instance, building ( using `cargo tauri android dev` )  for Android target failed, and the error is

```shell
error[E0425]: cannot find function `init` in crate `tauri_plugin_single_instance`
  --> src/lib.rs:10:47
   |
10 |         .plugin(tauri_plugin_single_instance::init())
   |                                               ^^^^ not found in `tauri_plugin_single_instance`
   |
help: consider importing one of these items
   |
2  + use tauri_plugin_notification::init;
   |
2  + use tauri_plugin_shell::init;
   |
help: if you import `init`, refer to it directly
   |
10 -         .plugin(tauri_plugin_single_instance::init())
10 +         .plugin(init())
   |
```

## Reproduction

1. Create a Tauri app with mobile support
2. Add Single Instance Plugin with `cargo tauri add single-instance` , manual adding fails as well
3. Run `cargo tauri android dev` 

However, `cargo tauri dev` runs fine on same app. ( But it opens Desktop application ofc )

**Comment by amrbashir** [comment]
this is because it doesn't support mobile targets, we could add an empty plugin implementation on mobile but I don't really like the idea of creating an empty plugin, instead users should cfg this plugin on mobile.
