### ISSUE TITLE
[sql] Question Am I using it correctly?

### ISSUE THREAD

**Issue by carloscv97** [tauri-apps/plugins-workspace#1076]
I just follow the steps of the readme to incluide SQL plugin to my project, but when I try to connect calling Database.load() throw the next message

![image](https://github.com/tauri-apps/plugins-workspace/assets/59967161/1071abc0-a44e-4c99-a3f7-d67b3339b9e4)

Here is how calling the method, is there something wrong?  

![image](https://github.com/tauri-apps/plugins-workspace/assets/59967161/d149865f-0121-43f7-a3bc-8c24bd4c3aa4)

**Comment by FabianLars** [comment]
The readme's weren't updated for the new permission system introduced in v2 beta yet. https://beta.tauri.app/references/v2/acl/ -> Your project should already have such a capibility file so just add "sql:allow-load" or "sql:default" to the permissions array.
