### ISSUE TITLE
[updater] Move updater out of zip

### ISSUE THREAD

**Issue by Legend-Master** [tauri-apps/plugins-workspace#1083]
Updaters/installers are already compressed files, there's no reason to place them in a zip file

Even if the user choose no compress on the installer, web servers (update servers) are generally able to send compressed stream anyway

Having to use zip makes it an extra step on the bundler and updater, and this makes the process slower and binary size bigger #1085

This will be a pretty big breaking change though (can be somewhat mitigated by introducing a new field in the update manifest to point to the plain installer)

**Comment by amrbashir** [comment]
related: https://github.com/tauri-apps/tauri/issues/5760

**Comment by amrbashir** [comment]
I agree we should remove the zip for Linux and Windows (it still required for macOS though), this however will require changes in the bundler and would require a few changes to the updater response JSON, probably will need adding a specific field to tell the updater that the updater package is an msi or nsis

**Comment by amrbashir** [comment]
for example:

```json
{
  "windows-x86_64": {
    "signature": "Content of app-setup.exe.sig or app.msi.sig, depending on the chosen format",
    "url": "https://github.com/username/reponame/releases/download/v1.0.0/app-x64-setup.nsis.zip",
    "format": "nsis or wix depending on the chosen format"
  }
}
```

**Comment by Legend-Master** [comment]
Do we want this change to be backward compatible?

If so we probably need to add a new field like this, and still emit a .zip file

```json
{
  "windows-x86_64": {
    "signature": "signature of .zip",
    "url": "app-x64-setup.nsis.zip",
    "signature-non-zip": "signature of app-x64-setup.exe",
    "url-non-zip": "app-x64-setup.exe"
  }
}
```

**Comment by amrbashir** [comment]
I think it should be fine to break it now than later
