### ISSUE TITLE
[bug][autostart] LaunchAgent Autostart launcher does not work on macOS

### ISSUE THREAD

**Issue by venkr** [tauri-apps/plugins-workspace#1115]
The `LaunchAgent` macOS autostart launcher does not work. I've looked at LaunchAgent plists created by other non-Tauri apps that successfully autostart, and it looks like they all create a Plist item of the form:

```
  <key>ProgramArguments</key>
  <array>
      <string>/Applications/APP.app/Contents/MacOS/APP</string>
  </array>
``` 

Whereas, tauri-plugin-autostart creates a Plist item of the form:
```
  <key>ProgramArguments</key>
  <array>
      <string>/Applications/APP.app
  </array>
``` 
which does not work. 

I've tested manually modifying the plist to add back the `Contents/macOS/APP` bit, and it works perfectly. 

This looks like this is likely caused by PR #125 - which caused this diff, likely to make `autostart` work correctly for the `AppleScript` path.

However, we don't really want to use the `AppleScript` path for the app we're working on as it shows a scary-looking message to users on first boot. 

Ideally, this would correctly:
- a) use the `APP.app` path for `AppleScript`
- b) use the `APP.app/Contents/macOS/APP` path for `LaunchAgent`

**Comment by FabianLars** [comment]
Are you using v1 or v2? For v1 this was fixed [here](https://github.com/tauri-apps/plugins-workspace/pull/841) if i understand correctly but i think i didn't merge v1 into v2 yet.

**Comment by venkr** [comment]
> Are you using v1 or v2? For v1 this was fixed [here](https://github.com/tauri-apps/plugins-workspace/pull/841) if i understand correctly but i think i didn't merge v1 into v2 yet.

I'm using v2 - that probably explains it.

**Comment by venkr** [comment]
I'm using a fork for now to unblock myself, and I put up a PR in case you're not planning to do another v1 -> v2 merge.

**Comment by FabianLars** [comment]
another merge is planned but idk when i can get to it so let's merge this for a quick fix, thank you!
