### ISSUE TITLE
Multiple crates missing `repository` field

### ISSUE THREAD

**Issue by paolobarbolini** [tauri-apps/plugins-workspace#1135]
Hi! As part of our efforts to verify that crates.io releases are reproducible [^1], we have discovered that one or more crates hosted in this repo are missing the `repository` field [^2] in `Cargo.toml`.

The `repository` field helps users and automated tools find the link to the git repository hosting the source code. While not required by crates.io, we believe it should always be set.

We suggest that the `repository` field be configured for **every crate** published to crates.io. Thank you very much.

[^1]: https://github.com/M4SS-Code/cargo-goggles/issues/11
[^2]: https://doc.rust-lang.org/cargo/reference/manifest.html#the-repository-field

**Comment by FabianLars** [comment]
Thanks for suggestion. We added the field in #1143 but won't cut a new release just for this change so it may take a few days to show up :)

Edit: I'll also add the field to the few crates that are published from the v1 branch later.
