### ISSUE TITLE
Permissions issue

### ISSUE THREAD

**Issue by Alchemy5** [tauri-apps/plugins-workspace#1149]
Hi,
What might be causing this traceback when using the exists binding with tauri?
<img width="946" alt="image" src="https://github.com/tauri-apps/plugins-workspace/assets/104028972/d0ac9c5e-0af5-42d9-b1a0-7e956b2bccb8">

**Comment by amrbashir** [comment]
looks like you have an invalid permission in your capability file, change `fs.exists` to `fs:allow-exists`
