### ISSUE TITLE
[dialog] Mobile selection of folders or files

### ISSUE THREAD

**Issue by handexing** [tauri-apps/plugins-workspace#1163]
Hi, when will mobile selection of folders or files be supported? Or what other solutions can be implemented. Thank you for providing some ideas

error：
<img width="433" alt="image" src="https://github.com/tauri-apps/plugins-workspace/assets/6150712/d7b32eb9-dad4-4036-9bcf-f70efe2d1616">
<img width="420" alt="image" src="https://github.com/tauri-apps/plugins-workspace/assets/6150712/e59c115a-d523-4c03-b958-45cde5524408">

I want to implement an import and export function
<img width="572" alt="image" src="https://github.com/tauri-apps/plugins-workspace/assets/6150712/2c18f6dc-a9cd-4e70-a83e-839beff1265e">

**Comment by bpevs** [comment]
I believe this is related to current work:
https://github.com/tauri-apps/tauri/pull/9311
https://github.com/tauri-apps/plugins-workspace/pull/1147

**Comment by FabianLars** [comment]
save_file should be supported now, pick_folder was tracked here already https://github.com/tauri-apps/plugins-workspace/issues/933
