### ISSUE TITLE
[http] Use browser cookies

### ISSUE THREAD

**Issue by skyf0l** [tauri-apps/plugins-workspace#1167]
I'd like `reqwest` on the rust side to be able to send a request to the server as the webview's browser: meaning automatically including the webview's cookies.

In addition, it would be interesting if, when a request is made to `/something`, the default domain was the one of the actual webpage (like the javascript fetch).

**Comment by amrbashir** [comment]
`reqwest` can have its own cookie store, you can enable its feature flag (I will open a PR to enable it by default)
```toml
tauri-plugin-http = { version = "2.0.0-beta", features = ["cookies"] } 
``` 

However we can't get the webview cookies and send them, so if you used the webview built-in fetch to set the cookie, you can't send it with the plugin fetch

> In addition, it would be interesting if, when a request is made to `/something`, the default domain was the one of the actual webpage (like the javascript fetch).

I will open a PR for that

**Comment by lingoh** [comment]
tauri-plugin-http-2.0.0-beta.7/src/commands.rs
if matches!(
                        name,
                        // forbidden headers per fetch spec https://fetch.spec.whatwg.org/#terminology-headers
                        header::ACCEPT_CHARSET
                            | header::ACCEPT_ENCODING
                            | header::ACCESS_CONTROL_REQUEST_HEADERS
                            | header::ACCESS_CONTROL_REQUEST_METHOD
                            | header::CONNECTION
                            | header::CONTENT_LENGTH
                            | header::DATE
                            | header::DNT
                            | header::EXPECT
                            | header::HOST
                            | header::ORIGIN
                            | header::REFERER
                            | header::TE
                            | header::TRAILER
                            | header::TRANSFER_ENCODING
                            | header::UPGRADE
                            | header::VIA
                    ) {
                        continue;
                    }
Why don't cookies allow customization?
