### ISSUE TITLE
Issue while implementing sql-plugin

### ISSUE THREAD

**Issue by Priefi-Solutions** [tauri-apps/plugins-workspace#1179]
Hey, im pretty new to tauri and rust. So please excuse any dumb question or false issue from me.

I tried to implement the sql-plugin in my new tauri project. I did as explained here: https://github.com/tauri-apps/tauri-plugin-sql

1. Pasted the code into cargo.toml
2. installed it via npm
3. activated the plugin in main.rs

I pretty much just copy/pasted the code from github. 

I just installed the plugin, havent used it in any js file or something.

But when i try to cargo run dev, i get the following error:

error[E0425]: cannot find function, tuple struct or tuple variant `Optional` in this scope
   --> /Users/[username]/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sqlx-sqlite-0.7.4/src/types/time.rs:311:13
    |
311 |             Optional(&Literal(b"Z")),
    |             ^^^^^^^^ not found in this scope
    |
help: consider importing one of these items
    |
192 +     use time::format_description::BorrowedFormatItem::Optional;
    |
192 +     use time::format_description::OwnedFormatItem::Optional;
    |

**Comment by FabianLars** [comment]
Please run `cargo update` in the src-tauri folder and try again.

**Comment by Priefi-Solutions** [comment]
Thanks! This was my mistake. 
Just curious, is this just some tauri or rust specific you have to know? Or was i blind while doing the step by step installation from github?

**Comment by FabianLars** [comment]
I honestly don't know, i don't think it's our fault, or something we can fix, other than mentioning `cargo update` in our install guide.
