### ISSUE TITLE
[clipboard manager] v2 tauri 2.0.0-beta.15 changed `into_img` method signature

### ISSUE THREAD

**Issue by washanhanzi** [tauri-apps/plugins-workspace#1194]
tauri `2.0.0-beta.15` changed `into_image` to accept `ResourceTable`, it breaks clipboard manager plugin here:

https://github.com/tauri-apps/plugins-workspace/blob/86723a5372af0f0bb4083ef1bf407b0199306728/plugins/clipboard-manager/src/desktop.rs#L42-L46

Maybe we can fix this by:

```
                    let resource_table = self.app.resources_table();
                    let image = image.into_img(&resource_table)?;
```

**Comment by FabianLars** [comment]
Will be fixed by https://github.com/tauri-apps/plugins-workspace/pull/1191, thanks for the report.
