### ISSUE TITLE
NFC plugin not working

### ISSUE THREAD

**Issue by parola05** [tauri-apps/plugins-workspace#1222]
I ran the NFC plugin as indicated in [link]( https://github.com/tauri-apps/plugins-workspace/tree/v2/plugins/nfc). However, the following error appears: **_"nfc.scan not allowed. Permissions associated with this command: nfc:allow-scan"_**. Should I proceed with any additional configuration? My **_lib.rs_** and my JavaScript file with the invocation of the NFC scan are as follows:

```rust
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_shell::init())
        .plugin(tauri_plugin_nfc::init())
        .invoke_handler(tauri::generate_handler![greet])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
```

```vue
<template>
  <div class="container my-3">
    <h1>Página Inicial</h1>
    <p>Valor NFC escaneado: {{ valorEscaneado }}</p>
    <button @click="iniciarLeitura">Iniciar Leitura NFC</button>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { scan } from "@tauri-apps/plugin-nfc";

const valorEscaneado = ref('');

const iniciarLeitura = async () => {
  try {
    const resultado = await scan({ type: "tag", keepSessionAlive: true });
  } catch (error) {
    console.error('Erro ao realizar a leitura NFC:', error);
  }
}
</script>
```

I registered the plugin _**tauri-plugin-nfc = "2.0.0-beta"**_ in Cargo.toml and no compilation errors occur. The only error that appears is when I click to start the scan.

**Comment by FabianLars** [comment]
we're still working on the docs but this is a "normal" error message with the new ACL/permissions. You should have a json file in src-tauri/capabilites/ folder. If you open that there should be a permissions array. Simply add `"nfc:allow-scan"` to that array and it should work.
