### ISSUE TITLE
[positioner] Tray position not set on Linux

### ISSUE THREAD

**Issue by davidchalifoux** [tauri-apps/plugins-workspace#1232]
I'm trying to use the system tray positions but am running into an error specifically on Linux. The error says `Tray position not set`, so is the tray position not available on Linux?

<img width="873" alt="Screenshot 2024-04-21 at 10 49 16 PM" src="https://github.com/tauri-apps/plugins-workspace/assets/3289533/57001ed5-834f-48d9-974c-89f2a2595fee">

I'm testing with Ubuntu 22.04.
Using `tauri-plugin-positioner` version 1.0.

You can see how I'm using it here: https://github.com/davidchalifoux/keylight-commander/blob/93e25da08044ea06189a72be2600a272028f8a4f/src-tauri/src/main.rs#L115

Any ideas?
Thanks

**Comment by FabianLars** [comment]
Correct, the tray apis don't work on Linux because we don't get any track click events due to limitations of libappindicator. As part of the docs rework we're doing rn we'll make sure to make this clear, thanks.
