### ISSUE TITLE
[sql] sqlite db file path?

### ISSUE THREAD

**Issue by echohsq** [tauri-apps/plugins-workspace#124]
I created the database file in the current directory(src-tauri/src/test.db), but it is not recognized, where should the path be by default in this method(Database.load('sqlite:test.db'))?
![image](https://user-images.githubusercontent.com/19308192/217163803-2987d035-de07-4dc6-9d23-2af4afb4913a.png)

**Comment by FabianLars** [comment]
the paths the plugins uses are relative to tauri's [`app_dir()`](https://docs.rs/tauri/latest/tauri/api/path/fn.app_dir.html) api (for example on windows `AppData/Roaming/bundle-id/<your path>`).

If you want to bundle a pre-built sql database you should look into tauri's resource feature <https://tauri.app/v1/guides/building/resources> (note that this doesn't change anything about the path resolution). Or look into "migrations" which seem to be the default solution if you want to pre-fill your database.
