### ISSUE TITLE
[v2 mobile]No command write found for plugin app.tauri.clipboard.ClipboardPlugin

### ISSUE THREAD

**Issue by thep0y** [tauri-apps/plugins-workspace#1240]
The `tauri-plugin-clipboard-manager` fails to operate within an Android emulator, presenting the error as described in the title, while functioning properly on Windows. I did not come across any specific instructions in the documentation regarding the use of the `clipboard` plugin on mobile devices, leading me to wonder if the `clipboard` plugin is unsupported on Android.

**Comment by FabianLars** [comment]
The writeText, readText, and clear apis should now be supported. Can you upgrade everything to latest and confirm?

The image and html apis are unsupported but should throw explicit "not supported" runtime errors. (this should have been the case when you reported the issue so maybe it was a de-sync between the rust and js packages)

**Comment by git-dazz** [comment]
same question


``` 
const { writeText, readText } = window?.__TAURI__?.clipboardManager;
readText().then(txt=>{
    greetMsgEl.textContent = txt;
}).catch(err=>{
    greetMsgEl.textContent = "error:"+ err.toString();
})
```

error:plugin clipboard-manager not found

**Comment by FabianLars** [comment]
> same question

Well, not really :P

This error _should_ mean that you didn't add or register the rust side of the plugin (the rust side of tauri plugins is always required, even if you just use the J's apis).

If this doesn't help, please share the output of the `tauri info` command.
