### ISSUE TITLE
[v2]clipboard-manager.write_text not allowed

### ISSUE THREAD

**Issue by Arc-zlz** [tauri-apps/plugins-workspace#1252]
![1714012789754](https://github.com/tauri-apps/plugins-workspace/assets/26889461/ee8418c1-64d7-478e-adac-a1081a8faa78)

![image](https://github.com/tauri-apps/plugins-workspace/assets/26889461/0086ae7a-6e61-4da7-a1d0-c38e5fa3dd1a)
![image](https://github.com/tauri-apps/plugins-workspace/assets/26889461/adf289f6-cb61-4ce0-96dd-82a5d639ecb5)

  - OS: Windows 10.0.22631 X64
    ✔ WebView2: 123.0.2420.97
    ✔ MSVC: 
        - Visual Studio Community 2022
    ✔ rustc: 1.75.0 (82e1608df 2023-12-21)
    ✔ cargo: 1.75.0 (1d8b05cdd 2023-11-20)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.19.0
    - pnpm: 8.14.1
    - yarn: 1.22.21
    - npm: 10.3.0

[-] Packages
    - tauri [RUST]: 2.0.0-beta.16
    - tauri-build [RUST]: 2.0.0-beta.13
    - wry [RUST]: 0.39.3
    - tao [RUST]: 0.27.1
    - @tauri-apps/api [NPM]: 2.0.0-beta.9
    - @tauri-apps/cli [NPM]: 2.0.0-beta.13

**Comment by loikki** [comment]
Hi @Arc-zlz what was your solution? I have exactly the same issue on android and I setup the permission correctly
