### ISSUE TITLE
An error while compilling

### ISSUE THREAD

**Issue by cnlancehu** [tauri-apps/plugins-workspace#1255]
![image](https://github.com/tauri-apps/plugins-workspace/assets/106385654/8746a444-1e0a-4b51-9355-58ddbc260301)

Here is the `Cargo.toml`
![image](https://github.com/tauri-apps/plugins-workspace/assets/106385654/618c9893-a89c-44c0-955e-1e239636e348)

It doesn't cause any major problem, but it's a bit annoying
could anyone fix it?
thanks a lot

**Comment by FabianLars** [comment]
run `cargo update`, i fixed that weeks ago :)

alternatively you can downgrade rust to 1.76, but of course that's not recommended.
