### ISSUE TITLE
[sql] - UUID unsuported type

### ISSUE THREAD

**Issue by KauanCurbani** [tauri-apps/plugins-workspace#1280]

**Comment by FabianLars** [comment]
https://github.com/tauri-apps/plugins-workspace/issues/1126

**Comment by KauanCurbani** [comment]
Can give me permission to add a pr?

**Comment by KauanCurbani** [comment]
I solved this

**Comment by FabianLars** [comment]
You can just fork this repository and open a PR from the fork, no need to have direct write access to our repo for that :)
