### ISSUE TITLE
[window state]Strange bug when using window state

### ISSUE THREAD

**Issue by Xiaobaishushu25** [tauri-apps/plugins-workspace#1284]
if just use dev or build ,it work normaly, but when change from build to dev(the meaning is to first run the packaged program, then close it and continue development in Rustover), window will not show(specifically, it will flash and then disappear),and i  read the `.window-state.json`, it content  has become:
```json
{
  "main": {
    "width": 1025.0,
    "height": 625.0,
    "x": -8,
    "y": -8,
    "prev_x": -32000,
    "prev_y": -32000,
    "maximized": true,
    "visible": false,
    "decorated": false,
    "fullscreen": false
  },
  "tool": {
    "width": 190.0,
    "height": 200.0,
    "x": 1645,
    "y": 174,
    "prev_x": 1645,
    "prev_y": 173,
    "maximized": false,
    "visible": false,
    "decorated": false,
    "fullscreen": false
  }
}
```
I manually changed prev_x and prev_y to 100, but it didn't work.

https://github.com/tauri-apps/plugins-workspace/assets/76581880/2ba3bab1-2f95-40b6-a803-5ccee903e6bc

this is my code:
```js
async function window_close(){
  // await WebviewWindow.getCurrent().hide()
  const ALL_WITHOUT_VISIBLE = StateFlags.ALL & ~StateFlags.VISIBLE;
  await saveWindowState(ALL_WITHOUT_VISIBLE);
  await invoke('exit_app', {})
  await WebviewWindow.getCurrent().close();
}
```
```rust
   tauri::Builder::default()
        .manage(state)
        .plugin(tauri_plugin_shell::init())
        .plugin(tauri_plugin_fs::init())
        .plugin(tauri_plugin_window_state::Builder::default().build())
        .setup(|app|{
            info!("{:?}",app.app_handle().path().app_config_dir().unwrap()); //"C:\\Users\\Xbss\\AppData\\Roaming\\com.xbss.trade-tip"
            let main_window = app.get_webview_window("main").unwrap();
            // main_window.as_ref().window().restore_state(StateFlags::all())
            let tool_window = app.get_webview_window("tool").unwrap();
            tokio::spawn(async move{
                let mut result = main_window.restore_state(StateFlags::all());
                info!("restore main window state result:{:?}",result);
                if result.is_err(){
                    error!("restore main window state error:{}",result.err().unwrap().to_string());
                };
                main_window.show().unwrap();
                 result = tool_window.restore_state(StateFlags::all());
                if result.is_err(){
                    error!("restore tool window state error:{}",result.err().unwrap().to_string());
                };
            });
            Ok(())
        })
```
the app stop in `let mut result = main_window.restore_state(StateFlags::all());`， but there is no error message or pain, it's just stuck here.
if i delete the `.window-state.json`, it will  work normaly.
this is my tauri info:
```
[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 124.0.2478.67
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.77.0 (aedd173a2 2024-03-17)
    ✔ cargo: 1.77.0 (3fe68eabf 2024-02-29)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.11.1
    - pnpm: 8.15.3
    - yarn: 1.22.19
    - npm: 10.2.4

[-] Packages
    - tauri [RUST]: 2.0.0-beta.17
    - tauri-build [RUST]: 2.0.0-beta.13
    - wry [RUST]: 0.39.3
    - tao [RUST]: 0.27.0
    - tauri-cli [RUST]: 2.0.0-beta.15
    - @tauri-apps/api [NPM]: 2.0.0-beta.7
    - @tauri-apps/cli [NPM]: 2.0.0-beta.12

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite

```

**Comment by FabianLars** [comment]
@amrbashir do you think this is related to https://github.com/tauri-apps/tauri/pull/9612 ?

**Comment by Xiaobaishushu25** [comment]
> @amrbashir do you think this is related to [tauri-apps/tauri#9612](https://github.com/tauri-apps/tauri/pull/9612) ?
sorry , i havc find the resaon, seems unrelated to dev and build, the code cause the problem:
```js
 const ALL_WITHOUT_VISIBLE = StateFlags.ALL & ~StateFlags.VISIBLE;
await saveWindowState(ALL_WITHOUT_VISIBLE);
```
(emm this code is gpt write..)
i chage it to：
```js
await saveWindowState(StateFlags.ALL);
```
the problem is never  again.
but i wonder why, there are no error prompts in the program, but there is an abnormal situation，I think if there are any errors, we should provide error messages instead of getting stuck here.

**Comment by Xiaobaishushu25** [comment]
> @amrbashir do you think this is related to [tauri-apps/tauri#9612](https://github.com/tauri-apps/tauri/pull/9612) ?

It seems that it has nothing to do with dev or build, because I deleted `.window-state.json` and it can run normally. When I opened it again, the same situation appeared, which is not stable. However, most of the time it occurs, and I don't know why. 
 the content of `.window-state.json` often is：
```
{
  "main": {
    "width": 1025.0,
    "height": 625.0,
    "x": -8,
    "y": -8,
    "prev_x": -32000,
    "prev_y": -32000,
    "maximized": true,
    "visible": true,
    "decorated": false,
    "fullscreen": false
  },
  "tool": {
    "width": 190.0,
    "height": 200.0,
    "x": 1299,
    "y": 353,
    "prev_x": 1298,
    "prev_y": 353,
    "maximized": false,
    "visible": false,
    "decorated": false,
    "fullscreen": false
  }
}
```
Just now, code stop also in `let mut result = main_window.restore_state(StateFlags::all());` ,but the window is show:
![image](https://github.com/tauri-apps/plugins-workspace/assets/76581880/ba233889-0c52-46e0-a832-41a3ea46efbd)
This is this time `.window-state.json`:
![image](https://github.com/tauri-apps/plugins-workspace/assets/76581880/789d39c4-bfcf-468f-acc3-24171f91be99)

**Comment by Xiaobaishushu25** [comment]
> @amrbashir do you think this is related to [tauri-apps/tauri#9612](https://github.com/tauri-apps/tauri/pull/9612) ?

oh, i have find the reason, because the plugin init code:
`.plugin(tauri_plugin_window_state::Builder::default().build())` ,it  automatically restored the window state(https://github.com/tauri-apps/plugins-workspace/blob/v2/plugins/window-state/src/lib.rs#L345)

I didn't read the document carefully(https://beta.tauri.app/features/window-state/), after `tauri_plugin_window_state::Builder::default().build()`, I attempted to manually restore the window state, which resulted in the above abnormal situation. However, I think the reason for the error should be given here. And improve the description of the document. By the way, there are errors in the document, the Permissions section:`"window-state:allow-restore-window-state"` should be `"window-state:allow-restore-state"`?

**Comment by amrbashir** [comment]
This sounds like a dead lock because the plugin is trying to restore the state while your code also tries to do the same and both are holding onto a mutex that is not dropped. You shouldn't restore yourself, and let the plugin do the initial restore.
