### ISSUE TITLE
[store][v2]Issues with using the Store plugin on the Android platform.

### ISSUE THREAD

**Issue by illuxiza** [tauri-apps/plugins-workspace#1289]
As shown in the screenshot, there is an issue with permissions when the page is first initialized, even though the permissions have been set. This issue only occurs on the Android platform, as there are no problems on desktop and iOS. Once the user successfully enters the page, the permission error no longer appears. However, it seems that the data is not actually being saved.

![WechatIMG1479](https://github.com/tauri-apps/plugins-workspace/assets/14817134/9552392d-cb1f-47a8-816f-7e3e7ed3cd5c)

**Comment by FabianLars** [comment]
Thanks for the report, this is an upstream issue tracked here: https://github.com/tauri-apps/tauri/issues/9502

**Comment by illuxiza** [comment]
@FabianLars  The plugin no longer throws errors on Android, but it still cannot save data.

**Comment by illuxiza** [comment]
It's my issue; on Android, I have to manually call save to actually save the data.

**Comment by codewithmanishkumar** [comment]
I am also facing the same issue, the 'load' store function does not work on Android but it works fine in macOS and iOS. @illuxiza can you share your implementation

**Comment by illuxiza** [comment]
> I am also facing the same issue, the 'load' store function does not work on Android but it works fine in macOS and iOS. @illuxiza can you share your implementation

I added the following code, and it runs normally.
`storeFile.save()`
