### ISSUE TITLE
[authenticator] auth.init() always gives error Unhandled Promise Rejection: TypeError: window.__TAURI_INVOKE_HANDLER__ is not a function

### ISSUE THREAD

**Issue by ihands** [tauri-apps/plugins-workspace#130]
We built the Tauri App using the tauri-plugin-authenticator plugin.

It looks like that the error occurred from the plugin as it gives an error when we call the init()

main.rs

```
fn main() {
    use tauri_plugin_authenticator::TauriAuthenticator;

    tauri::Builder::default()
    .plugin(TauriAuthenticator::default())
    ...
}
```

JS

```
import { Authenticator } from "tauri-plugin-authenticator-api";

const auth = new Authenticator();
auth.init(); // initialize usb
```

The error that shows in the console when we call auth.init()

Unhandled Promise Rejection: TypeError: window.__TAURI_INVOKE_HANDLER__ is not a function. (In 'window.__TAURI_INVOKE_HANDLER__(n)', 'window.__TAURI_INVOKE_HANDLER__' is undefined)

**Comment by FabianLars** [comment]
Sounds like you're using the `v0.1.0` git tag to install the package. Try using the dev branch instead (you can lock that to a specific commit if you'd like). The sql plugin has updated install instructions if you need guidance for that: https://github.com/tauri-apps/tauri-plugin-sql#rust
