### ISSUE TITLE
[feat] Improve windows NSIS updater

### ISSUE THREAD

**Issue by thewh1teagle** [tauri-apps/plugins-workspace#1301]
### Describe the problem

Currently, when updating a Tauri app with the Tauri updater on Windows using the NSIS package, it closes the app, opens a PowerShell terminal for a few seconds, then displays the NSIS installer progress. This process appears suspicious or strange to simple users.

### Describe the solution you'd like

Hide the powershell window and the nsis progress window with nicer user experience

### Alternatives considered

Maybe hide it completely until it finish everything?
The best scenario will be like in macOS. once the user chose to restart the app it immediately install the update in background and in 1-2 seconds open the app

### Additional context

Tauri v2

**Comment by amrbashir** [comment]
Cany you provide the updater version you're using and if possible a screenshot of that powershell window and when exactly does it show up?

**Comment by thewh1teagle** [comment]
I found that the powershell window doesn't apper in recent versions, so it seems like it fixed.

Can we hide this one too?
<video src="https://github.com/tauri-apps/plugins-workspace/assets/61390950/ad3b503c-59f0-4445-8240-87b3d2d0aa73">

**Comment by Legend-Master** [comment]
PowerShell window flashing should be fixed in #1054
