### ISSUE TITLE
[Updater][v2] - Show error on non-SSL updater endpoints

### ISSUE THREAD

**Issue by dan-myles** [tauri-apps/plugins-workspace#1308]
Currently, when serving a `latest.json` over an `https` endpoint, everything works as expected.

When moving to a self-hosted solution (ie. NOT github releases), the updater plugin will silently fail if the URI is not `https`.
Worst part is, Tauri will not show build errors, and will work in dev mode. However when using a built binary, it will silently fail.

**Comment by amrbashir** [comment]
It doesn't silently fail, the error should be there if you open the app from a terminal (unless you're on Windows). We still need to allow non-https protocol in development, otherwise it will be hard to use a localhost to serve your latest.json and updater files so instead I opened a PR to show a warning in development.

**Comment by dan-myles** [comment]
what i mean by silently fail is that tauri will succeed to build. this should be a build error.

and wow thanks for the prompt PR! ❤️

**Comment by amrbashir** [comment]
> what i mean by silently fail is that tauri will succeed to build. this should be a build error.

that' actually a good idea, I will open another PR for it.

**Comment by amrbashir** [comment]
Looks like it is not that easy to make it a build error from the plugin itself, so I guess we will just stick with this warning for now and if more users fall for this, we will make it build error on the CLI.

**Comment by dan-myles** [comment]
no worries, i think normally users will be using ssl for all production updater endpoints, so i don't think this will be too much of a problem, and this issue is open so if people want to find the info they can. thanks a lot!
