### ISSUE TITLE
[authenticator] error in the example 

### ISSUE THREAD

**Issue by conanchen** [tauri-apps/plugins-workspace#135]
1. run the example 
2. tauri-plugin-authenticator/examples/svelte-app on  dev [!] is 📦 v1.0.0 via  v16.4.1 took 3m23s
❯ yarn tauri dev
3. open http://localhost:5000
4. open chrome devtools: 
5. got the exception and the "register" button no effect:-
index.js:15 Uncaught (in promise) TypeError: Cannot read property 'notify' of undefined
    at index.js:15
    at new Promise (<anonymous>)
    at index.js:15
    at index.js:15
    at Object.next (index.js:15)
    at index.js:15
    at new Promise (<anonymous>)
    at index.js:15
    at e (index.js:15)
    at t.init (index.js:15)

**Comment by FabianLars** [comment]
Sound like you opened the localhost adress in your actual browser? Tauri's APIs only work in a tauri window, same is true for the example here.
Please re-open thise issue if you get the same error in a tauri app window.
