### ISSUE TITLE
tauri-plugin-shell: `.execute()` causes the page to freeze

### ISSUE THREAD

**Issue by 1zilc** [tauri-apps/plugins-workspace#1361]
# Describe:

It seems to be this submission https://github.com/tauri-apps/plugins-workspace/pull/1299 that is causing the page to stall, I used one of the simplest hello world prints, but I delayed it by 5 seconds, and during that 5 seconds the page freezes and cannot be manipulated

# Step:

- pnpm tauri dev
- click greet button

# Repo:

https://github.com/1zilc/tauri-plugin-shell-demo

# Screenshot:

https://github.com/tauri-apps/plugins-workspace/assets/44715458/dd76d24e-2d75-4253-88a0-c184689a5c58

# Version:

macOS 14.5
tauri 2.0-beta
tauri-plugin-shell v2

**Comment by amrbashir** [comment]
Thanks for the repro, it was a silly mistake, should be fixed by #1362
