### ISSUE TITLE
[problem] Websocket plugin

### ISSUE THREAD

**Issue by alicestoneprod** [tauri-apps/plugins-workspace#1366]
I cant understand, where i can check default port of websocket and why i got os error 10061:

VITE: 
import WebSocket from "tauri-plugin-websocket-api"
import s from "./ProgressBars.module.scss"

interface ProgressBarsI {}
export const ProgressBars: FC<ProgressBarsI> = ({}) => {
  const unlistenProgress = async () => await appWindow.listen("download_progress", ({ event, payload }) => console.log(payload))

  useEffect(() => {
    unlistenProgress()
    webSocket()
  }, [])

  const webSocket = async () => {
    const ws = await WebSocket.connect("ws://127.0.0.1:8080")
      .then((value) => {
        console.log(value)
        return value
      })
      .catch((e) => {
        console.log(e)
        return e
      })

    await ws.send("Hello World")

    await ws.disconnect()
  }
  
  Rust:
  
  async fn main() {
    tauri::Builder::default()
        .plugin(tauri_plugin_websocket::init())
        .invoke_handler(tauri::generate_handler![greet, play, get_settings, update_settings, update_all])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");    
}

**Comment by FabianLars** [comment]
> I cant understand, where i can check default port of websocket

I guess that depends on the server you're connecting to? Just to be clear, the websocket plugin is _not_ a server, but a client. Basically an alternative to the browser's WebSocket client when you're having cors issues.

**Comment by alicestoneprod** [comment]
> > I cant understand, where i can check default port of websocket
> 
> I guess that depends on the server you're connecting to? Just to be clear, the websocket plugin is _not_ a server, but a client. Basically an alternative to the browser's WebSocket client when you're having cors issues.

I am just trying to replace IPC, but i understood, that websocket is not good way for it. Maybe you know where i can see the best examples of IPC (especially from RUST to Vite (frontend))?

**Comment by alicestoneprod** [comment]
I should use this for solve my problem:
https://github.com/tauri-apps/plugins-workspace/tree/v2/plugins/websocket/examples/tauri-app
