### ISSUE TITLE
[bug] Shell plugin spawn behaves differently when the release build is open with different methods.

### ISSUE THREAD

**Issue by HuakunShen** [tauri-apps/plugins-workspace#1406]
I was running command like this

```ts
const command = Command.create("ffprobe", [
    "-v",
    "quiet",
    "-print_format",
    "json",
    "-show_format",
    "-show_streams",
    videoPath,
  ]);
```

It worked fine in debug mode, but stopped working when the app is bundled and installed.

<img width="608" alt="image" src="https://github.com/tauri-apps/plugins-workspace/assets/33727687/57e6253b-3f08-4f76-ab4b-8b23daedd824">

After enable devtools in release mode, I see error: `No such file or directory`.

Then I found that the shell command doesn't work if I open the app the usual way (i.e. double click the `.app`).
But if I open the app with `open` command (open `/Applications/myApp.app`), everything works fine. The `No such file or directory` is gone.

What's the difference between the two methods?

I am using "@tauri-apps/plugin-shell": "2.0.0-beta.6",

**Comment by HuakunShen** [comment]
I just found that in capability file I need to use absolute path for the command I am running.

```json
 {
      "name": "ffprobe",
      "cmd": "/opt/homebrew/bin/ffprobe",
      "args": true,
      "sidecar": false
},
```

I suspect it's because the app doesn't inherit PATH variable from shell when it's open, while running the app with `open` from terminal let it inherit the PATH variable.

But the executable could be anywhere in system, I can't hard code it in the capability file.

**Comment by FabianLars** [comment]
Can you try using this? https://github.com/tauri-apps/fix-path-env-rs/
