### ISSUE TITLE
[fs-extra] no repo Tags

### ISSUE THREAD

**Issue by MentalGear** [tauri-apps/plugins-workspace#141]
Installing via 
`yarn add github:tauri-apps/tauri-plugin-fs-extra#v0.1.0`

won't work since the repo has no tags defined.

**Comment by p0ryae** [comment]
Just use 

`yarn add github:tauri-apps/tauri-plugin-fs-extra` 

That should be good (for now)

**Comment by JonasKruckenberg** [comment]
We will properly publish all plugins soon, you this issues will be fully resolved then
