### ISSUE TITLE
Updater Plugin Bad Request IPC

### ISSUE THREAD

**Issue by nwehrhan** [tauri-apps/plugins-workspace#1439]
Hi,

I am trying to get the updater plugin working. In the past I have gotten a app to update fine with Tauri 1.0. I am now trying in a blank project for 2.0. 

For some reason when invoking `await update.downloadAndInstall();` on the frontend I get `Failed to load resource: the server responded with a status of 400 (Bad Request) ipc://localhost/plugin%3Aupdater%7Cdownload_and_install`. It can find the update with `import { check } from "@tauri-apps/plugin-updater";` as I can console log the output. It seems as if the plugin communication is failing. I am on Mac m2. 

I am wondering if I am missing a step to enable IPC?

![image](https://github.com/tauri-apps/plugins-workspace/assets/66650503/c50c581c-2777-44bd-b62f-1ae11d0e2e90)

**Comment by amrbashir** [comment]
seems like the pubkey and signature are not matched, could you double check that you're using a signature that was generated with the same pubkey?

**Comment by nwehrhan** [comment]
Hmm just regenerated my "2.0" test app and now getting invalid `InvalidSignature` when logging the error. The signature still sits in the JSON file version for the updater plugin like so:?
```
{
    "version": "v2.0.0",
    "notes": "Test version",
    "pub_date": "2020-06-22T19:25:57Z",
    "platforms": {
      "darwin-aarch64": {
        "signature": "sig_here",
        "url": "https://localhost/macos/two_point.app.tar.gz"
      }
    }
  }
  ```

**Comment by amrbashir** [comment]
When you build your app, it should create a `.sig` file next to your installer, copy the contents of it and paste it in `signature` field

**Comment by nwehrhan** [comment]
I restarted from step 1 using the 1.0 guide as well and now its working. So I guess it was a goof on my part with signatures.
