### ISSUE TITLE
Store plugin usage from Rust on mobile (iOS)

### ISSUE THREAD

**Issue by tdomhan** [tauri-apps/plugins-workspace#1445]
When I try to use the example code of the Store on iOS I run into 
```
Mobile plugin handled is not initialized, Perhaps you forgot to call StoreBuilder::mobile_plugin_handle
```

The example code being:
```
use tauri_plugin_store::StoreBuilder;
use serde_json::json;

fn main() {
    tauri::Builder::default()
        .plugin(tauri_plugin_store::Builder::default().build())
        .setup(|app| {
            let mut store = StoreBuilder::new("app_data.bin").build(app.handle().clone());
            store.load().expect("Failed to load store from disk");
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
```

`mobile_plugin_handle` seems to only be initialized [as part of the managed StoreCollection](https://github.com/tauri-apps/plugins-workspace/blob/6ada2af2e1de920edf8d3550c2f3a664b16a5deb/plugins/store/src/lib.rs#L335). However, when seprately calling StoreBuilder::new (as in the example) the `mobile_plugin_handle` is None. 

I need the store to set up some other state in `setup`, but I'm not sure how to avoid the above issue. 
@elkhoudiry

**Comment by tdomhan** [comment]
For now reverting to before https://github.com/tauri-apps/plugins-workspace/pull/1011 (the store plugin actually worked fine for iOS before when writing to and reading from `app_data_dir`).

**Comment by amrbashir** [comment]
You need to use `with_store` which initializes the needed mobile plugin handle, see https://github.com/tauri-apps/plugins-workspace/blob/6ada2af2e1de920edf8d3550c2f3a664b16a5deb/plugins/store/README.md?plain=1#L157
