### ISSUE TITLE
【v2】clipboard error in android

### ISSUE THREAD

**Issue by Xiaobaishushu25** [tauri-apps/plugins-workspace#1448]
I developed an Android app using tauriv2, and some of the code tried to read and write the clipboard. 
```
tauri-plugin-clipboard-manager = "2.1.0-beta.4"
```
```rust
#[tauri::command]
async fn read_clipboard<'r>(app_handle: tauri::AppHandle,state: State<'r, MyState>) -> Result<(), ()> {
    state
        .0
        .send(ClipboardMessage(app_handle.clipboard().read_text().unwrap()))
        .await
        .unwrap();
    Ok(())
}
```
This part of the code ran normally in simulation debugging and real machine debugging, but after packaging and installing it on the phone, it ran abnormally. When using the command to check the log, I found an error:
```
C:\Users\Xbss\AppData\Local\Android\Sdk\platform-tools>adb logcat | findstr /i "tauri"
06-10 12:34:16.630  8082  8141 I RustStdoutStderr: called `Result::unwrap()` on an `Err` value: PluginInvoke(InvokeRejected(ErrorResponse { code: None, message: Some("Class app.tauri.clipboard.ReadClipDataSerializer has no default (no arg) constructor"), data: () }))
```
my phone is honor 80gt, andoid 14.

**Comment by tweidinger** [comment]
@Xiaobaishushu25  does this error still persist with the latest release candidate?

**Comment by lucasfernog** [comment]
closed by https://github.com/tauri-apps/tauri/pull/10982
