### ISSUE TITLE
[fs-watch] `watch` function name conflicts with `Vue`'s `watch` fn 

### ISSUE THREAD

**Issue by seahindeniz** [tauri-apps/plugins-workspace#145]
As a workaround, we can import plugin as `import { watch as watchFile } from 'tauri-plugin-fs-watch-api';` but it might be a good choice to change the function name into something like `watchFile` or `watchDir` or `watchFS` to avoid renaming the function.

It is not the best recommendation, but it might be good to consider this upcoming conflict

**Comment by amrbashir** [comment]
you should use the workaround you mentioned because it doesn't makes sense to change the function name at all, let alone for one framework.
