### ISSUE TITLE
[fs-watch] _unwatch in example doesn't seem to work: missing field `event`

### ISSUE THREAD

**Issue by kdheepak** [tauri-apps/plugins-workspace#146]
Thanks for making this plugin!

I'm trying to run this example:

https://github.com/tauri-apps/tauri-plugin-fs-watch/blob/f29bba3da845223fa3b9b59e5a17477ca3f93c72/examples/svelte-app/src/App.svelte#L20-L25

using the following code

```
    <button
      on:click={async () => await _unwatch().catch((error) => console.log(error))}
      disabled={stopWatching === null}
    >
```

but I'm getting the following error when I click on the button that calls `_unwatch`:

![Screen Shot 2022-03-24 at 1 36 03 PM](https://user-images.githubusercontent.com/1813121/159996364-c3d35e79-5a2a-495f-bcfc-f40ca801dc2a.png)

I think it has to do with this block but I'm not sure.

https://github.com/tauri-apps/tauri-plugin-fs-watch/blob/f29bba3da845223fa3b9b59e5a17477ca3f93c72/webview-src/index.ts#L54-L56

Any suggestions on how to proceed?

**Comment by lucasfernog** [comment]
Thanks for the report. The api package was outdated and it's fixed now.

**Comment by kdheepak** [comment]
Thanks for the quick response. Also, the README has that you can use `tag = "v0.1.0"` but that appears to be from the template and not actually the case right now (there's no tags at the moment in this repo). Is there a plan to change that?
