### ISSUE TITLE
[bug][clipboard][v2] expected RGBA image data, found raw bytes

### ISSUE THREAD

**Issue by DWHengr** [tauri-apps/plugins-workspace#1463]
I used the following code and reported the error **expected RGBA image data, found raw bytes**
```js
const buffer = [255, 0, 0, 255, 0, 255, 0, 255,];
await writeImage(buffer);
```

**Comment by DWHengr** [comment]
[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 118.0.2088.76
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.78.0 (9b00956e5 2024-04-29)
    ✔ cargo: 1.78.0 (54d8815d0 2024-03-26)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 16.20.0
    - yarn: 1.22.22
    - npm: 8.19.4

[-] Packages
    - tauri [RUST]: 2.0.0-beta.22
    - tauri-build [RUST]: 2.0.0-beta.17
    - wry [RUST]: 0.40.1
    - tao [RUST]: 0.28.0
    - @tauri-apps/api [NPM]: 2.0.0-beta.13
    - @tauri-apps/cli [NPM]: 2.0.0-beta.18

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite

**Comment by amrbashir** [comment]
either create an `Image` instance using `Image.fromBytes` https://beta.tauri.app/reference/javascript/api/namespaceimage/#frombytes or provide a valid 32bpp RGBA data
