### ISSUE TITLE
[HTTP] Doesn't seem to allow all URLS like v1 tauri does.

### ISSUE THREAD

**Issue by ZelCloud** [tauri-apps/plugins-workspace#1468]
Doesn't seem like its possible to allow all urls in the allow list like it was in v1 of tauri.

Capabilities.json
```json
{
  "identifier": "http:default",
  "allow": [
      {
        "url": "https://**"
      },

      {
        "url": "http://**"
      }
    ]
},
```

Code
```javascript
import { fetch } from '@tauri-apps/plugin-http';

fetch(url, { method: "GET" })
  .then((res) => {
    console.log(res);
    return res.text()
  })
```

Result
```
error sending request for url (https://en.wikipedia.org/wiki/Landscape): error trying to connect: invalid URL, scheme is not http
```

I'd expect with the glob pattern for both HTTPS and HTTP all urls would be usable.

Edit:

Issue also persists if using singular * and only using the https capability like so

```json
{
  "identifier": "http:default",
  "allow": [
      {
        "url": "https://**" // single or double * makes no difference
      }
    ]
},
```

**Comment by FabianLars** [comment]
Can you run `cargo update` in your src-tauri dir? (If you locked the plugin version in cargo.toml with a `=` you'll have to update that). This was fixed quite some time ago.

Unless you added the http plugin with `default-features = "false"` then the tls backend will be disabled (if you do that, i'd like to know why :) ) and you have to re-enable it again with `features = ["rustls-tls"]`

**Comment by ZelCloud** [comment]
Deleted my `Cargo.lock` and deleted the deps and re-ran `tauri dev` and it worked. Not sure why I was getting outdated beta versions of the plugins. Oh well false alarm.
