### ISSUE TITLE
How to get http response headers?

### ISSUE THREAD

**Issue by hengkx** [tauri-apps/plugins-workspace#1470]
```js
// tauri-plugin-http = {version = "2.0.0-beta.9", features = ["cookies", "unsafe-headers"] }
import { fetch } from "@tauri-apps/plugin-http";
const response = await fetch();
console.log(response.headers.getSetCookie());// always []
```

**Comment by 4aiman** [comment]
I second this.
After installing the log plugin I can clearly see that cookies *are* being set:
![](https://github.com/tauri-apps/plugins-workspace/assets/2913210/d9fcc4fd-cc3e-4bc6-ad0d-4820ebd1a34e)

However, cookies in devtools are empty and show only localhost Tauri address 
(guess this is expected, as I've used the fetch from Rust backend to make the request)
![изображение](https://github.com/tauri-apps/plugins-workspace/assets/2913210/e3eb8d23-1e75-4eae-b0e2-2e710531a508)

I've tried iterating the headers, hoping to see a `set-cookie` header, but it's been stripped on the backend, it seems, as this code
```JS
  app.fetch = window.__TAURI__.http.fetch
  result1 = await app.fetch(url, request) // url = an url path; request is an instance of clientConfig 
  for (let pair of result1.headers.entries()) {
      console.log(pair)
  }
```
yields this
![изображение](https://github.com/tauri-apps/plugins-workspace/assets/2913210/ecaffa5f-0edf-40b4-893f-3564c31a9a2e)

**Comment by amrbashir** [comment]
Since the `http` plugin operates using Rust and not the browser built-in fetch, cookies are stored on the Rust side and are not accessible through JavaScript normal cookie store.

**Comment by amrbashir** [comment]
Could you explain a bit more about your use case and I will see if we can support it?

**Comment by hengkx** [comment]
Some parameters are parsed through set cookies, and we need to obtain the value of set cookies to proceed with the next request
