### ISSUE TITLE
Tauri Plugin SQL - How can I use multiples database

### ISSUE THREAD

**Issue by Snarloff** [tauri-apps/plugins-workspace#1472]
Hello.

Is there any way to use more than one type of database?

[dependencies.tauri-plugin-sql]
features = ["sqlite", "postgres", "mysql"]
version = "2.0.0-beta"

If, for example, my application needs other types of connections. If not, does anyone have any suggestions on how I can do this?
I'm using Tauri 2.

**Comment by FabianLars** [comment]
This is not supported yet. Tracked here: https://github.com/tauri-apps/plugins-workspace/issues/288 (closing this in favor of 288).

You could use the rust libraries yourself in your app, or for remote connections (postgres/mysql) there may be js packages that already work in the browser so then you could use those for psql/mysql and this plugin for sqlite.
