### ISSUE TITLE
[plugin-upload] Unable to correctly perform progress callback function.

### ISSUE THREAD

**Issue by liuhuapiaoyuan** [tauri-apps/plugins-workspace#1476]
![image](https://github.com/tauri-apps/plugins-workspace/assets/8020726/e31f1817-614e-4998-8df7-c0ee2e724e9e)

![image](https://github.com/tauri-apps/plugins-workspace/assets/8020726/8a8144e1-e9a1-4383-a72a-dffaae728aaa)

tauri:  v2

**Comment by FabianLars** [comment]
I realize that the wording on our side could be better (especially without any real docs), but the "progress" is not the total progress, but the last downloaded chunk's size. This means you'll have to add/collect them yourself and you should end up with "total".

**Comment by liuhuapiaoyuan** [comment]
yes. I think you can use 'chunkSize' instead
