### ISSUE TITLE
[localhost] `Setup(SetupError(WindowLabelAlreadyExists("main")))`

### ISSUE THREAD

**Issue by eli-front** [tauri-apps/plugins-workspace#148]
I am using the example and getting the error after running `yarn tauri dev`:
```
thread 'main' panicked at 'error while running tauri application: Setup(SetupError(WindowLabelAlreadyExists("main")))', src/main.rs:33:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error Command failed with exit code 101.
```

**Comment by FabianLars** [comment]
If i understood you correctly you copied the example into your own project? In that case the first window you configured in tauri.conf.json by default has the `"main"` label. The example does spawn a new window in main.rs, also with the `"main"` label.
So you have a few options depending on what you're actually doing
So depending on what you're actually doing you can either remove the window from tauri.conf, or change the label of one of the windows.

**Comment by Ynng** [comment]
Why did the example spawn a new window anyways?
The existing main window already has the correct localhost url and port for me

**Comment by forestsource** [comment]
FYI: https://github.com/tauri-apps/plugins-workspace/issues/160#issuecomment-1431290561

**Comment by icefee** [comment]
I make it work by remove setup,

main.rs

```rust
fn main() {
    let port = portpicker::pick_unused_port().expect("failed to find unused port");
    
    let mut context = tauri::generate_context!();
    let url = format!("http://localhost:{}", port).parse().unwrap();
    let window_url = WindowUrl::External(url);
    // rewrite the config so the IPC is enabled on this URL
    context.config_mut().build.dist_dir = AppUrl::Url(window_url.clone());
    tauri::Builder::default()
        .plugin(tauri_plugin_localhost::Builder::new(port).build())
        .invoke_handler(tauri::generate_handler![greet])
        .run(context)
        .expect("error while running tauri application");
}
```
