### ISSUE TITLE
Plugin [question][v2]- Store plugin usage as managed state 

### ISSUE THREAD

**Issue by SilenLoc** [tauri-apps/plugins-workspace#1482]
Hi,

- Tauri version 2.*
- Store Plugin version 2.*

I have a question:

When using the plugin ''Store" I understand the main idea is to use it from JS but I would like to use it in rust not only in the setup step but as a managed state in any command. 

## Why I ask this
- I could not find a documentation on that
- I was not able to figure out a solution myself.
- There is a workaround, but like this I may not need to load anything into JS and just load into the store from a command I implemented.

Thank you

**Comment by FabianLars** [comment]
Did you see with_store at the bottom of the readme? https://github.com/tauri-apps/plugins-workspace/tree/v2/plugins/store#frontend-interoperability This will also work in commands via https://v2.tauri.app/develop/calling-rust/#accessing-an-apphandle-in-commands

**Comment by SilenLoc** [comment]
> Did you see with_store at the bottom of the readme? https://github.com/tauri-apps/plugins-workspace/tree/v2/plugins/store#frontend-interoperability This will also work in commands via https://v2.tauri.app/develop/calling-rust/#accessing-an-apphandle-in-commands

I did see both but did not put them together. Thank you.
