### ISSUE TITLE
[localhost] Request for guidance

### ISSUE THREAD

**Issue by ZanzyTHEbar** [tauri-apps/plugins-workspace#149]
# Localhost to talk to devices over LAN

So, I am making an [ESP32 Data Logger](https://github.com/ZanzyTHEbar/ESP32-Data-Logger) app.

This app is designed to talk to devices on my local network, to collect and graph real-time data from them. 
The app works 100% as I would expect it to in `dev` using `yarn tauri dev`, as the dev server is running on `http`. However, as you already see coming, when I build and run the executable the app no longer works ... why ... mixed content. Tauri is hosted on `https` and the REST api's that I am hitting are `http`. Adding TLS support to the devices is not an option. 

I am an embedded C developer and have been learning Typescript and Javascript for the last year. I know pretty much nothing about rust - though I am learning. 

How on earth do I use this - or if this plugin isn't the right option - what options do I have.

I tried to use the setup in the examples but i get the error `Window named main already exists` - when i change the name of the window, it compiles and loads, but loads a new window entirely that has nothing in it (of course not) - which is obvious since the example uses the `WindowBuilder`. 

What do I do? How can I get my current window to run using this plugin? 

Is this the right plugin, or should i look elsewhere? 

Thanks :)

**Comment by FabianLars** [comment]
> I tried to use the setup in the examples but i get the error Window named main already exists 

You need to remove the window from tauri.conf.json then. You can't really "overwrite" the existing window so you need to create a new one instead.

And since tauri does not have a built-in option to use http instead this should indeed be the correct plugin.

**Comment by ZanzyTHEbar** [comment]
Thank you for the reply, i just ended up making a custom REST rust module and doing manual communication myself
