### ISSUE TITLE
[sql] SQLite file is stored on `app_config_dir`, not `app_data_dir`

### ISSUE THREAD

**Issue by phucvinh57** [tauri-apps/plugins-workspace#1499]
Regarding this [implementation](https://github.com/tauri-apps/plugins-workspace/blob/757ab74c8e0e376c56331edbfdc93fd9dd027cbd/plugins/sql/src/plugin.rs#L67), SQLite file is not saved in `app_data_dir` as described by the [usage](https://v2.tauri.app/plugin/sql/#usage:~:text=The%20path%20is%20relative%20to%20tauri%3A%3Aapi%3A%3Apath%3A%3ABaseDirectory%3A%3AApp)

Is it a mistake or an intention?

![image](https://github.com/tauri-apps/plugins-workspace/assets/69946748/a48a7856-0bd8-46cb-9c6b-1dce6a13a8ae)
![image](https://github.com/tauri-apps/plugins-workspace/assets/69946748/c04277a5-cce5-4def-91ea-206480e71146)
![image](https://github.com/tauri-apps/plugins-workspace/assets/69946748/96ddfe65-348a-47f6-8a5d-376c857d80e0)

**Comment by FabianLars** [comment]
The docs are saying BaseDirectory::App, not BaseDirectory::AppData - `App` was removed in v2 so here are the v1 docs: https://docs.rs/tauri/latest/tauri/api/path/enum.BaseDirectory.html#variant.App - In v1 this indeed was the same as `AppConfig`, so everything is working as expected, we just need to update the basedir in the docs, thanks for bringing that to our intention.

**Comment by FabianLars** [comment]
The docs update is now live. thx again
