### ISSUE TITLE
[v2] [fs] [linux] Unable to allow any path for `fs:allow-exists` permission

### ISSUE THREAD

**Issue by gnoumph** [tauri-apps/plugins-workspace#1533]
`@tauri-apps/plugin-fs` `2.0.0-beta.6`

The path to be allowed is not known in advance, but is defined by the user in a form. So I can't add it to the list of permissions.  
The path can be anywhere in the file system, including mount points such as network shares (CIFS) in `/mnt/XXX`.

I tried with:

```jsonc
// src-tauri/capabilities/default.json
"fs:default",
{
  "identifier": "fs:allow-exists",
  "allow": [
    {
      "path": "*" // "**", "/*", "/**", "/*/**", "/**/*", "/*/*/*/*", "*/*", "*/**", "**/*", "**/**", "all"
    }
  ]
}
```

But in all cases I get the `forbidden path` error.  
If I add the complete absolute path, everything works normally.

**Comment by FabianLars** [comment]
Does the file path you were testing contain a component with a `.` in front? For example `/home/username/.bashrc` ? Those require either the dot in the scope, or `"requireLiteralLeadingDot": false`.

> The path to be allowed is not known in advance, but is defined by the user in a form.

Can you use tauri's dialog plugin for this? It would extend the scope automatically with the selected path. If you need that to persist between restarts you can use the persisted-scope plugin.

**Comment by gnoumph** [comment]
Tauri's dialog plugin did the trick, thanks for your help!

**Comment by gnoumph** [comment]
Just to clarify for persistence, the `persisted-scope` plugin must be loaded in the correct order for it to work.  
As I don't know exactly what its dependencies are, I loaded it after all the others:

```rust
// src-tauri/src/main.rs
fn main() {
    tauri::Builder::default()
        .plugin(
            tauri_plugin_log::Builder::new()
                .targets([
                    Target::new(TargetKind::Stdout),
                    Target::new(TargetKind::LogDir { file_name: None }),
                ])
                .build(),
        )
        .plugin(tauri_plugin_http::init())
        .plugin(tauri_plugin_fs::init())
        .plugin(tauri_plugin_store::Builder::new().build())
        .plugin(tauri_plugin_process::init())
        .plugin(tauri_plugin_shell::init())
        .plugin(tauri_plugin_single_instance::init(|app, _args, _cwd| {
            let _ = show_window(app);
        }))
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_persisted_scope::init()) // <-- Here
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
```
