### ISSUE TITLE
[localhost] Running gives `AssetNotFound("index.html")`

### ISSUE THREAD

**Issue by elanzini** [tauri-apps/plugins-workspace#155]
I am trying to get the plugin to work with my app.
I have followed the instructions in the `README`, emptied the `windows` array in the Tauri configs, and added the code in the `main.rs`.

I can compile and everyone is happy but when the app starts I get these errors:
```
Asset `index.html` not found; fallback to index.html.html
Asset `index.html` not found; fallback to index.html/index.html
Asset `index.html` not found; fallback to index.html
AssetNotFound("index.html")
```
And then an empty white window is displayed.
I had a look at the [vanilla](https://github.com/tauri-apps/tauri-plugin-localhost/tree/dev/examples/vanilla) example and my `index.html` is available at the same location (`src/public/index.html`).

I am confused why it's not working.

**Comment by FabianLars** [comment]
You don't necessarily need to copy the structure of the example. This plugin serves the frontend files the same way the built-in custom protocol does. So what you need is a `index.html` file in the root of your configured `distDir`

**Comment by elanzini** [comment]
> You don't necessarily need to copy the structure of the example. This plugin serves the frontend files the same way the built-in custom protocol does. So what you need is a `index.html` file in the root of your configured `distDir`

I haven't changed any of the default configs. In my `tauri.conf.json` I have `"distDir": "../build"` configured and I can see there is an `index.html` in that location.

**Comment by elanzini** [comment]
After looking at the vanilla example, I modified the `devPath` to also match the `distDir`:  `"devPath": "../build"` and it's now able to serve the files

**Comment by elanzini** [comment]
Actually @FabianLars I also tried to point to `../public` so I didn't have to `npm run tauri build` every time to see the changes in `dev` but I am getting these logs and then nothing starts:
```
Asset `%PUBLIC_URL%/manifest.json` not found; fallback to %PUBLIC_URL%/manifest.json.html
Asset `%PUBLIC_URL%/manifest.json` not found; fallback to %PUBLIC_URL%/manifest.json/index.html
Asset `%PUBLIC_URL%/manifest.json` not found; fallback to index.html
```

**Comment by FabianLars** [comment]
Well normally you can ignore these logs, since manifest.json should be useless (in tauri apps) i think?

But yeah pointing to public won't work if ../build is your actual build output :)

**Comment by elanzini** [comment]
> Well normally you can ignore these logs, since manifest.json should be useless (in tauri apps) i think?
> 
> But yeah pointing to public won't work if ../build is your actual build output :)

Does this mean that using this plugin prevents the app from reloading the changes when the files have been changed on the frontend side of things?

Right now I need to run `npm run tauri build` every time and restart to see the new changes.

**Comment by FabianLars** [comment]
I'd suggest reverting the devPath change and putting the plugin behind a cfg flag to enable it only in actual builds so that `tauri dev` works as it used to.
that's what i mean with the flag:
```rs
#[cfg(dev)]
{ do_plugin_stuff() }
```

**Comment by elanzini** [comment]
@FabianLars Silly question, what other cfg flag can I use for build instead? I tried `#[cfg(build)]` without success.

**Comment by FabianLars** [comment]
`dev` is the only custom flag tauri sets, other than that there's only the cargo-native stuff: https://doc.rust-lang.org/reference/conditional-compilation.html
