### ISSUE TITLE
[feat] Haptic feedback and vibration API for mobile

### ISSUE THREAD

**Issue by httpjamesm** [tauri-apps/plugins-workspace#1554]
### Describe the problem

Right now, it doesn’t seem like there is any way to trigger haptic feedback or vibrations programatically on mobile, at least for Android.

### Describe the solution you'd like

I would like a vibration plugin which offers different modes of vibration, e.g.:

- Light/medium/hard haptic feedback
- Light/medium/hard vibration
- Vibration duration control

### Alternatives considered

I’ve tried using the navigator.vibrate() web API, but it doesn’t seem to do anything.

**Comment by FabianLars** [comment]
For what it's worth, we've recently created a plugin for a client (in public) [here](https://github.com/crabnebula-dev/plugins-workspace/tree/feat/haptics/plugins/haptics), it's not quite ready to upstream it into this repo, but it's close enough that it'd be a waste of time for others to create a new plugin for this, hence me writing this message :)

**Comment by ardasugur** [comment]
Is this feature ready for upstream? It seems like is in stable release [as in here](https://github.com/tauri-apps/plugins-workspace/blob/v2/plugins/haptics/CHANGELOG.md)
but it isn't in [plugins list](https://github.com/crabnebula-dev/plugins-workspace/blob/feat/haptics/README.md)

**Comment by FabianLars** [comment]
oops, always forget to update the readme. thanks for the headsup
