### ISSUE TITLE
[sql] Docs missing `preload` migrations info

### ISSUE THREAD

**Issue by gabeins** [tauri-apps/plugins-workspace#1555]
While following the docs instructions to use the `tauri-plugin-sql` with sqlite and use the migrations feature, I noticed the migrations were not executed at all.

### Reproduction

1. Create a new project `cargo create-tauri-app --beta`
2. Add the SQL plugin `cargo tauri add sql`
3. Update `Cargo.toml`
```diff
- tauri-plugin-sql = "2.0.0-beta.9"
+ tauri-plugin-sql = { version = "2.0.0-beta.9", features = ["sqlite"] }
```
4. Add a migration, [as described in the plugin docs](https://v2.tauri.app/plugin/sql/#adding-migrations-to-the-plugin-builder)
```diff
// src-tauri/src/main.rs

+ use tauri_plugin_sql::{Builder, Migration, MigrationKind};

fn main() {
+    let migrations = vec![
+        // Define your migrations here
+        Migration {
+            version: 1,
+            description: "create_initial_tables",
+            sql: "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);",
+            kind: MigrationKind::Up,
+        }
+    ];

    tauri::Builder::default()
        .plugin(
            tauri_plugin_sql::Builder::default()
+                .add_migrations("sqlite:mydatabase.db", migrations)
                .build(),
        )
        ...
}
```
5. Start app with `cargo tauri dev`
6. On the file system, open the `tauri::api::path::BaseDirectory::AppConfig` path
7. Notice the missing `"mydatabase.db"`
![CleanShot 2024-07-16 at 11 50 58@2x](https://github.com/user-attachments/assets/d33a7715-b3b9-43e8-8599-e6942992ed26)

### Expected behavior

Migrations are applied automatically when the plugin is initialized.

### Full `capabilities/default.json`
```json
{
  "$schema": "../gen/schemas/desktop-schema.json",
  "identifier": "default",
  "description": "Capability for the main window",
  "windows": [
    "main"
  ],
  "permissions": [
    "path:default",
    "event:default",
    "window:default",
    "app:default",
    "image:default",
    "resources:default",
    "menu:default",
    "tray:default",
    "shell:allow-open",
    "sql:default"
  ]
}
```

### Full `tauri info` output
```
WARNING: no lock files found, defaulting to npm

[✔] Environment
    - OS: Mac OS 14.5.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.79.0 (129f3b996 2024-06-10)
    ✔ cargo: 1.79.0 (ffa9cf99a 2024-06-03)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (environment override by RUSTUP_TOOLCHAIN)
    - node: 22.4.1
    - pnpm: 9.0.2
    - yarn: 1.22.22
    - npm: 10.8.2

[-] Packages
    - tauri [RUST]: 2.0.0-beta.24
    - tauri-build [RUST]: 2.0.0-beta.19
    - wry [RUST]: 0.41.0
    - tao [RUST]: 0.28.1
    - tauri-cli [RUST]: 2.0.0-beta.21
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 2.0.0-beta.21

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../src
```

**Comment by gabeins** [comment]
After a conversation with @FabianLars [on Discord](https://discord.com/channels/616186924390023171/731495028677148753/1262713791389368443), it seems the current fix is to load the DB from the client side:

```ts
import Database from "@tauri-apps/plugin-sql";
const db = await Database.load("sqlite:mydatabase.db"); // <- same db name from plugin setup!
```

The reason is that the migrations are run on the `load()` command implementation https://github.com/tauri-apps/plugins-workspace/blob/v2/plugins/sql/src/plugin.rs#L166-L169 and not when the plugin is initialized.

[A refactoring of the plugin is being considered](https://discord.com/channels/616186924390023171/731495028677148753/1262714167417114689), which may change the behavior and match the expectation of the migrations being run from the Rust side automatically when the plugin is initialized.

Related to https://github.com/tauri-apps/plugins-workspace/issues/509 and https://github.com/tauri-apps/plugins-workspace/issues/506.

**Comment by gabeins** [comment]
It seems this could be solved if there was a way to write `config.preload` value, based on https://github.com/tauri-apps/plugins-workspace/blob/v2/plugins/sql/src/plugin.rs#L313-L317

**Comment by FabianLars** [comment]
Oh my god, i totally forgot about that. You absolutely can change that value! Simply add this to your tauri.conf.json file:
```json
{
  "plugins": {
    "sql": {
      "preload": ["dbname"]
    }
  }
}
```

**Comment by gabeins** [comment]
I JUST found it in the docs as well! 🤦 
https://v2.tauri.app/develop/plugins/#plugin-configuration

**Comment by gabeins** [comment]
I've opened a couple of PRs to update the readme and the v2 docs for the plugin:
- v2 docs: https://github.com/tauri-apps/tauri-docs/pull/2417
- readme: https://github.com/tauri-apps/plugins-workspace/pull/1557
