### ISSUE TITLE
[bug][global-shortcut][v2] Error message when adding shortcut keys from the front-end

### ISSUE THREAD

**Issue by DWHengr** [tauri-apps/plugins-workspace#1558]
```js
import {register} from '@tauri-apps/plugin-global-shortcut';
register(['CommandOrControl+Shift+C', 'Alt+A'], (event) => {
    console.log(`Shortcut ${event.shortcut} triggered`);
});
```
**Uncaught (in promise) invalid args `shortcut` for command `register`: command register missing required key shortcut**
![e6588cc54a7466c56091a675fb54034a](https://github.com/user-attachments/assets/aac0e19e-52aa-47da-ad7c-85f46ff1e4be)

**Comment by FabianLars** [comment]
This _should_ mean that the rust side of the plugin is outdated. Try running `cargo update` in the src-tauri dir please.

**Comment by DWHengr** [comment]
It's possible. I updated all the versions and there were no issues.
