### ISSUE TITLE
[http][v2] url not allowed on the configured scope

### ISSUE THREAD

**Issue by ktecho** [tauri-apps/plugins-workspace#1559]
I get this when using latest version of "HTTP client" plugin. I also tested the git version of both parts (rust and js), with the same result:

```
[Error] Unhandled Promise Rejection: url not allowed on the configured scope: http://127.0.0.1:9740/getbalance
```
+page.svelte
```
<script>
     async function do_request() {
		const headers = new Headers();
		headers.append(
			'Authorization',
			"Basic ${btoa(':71ec453e388cdddff03f2dd31bb26230e09af625e922ecc4923a9b9561a27197')}"
		);

		const response = await fetch('http://127.0.0.1:9740/getbalance', {
			method: 'GET',
			headers: headers
		});
     }
</script>
```

Cargo.toml
```
[dependencies]
tauri = { version = "2.0.0-beta.24", features = [] }
tauri-plugin-http = "2.0.0-beta.12"
```

package.json
```
"dependencies": {
	"@tauri-apps/api": "^2.0.0-beta.15",
	"@tauri-apps/plugin-http": "^2.0.0-beta.8"
}
```

base.json
```
{
    "identifier": "http:default",
    "permissions": [
      {
        "identifier": "http:default",
        "allow": [
          {
            "url": "http://127.0.0.1:9740"
          },
          {
            "url": "http://127.0.0.1:9740/*"
          }
        ]
      }
    ]
  }
```

Full tauri info output
```
[✔] Environment
    - OS: Ubuntu 24.04 X64
    ✔ webkit2gtk-4.1: 2.44.2
    ✔ rsvg2: 2.58.0
    ✔ rustc: 1.79.0 (129f3b996 2024-06-10)
    ✔ cargo: 1.79.0 (ffa9cf99a 2024-06-03)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 20.15.1
    - yarn: 1.22.22
    - npm: 10.7.0

[-] Packages
    - tauri [RUST]: 2.0.0-beta.24
    - tauri-build [RUST]: 2.0.0-beta.19
    - wry [RUST]: 0.41.0
    - tao [RUST]: 0.28.1
    - @tauri-apps/api [NPM]: 2.0.0-beta.15
    - @tauri-apps/cli [NPM]: 2.0.0-beta.21

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../public
    - devUrl: http://localhost:5173/
    - framework: Svelte
    - bundler: Vite

```

**Comment by ktecho** [comment]
Also, the documentation is not updated, because if I copy the `base.json` from here https://beta.tauri.app/plugin/http-client/ or here https://v2.tauri.app/reference/javascript/http/, it will complain that "identifier" is not found. That's why I put "identifier" twice in my "base.json".

**Comment by amrbashir** [comment]
> Also, the documentation is not updated, because if I copy the `base.json` from here [beta.tauri.app/plugin/http-client](https://beta.tauri.app/plugin/http-client/) or here [v2.tauri.app/reference/javascript/http](https://v2.tauri.app/reference/javascript/http/), it will complain that "identifier" is not found. That's why I put "identifier" twice in my "base.json".

the first identifier is the identifier of the capability file, not the permission to be used

**Comment by ktecho** [comment]
> > Also, the documentation is not updated, because if I copy the `base.json` from here [beta.tauri.app/plugin/http-client](https://beta.tauri.app/plugin/http-client/) or here [v2.tauri.app/reference/javascript/http](https://v2.tauri.app/reference/javascript/http/), it will complain that "identifier" is not found. That's why I put "identifier" twice in my "base.json".
> 
> the first identifier is the identifier of the capability file, not the permission to be used

What would be the identifier for the `base.json` file? I tried with `base`, but it doesn't work.

**Comment by ktecho** [comment]
I changed base.json to this:

```
{
    "identifier": "http.phoenix",
    "permissions": [
      {
        "identifier": "http:default",
        "local": true,
        "windows": ["*"],
        "allow": [
          {
            "url": "http://localhost:9740/*"
          },
          {
            "url": "http://**/"
          }
        ]
      }
    ]
  }
```

and added this to tauri.conf.json:
```
    "security": {
      "csp": null,
      "capabilities": ["http.phoenix"]
    }
  }
```


and now I get this:

```
Unhandled Promise Rejection: http.fetch not allowed on window main, webview main, allowed windows: , allowed webviews: , referenced by capability: http.phoenix, permission: default
```

I've tried with `"windows": ["*"],` and `"windows": ["main"],`, but it doesn't work.

**Comment by ktecho** [comment]
I recommend using this steps to create your app so your http plugin is configured and working in v2: https://github.com/tauri-apps/plugins-workspace/issues/1484#issuecomment-2222169301

**Comment by amrbashir** [comment]
I just retested this issue and I can't reproduce any bugs, if you still have issues, please ping me.

**Comment by qinsehm1128** [comment]
> 我刚刚重新测试了这个问题，但无法重现任何错误，如果您仍然有问题，请联系我。
Hi! I had the same problem

**Comment by qinsehm1128** [comment]
> 我刚刚重新测试了这个问题，但无法修复任何错误，如果您仍然有问题，请联系我。

const response = await fetch('http://127.0.0.1:16888/creatModel', {
    method: 'POST',
    body:data
});

In this code, you can request other public urls, but you cannot request localhost,
This is an error => "url not allowed on the configured scope: http://127.0.0.1:16888/creatModel" 

{
  "$schema": "../gen/schemas/desktop-schema.json",
  "identifier": "default",
  "description": "Capability for the main window",
  "windows": [
    "main"
  ],
  "remote": {
    "urls": ["https://**","http://**" ]

  },

  "permissions": [
    "core:default",
    "shell:allow-open",
    "dialog:allow-open",
    "dialog:default",

    {
      "identifier": "http:default",
      "allow": [{ "url": "http://127.0.0.1/*" },{ "url": "https://127.0.0.1/*" }]
    }

  ]
}


this is my conf , can you tell me if my configuration is wrong or something else is missing?

**Comment by qinsehm1128** [comment]
> 我刚刚重新测试了这个问题，但无法修复任何错误，如果您仍然有问题，请联系我。

`{
  "$schema": "../gen/schemas/desktop-schema.json",
  "identifier": "default",
  "description": "Capability for the main window",
  "windows": [
    "main"
  ],
  "remote": {
    "urls": ["https://**","http://**" ]

  },

  "permissions": [
    "core:default",
    "shell:allow-open",
    "dialog:allow-open",
    "dialog:default",

    {
      "identifier": "http:default",
      "allow": [{ "url": "http://127.0.0.1/*" },{ "url": "https://127.0.0.1/*" }]
    }

  ]
}
`

**Comment by amrbashir** [comment]
try `http://127.0.0.1:*` or `http://127.0.0.1:*/*`

**Comment by qinsehm1128** [comment]
> try `http://127.0.0.1:*` or `http://127.0.0.1:*/*`

Thank you very much for your answer, this problem did not occur after I tried, but the following return value will appear in the post request, I do not know what causes it, this tauri1.0 is completely different, can you tell me why?


{
    "status": 502,
    "statusText": "Bad Gateway",
    "headers": [
        [
            "connection",
            "close"
        ],
        [
            "content-length",
            "0"
        ]
    ],
    "url": "http://127.0.0.1:16888/creatModel",
    "rid": 2805294189
}

**Comment by qinsehm1128** [comment]
> > try `http://127.0.0.1:*` or `http://127.0.0.1:*/*`
> 
> Thank you very much for your answer, this problem did not occur after I tried, but the following return value will appear in the post request, I do not know what causes it, this tauri1.0 is completely different, can you tell me why?
> 
> { "status": 502, "statusText": "Bad Gateway", "headers": [ [ "connection", "close" ], [ "content-length", "0" ] ], "url": "http://127.0.0.1:16888/creatModel", "rid": 2805294189 }

I'll use the browser's native fecth function for the moment
