### ISSUE TITLE
[localhost] Continue to improve documents

### ISSUE THREAD

**Issue by Jzow** [tauri-apps/plugins-workspace#156]
What needs to be done for the readme file

- [x] update `src-tauri/src/main.rs` example code.
- [x] update src-tauri/Cargo.toml conf file. (If this crate has been published to [crates.io](https://crates.io/))

**Comment by lucasfernog** [comment]
I just published the crate btw.

**Comment by Jzow** [comment]
@lucasfernog I'm not sure whether tauri needs to introduce **api-all** features, If need adjust, I modify it.

**Comment by lucasfernog** [comment]
No need for api-all.

**Comment by Jzow** [comment]
> No need for api-all.

OK, I should go to bed. Bye.
