### ISSUE TITLE
[feat] Enable Startup Hide All Windows

### ISSUE THREAD

**Issue by ayangweb** [tauri-apps/plugins-workspace#1574]
`tauri_plugin_autostart`

Hey👋, my current app has multiple windows, it shows all of them on manual startup, but I want to hide all of them on auto startup, how can I do this?

**Comment by ayangweb** [comment]
https://github.com/ayangweb/EcoPaste/pull/211

This is my current solution idea, it has no problem with windows and macos, linux I don't have a test machine and don't know what's going on!

**Comment by amrbashir** [comment]
The way you implemented it in https://github.com/ayangweb/EcoPaste/pull/211 is the correct way, closing this issue since there is nothing to do on our part.
