### ISSUE TITLE
[localhost] When I delete something in Windows it says window.__tauri_IPc__ is not a function

### ISSUE THREAD

**Issue by Sunnnner** [tauri-apps/plugins-workspace#159]
![image](https://user-images.githubusercontent.com/9432907/172583414-e6330308-f763-4db2-bfd9-86a943cb77e6.png)
![image](https://user-images.githubusercontent.com/9432907/172583498-9fb22be2-fe8f-4c77-a1f4-c5e4e2aedebd.png)
![image](https://user-images.githubusercontent.com/9432907/172583549-64341b68-f307-485d-9e32-51f388a9921e.png)
![image](https://user-images.githubusercontent.com/9432907/172583595-f520b623-df05-423e-8a28-532c9c397488.png)

info:
![image](https://user-images.githubusercontent.com/9432907/172583811-1e890bf0-c7fd-40c9-ab21-e2f2359ef7a9.png)

**Comment by xiaowang-web** [comment]
[https://github.com/tauri-apps/tauri/issues/4759](url)

Using Tauri plugin localhos, you cannot call fs to write files in windows

**Comment by lucasfernog** [comment]
I just updated our example to enable the IPC on the localhost URL. Check it out :)

**Comment by elanzini** [comment]
I have tried to use the updated example to integrate this into my app but I still see this in the console:
```
Unhandled Promise Rejection: TypeError: window.__TAURI_IPC__ is not a function. 
(In 'window.__TAURI_IPC__(ci({cmd:e,callback:a,error:i},t))', 'window.__TAURI_IPC__' is undefined)
```

**Comment by lucasfernog** [comment]
@elanzini can you share the main.rs code here? You also need to change the `run` call to `.run(context)`.

**Comment by elanzini** [comment]
> @elanzini can you share the main.rs code here? You also need to change the `run` call to `.run(context)`.

```rust
use tauri::{utils::config::AppUrl, window::WindowBuilder, WindowUrl};

fn main() {
  let port = portpicker::pick_unused_port().expect("failed to find unused port");
  let mut context = tauri::generate_context!();
  let url = format!("http://localhost:{}", port).parse().unwrap();
  let window_url = WindowUrl::External(url);
  context.config_mut().build.dist_dir = AppUrl::Url(window_url.clone());
  context.config_mut().build.dev_path = AppUrl::Url(window_url.clone());

  tauri::Builder::default()
    .system_tray(make_tray())
    .on_system_tray_event(handle_tray_event)
    .menu(make_menu())
    .on_menu_event(|event| match event.menu_item_id() {
      "Hide" => match event.window().hide() {
        Ok(_) => {}
        Err(e) => eprintln!("{}", e),
      },
      _ => {}
    })
    .invoke_handler(tauri::generate_handler![
      my_custom_function
    ])
    .plugin(tauri_plugin_localhost::Builder::new(port).build())
    .setup(move |app| {
      WindowBuilder::new(app, "main".to_string(), window_url)
        .title("Localhost example")
        .decorations(false)
        .fullscreen(false)
        .build()?;
      Ok(())
    })
    .run(context)
    .expect("error while running tauri application");
}
```

And I have updated the `tauri.conf.json` as follows:
```
"build": {
    "beforeBuildCommand": "npm run build",
    "beforeDevCommand": "npm run start",
    "devPath": "../build",
    "distDir": "../build",
    "withGlobalTauri": true
  },
```

Btw, the import in the `README` needs to be fixed

**Comment by lucasfernog** [comment]
Works on my end, are you using latest tauri @elanzini ? Also which OS are you running? (shouldn't matter but just as a sanity check).

**Comment by Sunnnner** [comment]
> I just updated our example to enable the IPC on the localhost URL. Check it out :)

thank you for your efforts

**Comment by elanzini** [comment]
> Works on my end, are you using latest tauri @elanzini ? Also which OS are you running? (shouldn't matter but just as a sanity check).

`cargo update` did the trick - thanks a lot @lucasfernog 🍻
