### ISSUE TITLE
[store] Mistypes in TS part of the lib

### ISSUE THREAD

**Issue by dkzlv** [tauri-apps/plugins-workspace#16]
I believe there are two mistypes:

1. [here](https://github.com/tauri-apps/tauri-plugin-store/blob/dev/webview-src/index.ts#L117) should go `T[]` for function return value
2. [here](https://github.com/tauri-apps/tauri-plugin-store/blob/dev/webview-src/index.ts#L189) should go `T | null` for `value` argument

**Comment by JonasKruckenberg** [comment]
I agree with the changes, could you open a quick PR for this?
