### ISSUE TITLE
can't install fs for v2: failed to select a version for `webkit2gtk-sys`

### ISSUE THREAD

**Issue by zoaha** [tauri-apps/plugins-workspace#1615]
```
error: failed to select a version for `webkit2gtk-sys`.
    ... required by package `wry v0.18.3`
    ... which satisfies dependency `wry = "^0.18.3"` of package `tauri-runtime-wry v0.9.0`
    ... which satisfies dependency `tauri-runtime-wry = "^0.9.0"` of package `tauri v1.0.0`
    ... which satisfies dependency `tauri = "^1"` of package `test-thing' v0.0.0 
versions that meet the requirements `^0.18` are: 0.18.0

the package `webkit2gtk-sys` links to the native library `web_kit2`, but it conflicts with a previous package which links to `web_kit2` as well:
package `webkit2gtk-sys v2.0.1`
    ... which satisfies dependency `ffi = "^2.0.1"` of package `webkit2gtk v2.0.1`     
    ... which satisfies dependency `webkit2gtk = "=2.0.1"` of package `tauri v2.0.0-beta.25`
    ... which satisfies dependency `tauri = "^2.0.0-beta.25"` of package `tauri-plugin-fs v2.0.0-beta.12`
    ... which satisfies dependency `tauri-plugin-fs = "^2.0.0-beta.12"` of package `test-thing' v0.0.0 
```

only ran 2 commands:
npm create tauri-app@latest -- --beta
and
npm install --save-dev @tauri-apps/cli@next

node v22.4
npm v10.8

windows 11 with latest updates

**Comment by FabianLars** [comment]
> only ran 2 commands:
> npm create tauri-app@latest -- --beta

Which npm version did you use? This command works for me but in your case it seemed to have ignored the `--beta` flag for some reason 🤔

**Comment by FabianLars** [comment]
Also, which selections did you make in the create-tauri-app prompt?

**Comment by zoaha** [comment]
![image](https://github.com/user-attachments/assets/fc17c3fd-6766-4af9-bf6c-7b71ff8eb760)   
and     
![image](https://github.com/user-attachments/assets/23774c0a-7dda-41ab-93a8-262dfaa7b53b)
with
node v22.4
npm v10.8
on
windows 11 with latest updates

**Comment by zoaha** [comment]
turns out the cargo version works
`cargo create-tauri-app --rc`
npm version still does not

**Comment by zoaha** [comment]
i'll close this as it's not specific to plugins but rather the create app, tracking: https://github.com/tauri-apps/create-tauri-app/issues/745
