### ISSUE TITLE
Should `FileResponse` be `#[non_exhaustive]`?

### ISSUE THREAD

**Issue by anatawa12** [tauri-apps/plugins-workspace#1623]
Currently `tauri_plugin_dialog::FileResponse` is not `#[non_exhaustive]` but this means adding fields to `tauri_plugin_dialog::FileResponse` is braking changes.

Is this fine?

**Comment by anatawa12** [comment]
FileResponse was exported in #837 without discussion about `non_exhaustive` so I feel it might not be expected.

**Comment by anatawa12** [comment]
This is about `plugin: dialog`, not `plugin: fs`

**Comment by FabianLars** [comment]
whoops
