### ISSUE TITLE
[sql] Where is database saved?

### ISSUE THREAD

**Issue by cindy-do** [tauri-apps/plugins-workspace#1653]
I'm using sqlite and I put "test.db" in my root folder of my project, but for some reason I don't think it's loading it correctly. Where should I save my db file? Or do I need to use migrations to initialize the tables?

I don't understand what this comment means:
`The path is relative to tauri::api::path::BaseDirectory::App`

**Comment by FabianLars** [comment]
> Or do I need to use migrations to initialize the tables?

Yep, that's really the way to go right now.
If you want to have a prebuilt .db file you would have to include it in the bundle yourself (via tauri's resources feature, or by moving it into the distDir, or by using include_bytes in rust) and then write it it the expected location on the first app start yourself.

> The path is relative to tauri::api::path::BaseDirectory::App

It means that this https://tauri.app/v1/api/js/path#appconfigdir function is used as the location (for example on windows `AppData/Roaming/bundle-id/yourdb.db`).

**Comment by zennolux** [comment]
AppData/Roaming/bundle-id/yourdb.db).

But there is no `bundle-id` located in AppData,  I have searched the whole computer to find `mydb.db`, but unfortunately nothing matched

**Comment by FabianLars** [comment]
bundle-id is what you set as "identifier" in your tauri.conf.json

if there's no db file in that path you likely didn't write to it yet

**Comment by zennolux** [comment]
Thanks.  Finally, I found it via the Android Studio Emulator's `device explorer`,  because my application is an Android App.

**Comment by Alirezaaraby** [comment]
in windows you can use `Win + R` then type %APPDATA% and looks for the folder with the name of identifier which defined in tauri.config.js
