### ISSUE TITLE
[bug] In the `invoke` method, if the `options.headers` contain English, `request.body()` will return `Json(Object {"0": Number()})` instead of `Raw([])`.

### ISSUE THREAD

**Issue by SRutile** [tauri-apps/plugins-workspace#1667]
In the writeFile function, when the path is a string that contains Chinese characters or spaces, and options.baseDir is not provided, it can lead to errors. It uses request.body() to obtain the data. Normally, it should return Raw([]), but when there are Chinese characters or spaces, it returns Json(Object {"0": Number()}). This problem also exists in the invoke method.

**Comment by amrbashir** [comment]
I think this has been fixed in the latest release of `tauri-plugin-fs`, please re-test and let us know if you still have issues.
