### ISSUE TITLE
[log] potential log file loss with file rotation enabled

### ISSUE THREAD

**Issue by ingwinlu** [tauri-apps/plugins-workspace#167]
https://github.com/tauri-apps/tauri-plugin-log/blob/dev/src/lib.rs#L281

if file rotation happens twice on the same day the 'initial' rotated file is silently overwritten.

Suggested way forward:
additionally include time in filename to avoid overwrite

Happy to implement that if you are ok with it.

```  
  let log_targets = [
    // LogTarget::LogDir,
    LogTarget::Folder("./logs".into()),
    LogTarget::Stdout,
    LogTarget::Webview,
  ];
tauri::Builder::default()
    .plugin(
      LoggerBuilder::new()
        .rotation_strategy(RotationStrategy::KeepAll)
        .max_file_size(1000)
        .level(LevelFilter::Debug)
        .targets(log_targets)
        .build(),
    )
```

**Comment by JonasKruckenberg** [comment]
Yeah, should just be a matter of adding it to the chrono time fmt string. Shoot us a PR!

**Comment by ingwinlu** [comment]
Done
