### ISSUE TITLE
[log] Can't install

### ISSUE THREAD

**Issue by jolic** [tauri-apps/plugins-workspace#168]
How can this plugin be installed in Tauri?

**Comment by jolic** [comment]
error: failed to get `tauri-plugin-log` as a dependency of package `...`

Caused by:
  failed to load source for dependency `tauri-plugin-log`

Caused by:
  Unable to update https://github.com/tauri-apps/tauri-plugin-log?tag=v0.1.0

Caused by:
  failed to find tag `v0.1.0`

Caused by:
  reference 'refs/remotes/origin/tags/v0.1.0' not found; class=Reference (4); code=NotFound (-3)

**Comment by FabianLars** [comment]
The plugin wasn't released so yet. Just remove the `tag` and it should pull the latest version automatically.
