### ISSUE TITLE
[bug] SQL plugin doesn't work in v2

### ISSUE THREAD

**Issue by dominictobias** [tauri-apps/plugins-workspace#1681]
### Describe the bug

Trying to connect to an SQL database throws:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'invoke')
    at invoke (core.js:118:39)
    at _Database.load (index.js:32:29)
    at index.tsx:6:27Understand this error
```
    
Here:
    
```ts
async function invoke(cmd, args = {}, options) {
    return window.__TAURI_INTERNALS__.invoke(cmd, args, options);
}
```

### Reproduction

`bun create tauri-app --rc` (I used Solid tempalte)

`bun add @tauri-apps/plugin-sql`

Follow install steps here:

Cargo.toml:

```toml
tauri-plugin-sql = { version = "2.0.0-rc", features = [
  "sqlite",
  # "postgres",
  # "mysql",
] }
```

(Last time I checked the plugin only support one SQL flavor at time which would be a terrible shame considering SQLX support multiple and means that an SQL explorer/editor would have to make a custom one)

`srx/index.tsx`:

```ts
import Database from "@tauri-apps/plugin-sql";

const db = await Database.load("sqlite:test.db");
```

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.5.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.80.1 (3f5fd8dd4 2024-08-06)
    ✔ cargo: 1.80.1 (376290515 2024-07-16)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 20.11.0
    - pnpm: 9.6.0
    - yarn: 1.22.19
    - npm: 10.8.2
    - bun: 1.1.24

[-] Packages
    - tauri [RUST]: 2.0.0-rc.3
    - tauri-build [RUST]: 2.0.0-rc.3
    - wry [RUST]: 0.42.0
    - tao [RUST]: 0.29.0
    - @tauri-apps/api [NPM]: 2.0.0-rc.2
    - @tauri-apps/cli [NPM]: 2.0.0-rc.4

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: SolidJS
    - bundler: Vite
```

**Comment by FabianLars** [comment]
Just to be sure, you're testing this inside a tauri window and not your normal browser, right? You're the first one to report this so i assume it's something specific to your project or to how you're testing it.

> Last time I checked the plugin only support one SQL flavor at time which would be a terrible shame considering SQLX support multiple and means that an SQL explorer/editor would have to make a custom one

I have a local branch where i was working on it but i'm currently out of office so no more progress for a while. sqlx' support for multiple backens is honestly a bit lacking though.

Once i'm back i'll test it myself :)

**Comment by dominictobias** [comment]
Ah erm good guess, I ran `bun dev` and clicked on the locahost URL in the browser but of course it needs to be outside for SQL TCP 😅

I have a sep. issue trying to load the DB (SQLite) `sql.load not allowed. Permissions associated with this command: sql:allow-load, sql:default` but I'll work through that

Thanks!

**Comment by andrii-bodnar** [comment]
Hi @sekoyo, have you managed to resolve the `sql.load not allowed` issue? 

I've even tried to allow everything in the capability configuration, but with no success.

```
"permissions": [
  "core:default",
  "shell:allow-open",
  "sql:default",
  "sql:allow-load",
  "sql:allow-execute",
  "sql:allow-close",
  "sql:allow-select"
],
```

**Comment by shuTwT** [comment]
> "sql:allow-load",

Add the window you need permission to `windows`

```` json
"windows": [
    "main",
    "your window"
  ],
  "permissions": [
    "core:default",
    "shell:default",
    "shell:allow-open",
    "sql:default",
    "sql:allow-load",
    "sql:allow-execute",
    "sql:allow-close",
    "sql:allow-select"
]
````
