### ISSUE TITLE
Adding plugin to project fails to install NPM dependency

### ISSUE THREAD

**Issue by romatallinn** [tauri-apps/plugins-workspace#1697]
# Problem
`pnpm tauri add process --verbose`

```
> tauri "add" "process" "--verbose"
    Info [tauri_cli::helpers::cargo] Installing Cargo dependency "tauri-plugin-process"...
    Info [tauri_cli::helpers::npm] Installing NPM dependency "@tauri-apps/plugin-process@2.0.0-rc"...
    Error [tauri_cli_node] Failed to install NPM dependency
 ELIFECYCLE  Command failed with exit code 1.
```

# Reproduce
The issue is reproducable on a dummy project: 
```
pnpm create tauri-app --rc
cd tauri-app
npm install
npm run tauri dev
```

# Hypothesis
The script attempts to install `@tauri-apps/plugin-process@2.0.0-rc`. Version `2.0.0-rc` doesn't exist, but `2.0.0-rc.0` does ([npm versions](https://www.npmjs.com/package/@tauri-apps/plugin-process?activeTab=versions)).

**Comment by romatallinn** [comment]
`pnpm tauri add process@2.0.0-rc.0` works.

**Comment by amrbashir** [comment]
This should be fixed in the next release, see https://github.com/tauri-apps/tauri/pull/10795
