### ISSUE TITLE
[bug][fs][v2] unable to get path from XX

### ISSUE THREAD

**Issue by BTMuli** [tauri-apps/plugins-workspace#1704]
When I want to read a text file such as `C://users/user/temp.json`, `fs.readTextFile` is work.

But it reports the `unable to get path from c://users/user/temp.json` error recently.

+ `tauri-plugin-fs`: v2
+ `@tauri-apps/plugin-fs`: 2.0.0-rc.1

**Comment by BTMuli** [comment]
![image](https://github.com/user-attachments/assets/d563cbb7-cf82-48d0-91f1-f22d30923704)
![image](https://github.com/user-attachments/assets/9310f399-5c3e-4930-9773-42279dd8dac8)

**Comment by BTMuli** [comment]
I'm sure https://github.com/tauri-apps/plugins-workspace/pull/1658/commits/f8ba7e8e causes this bug😅

**Comment by etekinalp** [comment]
Hello I am also facing the same path and fs issues on windows. I am not able to read a json path nor check an path for existence with the exist function from the fs plugin for tauri v2. I tried multiple rc versions but all of them fail in the end. Some bug got introduced then recently which might cause pathing issues.

**Comment by BTMuli** [comment]
> Hello I am also facing the same path and fs issues on windows. I am not able to read a json path nor check an path for existence with the exist function from the fs plugin for tauri v2. I tried multiple rc versions but all of them fail in the end. Some bug got introduced then recently which might cause pathing issues. 

This bug accurs after https://github.com/tauri-apps/plugins-workspace/pull/1658 merged,you could lock the plugin version to an exact commit before it to prevent this bug.

**Comment by etekinalp** [comment]
Heya I tried that all now the last hours but nothing seems to solve the issue unfortunately. 
The weird thing is on macos there are no issues it is only affecting windows on my end. I matched the versions to my macos one and still no luck.

**Comment by BTMuli** [comment]
> Heya I tried that all now the last hours but nothing seems to solve the issue unfortunately. 

https://github.com/BTMuli/TeyvatGuide/blob/master/src-tauri%2FCargo.lock This is my proj lock file,the plugin fs is beta11 version and everything works well.

**Comment by etekinalp** [comment]
Thank you so much BTMuli! Thanks to your proj lock file example I was able to make it work again using beta11! Really appreciate it! Also I learned new stuff now with project locking because before I was mainly changing the js guest bindings for the nextjs part whereas in my cargo.toml I kept it on v2 for all the plugins BUT the key was the cargo.lock file as you pointed it out! Thank youuuu

**Comment by ShaunSHamilton** [comment]
I get the same issue. The following updates were breaking changes:
- `@tauri-apps/plugin-dialog@2.0.0-rc.1`
- `@tauri-apps/plugin-fs@2.0.0-rc.3`

So, to fix, you need to pin your deps:

```json
"dependencies": {
    "@tauri-apps/plugin-dialog": "2.0.0-rc.0",
    "@tauri-apps/plugin-fs": "2.0.0-rc.2",
}
```

```toml
tauri-plugin-dialog = "=2.0.0-rc.2"
tauri-plugin-fs = "=2.0.0-rc.0"
```
