### ISSUE TITLE
[tauri-plugin-single-instance][v1] Error starting project

### ISSUE THREAD

**Issue by ayangweb** [tauri-apps/plugins-workspace#1729]
Report Error Details:

https://github.com/EcoPasteHub/EcoPaste/actions/runs/10694674008/job/29646832896

Because I used `tauri-plugin-sql`, starting the project prompted to upgrade `rustc` to 1.80, but after the upgrade starting the project `tauri-plugin-single-instance` reported an error!

<img width="648" alt="image" src="https://github.com/user-attachments/assets/0ce78be5-babe-46dc-938f-4069340ff47c">

**Comment by FabianLars** [comment]
The single-instance plugin should work now https://github.com/tauri-apps/plugins-workspace/commit/5c249a1a1076ac78cfc0ed4c2857cf7e2540b1cc - thanks for the report here too. The rustc version requirement won't change because of `sqlx`. If it's too new for you, you can use an older commit.

**Comment by ayangweb** [comment]
Okay, I'll try again. Thanks
