### ISSUE TITLE
[positioner] cant get TrayRight to work

### ISSUE THREAD

**Issue by farfromrefug** [tauri-apps/plugins-workspace#173]
I am trying to use TrayRight for positioning and i get this error:
![image](https://user-images.githubusercontent.com/655344/182159823-3acf8228-ca8f-48fd-a10e-94baa77fbe94.png)

I am not sure why

**Comment by farfromrefug** [comment]
Found the issue. `features = ["system-tray"]` needs to be added in the plugin dep and not only tauri.

**Comment by farfromrefug** [comment]
ACtually i must reopen this issue. Cause now i get a crash at runtime when using it 
```
thread 'main' panicked at 'Tray position not set', /home/mguillon/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-plugin-positioner-1.0.4/src/ext.rs:138:11
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by keroserene** [comment]
@farfromrefug ran into a very similar issue. Solved by adding this line (and import) from the example:
[on_tray_event(app, &event);](https://github.com/JonasKruckenberg/tauri-plugin-positioner/blob/main/examples/svelte-app/src-tauri/src/main.rs#L37)

(seems like a strange undocumented dependency?)

**Comment by JonasKruckenberg** [comment]
It's actually needed yeah, is it undocumented though? That's a big issue then!

Edit: I also totally agree it's a weird dependency, but plugins currently don't have hooks to listen for system tray events, that's why this hook workaround is needed.

Edit 2: I updated the Readme example to be correct, thanks for reporting this!

**Comment by farfromrefug** [comment]
@keroserene @JonasKruckenberg thank you both for this! will fix my app right away
