### ISSUE TITLE
[updater] Updating macOS app from Tauri v1 to v2 fails to restart

### ISSUE THREAD

**Issue by calejvaldez** [tauri-apps/plugins-workspace#1746]
I have a Tauri app, and when I attempt to update a v1 app to a v2 version, the program gets stuck when I select "Yes" after being asked to restart.

The v1 version ends up being replaced in the /Applications folder, but it just doesn't restart to the v2 version.

**Comment by FabianLars** [comment]
Can you check whether it's the same as https://github.com/tauri-apps/plugins-workspace/issues/1724? So, do the file names differ?

edit: also linking https://github.com/tauri-apps/tauri/issues/10355 just so we don't forget to close anything once resolved.

**Comment by calejvaldez** [comment]
The files names don't differ. They both end up being `You Are Typing.app`. I check the Applications folder and only one version exists. When I manually reset it, I check the About menu option and I see that the old version was properly replaced.

These seem to be two different problems.

**Comment by FabianLars** [comment]
Okay, thanks. Since this is the v1 updater failing and not this plugin i'll mark this as an upstream issue. On that note, is the project in question public so we can check it out?

**Comment by calejvaldez** [comment]
Yeah, it's [You Are Typing](https://github.com/calejvaldez/YouAreTyping/).

I should mention that 1.3.3 and 1.3.4 are the ones with Tauri v2. I eventually went back to v1.

Sorry for all the issues, but thank you for working on it!! 🫡

**Comment by FabianLars** [comment]
so i assume updates from v1 to v1 work fine meaning it's not a permission issue (which would be a known issue on macos) 🤔

**Comment by calejvaldez** [comment]
Yup! v1->v1 work perfectly fine. :)

Edit: v1 -> v2 is where issues arise. ~~and v2 -> v2 doesn't display the update dialog, as mentioned in #1747.~~

Edit 2: Found out the Updater plugin requires us to manually check for updates. My bad!

**Comment by tweidinger** [comment]
Is the issue solved on your end then @calejvaldez?

**Comment by calejvaldez** [comment]
@tweidinger Issue is resolved for #1747, not for this issue. The v2 -> v2 problem was unrelated to this one, I just thought I should mention it. :)

**Comment by lucasfernog** [comment]
hmm I've recently written a e2e test for the v1->v2 updater, it's working but i'll test with your repo to see what's missing.
EDIT: oh it's actually the restart step.. interesting, i'll get to it tomorrow

**Comment by calejvaldez** [comment]
@lucasfernog That might be a bit tricky because I reverted the project to v1 in 1.3.5.

The v2 projects are 1.3.3 and 1.3.4... though I don't know how we'd test the updater if the latest version is 1.3.6 which is built with v1. :c

**Comment by lucasfernog** [comment]
no worries we'll figure it out

**Comment by calejvaldez** [comment]
Closing as a fix was merged! :)
