### ISSUE TITLE
Registered global shortcut handler is called twice when pressed.

### ISSUE THREAD

**Issue by jason89521** [tauri-apps/plugins-workspace#1748]
When I press the registered shortcut (`ALT + Space`), the handler is called twice, as shown in the following output:

```sh
shortcut: HotKey { mods: Modifiers(ALT), key: Space, id: 2201978783 }
shortcut: HotKey { mods: Modifiers(ALT), key: Space, id: 2201978783 }
```

Here is my code:

```rust
app.handle().plugin(
    Builder::new()
        .with_handler(move |app, shortcut, _event| {
            println!("shortcut: {:?}", shortcut);
            if shortcut == &alt_space {
                let window = app.get_webview_window("main").unwrap();
                window.center().unwrap();
                window.show().unwrap();
                window.set_focus().unwrap();
            }
        })
        .with_shortcut(alt_space)?
        .build(),
)?;
```

It seems like the handler is designed to be called twice in this section of code from the repository [here](https://github.com/tauri-apps/plugins-workspace/blob/d4a54157f03446b1e118bf1ce80d761d76f8163d/plugins/global-shortcut/src/lib.rs#L419-L426):

```rust
if let Some(shortcut) = shortcuts_.lock().unwrap().get(&e.id) {
    if let Some(handler) = &shortcut.handler {
        handler(&app_handle, &shortcut.shortcut, e);
    }
    if let Some(handler) = &handler {
        handler(&app_handle, &shortcut.shortcut, e);
    }
}
```

Is this behavior expected? If so, what should I do to ensure the handler is only called once?

**Comment by FabianLars** [comment]
I don't think it's the repo code you shared here but instead the issue _should_ be that you're not checking the `_event` type since the handler will be called for keydown (pressed) and keyup (released) events.

**Comment by jason89521** [comment]
Oh sorry, I didn't check it. May I add some usage examples to the document to make this API clearer?

**Comment by FabianLars** [comment]
sure!
