### ISSUE TITLE
Deep link "listen" does not trigger in the rust executable

### ISSUE THREAD

**Issue by inzanez** [tauri-apps/plugins-workspace#1762]
Hi

I am currently testing deep link integration and listening for the event in the JS part works perfectly:

 ```
   await onOpenUrl((urls) => {
      console.log('deep link:', urls);
    });
```
However, I do not get any output when executing the listener in Rust:
```
...
        .setup(|app| {
            #[cfg(target_os = "linux")]
            {
                use tauri_plugin_deep_link::DeepLinkExt;
                app.deep_link().register_all()?;
            }
            app.listen("deep-link://new-url", |url| {
                dbg!(url);
                std::fs::write("/tmp/deep.txt", "test").expect("Failed to write");
            });
...
```

Not that I require it in Rust, I think I will require the JS side anyway, but either I am doing something wrong or it might be bug.

**Comment by FabianLars** [comment]
Hmm, as far as i can see from the code it should generally work. That said the rust code will not work if the app was started by the deep link - onOpenUrl call getCurrent internally first - could that be the issue?

**Comment by inzanez** [comment]
@FabianLars Oh, yeah,...right. That will be the issue then. I was under the impression that currently every deep-link will launch a new instance on the desktop anyway, so I will mainly want to catch the initial deep-link when launching the app.

**Comment by FabianLars** [comment]
Yep, if you don't use the single-instance plugin this is indeed the case, there's just not really a way to wait inside the plugin before the initial url is emitted hence the need for `std::env::args()` and/or `get_current()`.

**Comment by inzanez** [comment]
Wow, great, thanks for the clarification!
