### ISSUE TITLE
[deep-link][v2] Custom URL scheme not working on Windows 11

### ISSUE THREAD

**Issue by Reptarsrage** [tauri-apps/plugins-workspace#1765]
Repo: https://github.com/Reptarsrage/tauri-deep-link-repro

OS Name	Microsoft Windows 11 Pro
Version	10.0.22621 Build 22621

Upon attempting to redirect to the configured redirect_uri `my-tauri-app://reddit-oauth` browser responds with :
```
authorize:1 Failed to launch 'my-tauri-app://reddit-oauth?state=somestate&code=<code>' because the scheme does not have a registered handler.
```

Any help here would be great, thanks!

**Comment by FabianLars** [comment]
Did you test this only in `tauri dev`? If you don't register the schemes in your code (which arguably you shouldn't other than for AppImages on Linux) then you need to install the app to make it register the schemes.

**Comment by Reptarsrage** [comment]
nice! that was the piece i was missing. Does it mention this in the docs? If not, it should be added. As a developer, I was expecting this plugin to work in dev mode.  Thanks again for your help!!
