### ISSUE TITLE
[bug][window-state][WSL] Wayland protocol error 71 when restoring maximized window state

### ISSUE THREAD

**Issue by Zamoca42** [tauri-apps/plugins-workspace#1779]
## Describe the bug

I'm encountering a Wayland protocol error when restoring a maximized window state using tauri-plugin-window-state plugin on WSL. This issue is based on https://github.com/gitbutlerapp/gitbutler/pull/4864 and the [xdg-shell.xml](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/blob/main/stable/xdg-shell/xdg-shell.xml) specification.

According to the xdg-shell.xml specification:

```xml
<request name="set_window_geometry">
  <description summary="set the new window geometry">
    The window geometry of a window is its "visible bounds" from the user's perspective. It includes title bars and borders if they are drawn by the client, but excludes drop shadows. The geometry is double-buffered, and will be applied at the time wl_surface.commit of the corresponding wl_surface is called.

    **A client cannot set the window geometry of a maximized or fullscreen window, as the window dimensions are determined by the compositor.**

    When applied, the effective window geometry will be the rectangular region of the visible area of the window.
  </description>
  <!-- ... -->
</request>
```

In the Wayland protocol, the compositor determines the size of a maximized window, and the client must adhere to this size. If a client attempts to change the size of a maximized window, it is considered a protocol violation, resulting in an error. Therefore, `window-state` plugin should be modified to avoid setting the size for maximized windows.

## Suggestion

Modify `update_state` and `restore_state` functions to set the size and position only when the window is not maximized.

```rust
if !state.maximized {
    if flags.contains(StateFlags::SIZE) {
        self.set_size(PhysicalSize {
            width: state.width,
            height: state.height,
        })?;
    }

    if flags.contains(StateFlags::POSITION) {
        let position = PhysicalPosition {
            x: state.x,
            y: state.y,
        };
        self.set_position(position)?;
    }
}
```

If this suggestion is acceptable, I would be happy to submit a pull request implementing these changes.

**Comment by Legend-Master** [comment]
The size and position are set for restoring the size after exiting maximized state so I don't think it's a good idea to simply not to do it for maximized windows

I think if setting the size of a maximized window is causing problems, we probably should add a fix in [tao](https://github.com/tauri-apps/tao) (upstream windowing library used by tauri) instead of here

**Comment by Zamoca42** [comment]
You're right! Thanks for your response. I will attempt to move the issue and try to modify the Linux-related window state in tao.
