### ISSUE TITLE
[upload] Add transfer_speed for downloading and uploading files

### ISSUE THREAD

**Issue by VirtualPirate** [tauri-apps/plugins-workspace#1784]
## Feature Description

Send an extra filed in the event payload, this field will be called something like `progress_speed`. Will be used by the frontend to show the download or upload speed of a file.

### Problem
I was creating a downloader using the tauri-plugin-upload . I want an extra field in the event payload. Which will report the download speed of the file. This field will be updated every second.

Now, why I want this has a strong reason.

I accumulated the progress and run `setInterval(() => {}, 1000)` to derive the per second download speed of the file. But, I noticed that . Javascript doesn't actually run the `setInterval()` in every second consistently. Which caused the download speed to show not in a very timely manner.

### Solution:
My technical solution was:

I cloned the plugin workspace.
Created Mutex Variables And Threads.
This thread will run every second.
Updates the progress_speed every second.
This progress speed will be sent alongside the event payload

### Additional context
I've already worked on this solution in my local machine, and it's working fine. I just wanted to ask if this feature would be accepted by the community for the tauri-plugin-upload . Or else I'd have to create a fork of this plugin with that extra added feature ..

**Comment by FabianLars** [comment]
> I accumulated the progress and run setInterval(() => {}, 1000) to derive the per second download speed of the file. But, I noticed that . Javascript doesn't actually run the setInterval() in every second consistently. Which caused the download speed to show not in a very timely manner.

What i saw people do in their web apps (outside of tauri) is to use `performance.now()` instead which should be accurate enough for this. I can't remember the calculations etc they did though, too long ago.

----

I personally would like to not add it to the plugin but i assume many devs will appreciate this. So, PRs are appreciated to get this started :)
