### ISSUE TITLE
[stronghold] High CPU Usage on Linux

### ISSUE THREAD

**Issue by pwltr** [tauri-apps/plugins-workspace#18]
Hi, I'm seeing 100% CPU Usage on one core at all times when running the svelte example app on my system.
Was able to pin it down to this function:

https://github.com/tauri-apps/tauri-plugin-stronghold/blob/ef36411f4a869455b9249f3150bc309edec5ec58/src/stronghold.rs#L206-L262

Happens in dev & prodution build.

My System:
OS: Manjaro 21.2.4 Qonos
Kernel: x86_64 Linux 5.16.11-2-MANJARO
CPU: Intel Core i7-8700 @ 12x 4.6GHz

**Comment by nothingismagick** [comment]
can you please share your `tauri info` results?

**Comment by pwltr** [comment]
```
$ tauri info

Operating System - Manjaro, version 21.2.4 X64

Node.js environment
  Node.js - 16.13.2
  @tauri-apps/cli - 1.0.0-rc.5
  @tauri-apps/api - 1.0.0-rc.1

Global packages
  npm - 8.1.2
  pnpm - Not installed
  yarn - 1.22.17

Rust environment
  rustup - 1.24.3
  rustc - 1.58.0
  cargo - 1.58.0
  toolchain - stable-x86_64-unknown-linux-gnu 

App directory structure
/src
/.vscode
/node_modules
/src-tauri
/public

App
  tauri - 1.0.0-rc.3
  tauri-build - 1.0.0-rc.3
  tao - 0.6.3
  wry - 0.13.3
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  distDir - ../public
  devPath - http://localhost:5000/
  framework - Svelte
  bundler - Rollup
Done in 9.83s.
```

**Comment by nothingismagick** [comment]
Maybe not the cause, but I do see that your rust is outdated (1.58.1 is an important patch...) but you should use 1.59

`rustup update`

**Comment by pwltr** [comment]
Good to know, I updated rust and node to latest versions, but am not seeing improvement.

I'm using this plugin in my app which is built with this GitHub Action: https://github.com/pwltr/tauthy/blob/master/.github/workflows/release.yml

So tooling should be up-to-date there I believe? Thought it was just a development build issue but am seeing fans spin up on the prod bundle as well.

**Comment by lucasfernog** [comment]
Thanks for finding the issue. I think we need a redesign of the plugin, we can do better.

**Comment by pwltr** [comment]
No worries, thanks for doing this. I would love to help but am not there yet with the Rust...

**Comment by pwltr** [comment]
I think it's actually an easy fix, see PR. I tested it and it works fine.
