### ISSUE TITLE
[single-instance] This plugin is not searchable on crates.io

### ISSUE THREAD

**Issue by wkl007** [tauri-apps/plugins-workspace#180]
When will it be released to crates.io? https://crates.io/search?q=tauri-plugin-single-instance

The project can only be referenced in this way:
``` toml
tauri-plugin-single-instance = { git = "https://github.com/tauri-apps/tauri-plugin-single-instance" }
```

**Comment by FabianLars** [comment]
i think it will still take a while. We are not sure yet how we want to release the plugins (audit etc). In this particular case we also need to figure out what to do with macos first :/

**Comment by huangjj27** [comment]
Is it a good idea to make a `v0.0.1` version that works on window and Linux first?
