### ISSUE TITLE
[fs][bug][v2] The stat method path parameter contains an error message in Chinese

### ISSUE THREAD

**Issue by DWHengr** [tauri-apps/plugins-workspace#1803]
![image](https://github.com/user-attachments/assets/f89b7334-37e1-4655-9038-3524146245df)
In the `stat` method, the path parameter contains Chinese. Obtaining file information, an error is reported.

**Comment by FabianLars** [comment]
Thanks for the report! Could you also include the output of the `tauri info` command please?

**Comment by DWHengr** [comment]
[✔] Environment
    - OS: Windows 10.0.22631 x86_64 (X64)
    ✔ WebView2: 126.0.2592.113
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.78.0 (9b00956e5 2024-04-29)
    ✔ cargo: 1.78.0 (54d8815d0 2024-03-26)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.12.2
    - yarn: 1.22.22
    - npm: 10.5.0

[-] Packages
    - tauri 🦀: 2.0.0-rc.8
    - tauri-build 🦀: 2.0.0-rc.7
    - wry 🦀: 0.42.0
    - tao 🦀: 0.29.1
    - @tauri-apps/api : 2.0.0-rc.4
    - @tauri-apps/cli : 2.0.0-rc.10

[-] Plugins
    - tauri-plugin-autostart 🦀: 2.0.0-rc.1
    - @tauri-apps/plugin-autostart : 2.0.0-rc.1
    - tauri-plugin-global-shortcut 🦀: 2.0.0-rc.2
    - @tauri-apps/plugin-global-shortcut : 2.0.0-rc.1
    - tauri-plugin-websocket 🦀: 2.0.0-rc.1
    - @tauri-apps/plugin-websocket : 2.0.0-rc.1
    - tauri-plugin-process 🦀: 2.0.0-rc.1
    - @tauri-apps/plugin-process : 2.0.0-rc.1
    - tauri-plugin-dialog 🦀: 2.0.0-rc.3
    - @tauri-apps/plugin-dialog : 2.0.0-rc.1
    - tauri-plugin-fs 🦀: 2.0.0-rc.1
    - @tauri-apps/plugin-fs : 2.0.0-rc.2
    - tauri-plugin-upload 🦀: 2.0.0-rc.1
    - @tauri-apps/plugin-upload : 2.0.0-rc.1
    - tauri-plugin-shell 🦀: 2.0.0-rc.3
    - @tauri-apps/plugin-shell : 2.0.0-rc.1
    - tauri-plugin-updater 🦀: 2.0.0-rc.2
    - @tauri-apps/plugin-updater : 2.0.0-rc.1 (outdated, latest: 2.0.0-rc.2)
    - tauri-plugin-http 🦀: 2.0.0-rc.1
    - @tauri-apps/plugin-http : 2.0.0-rc.2

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite

**Comment by FabianLars** [comment]
Can you try upgrading `tauri-plugin-fs` in cargo.toml to 2.0.0-rc.5 ? In rc.3 there were potentially relevant changes there.

**Comment by DWHengr** [comment]
Great, it has been resolved after the upgrade.
