### ISSUE TITLE
About app sharing 

### ISSUE THREAD

**Issue by lindongchen** [tauri-apps/plugins-workspace#1808]
When an application is launched on the store, especially on mobile app, it should have certain promotion capabilities, not limited to sharing content, files to other apps/files/airdrops, etc. Does Tauri2 have a plugins or plans about this, I think sharing is the bridge to connect the marketplace

**Comment by tweidinger** [comment]
Hey, I think an issue here is not the right place to discuss. Please move these kind of questions to the Github Discussions.
Also this is the plugin repository and not Tauri itself.
There is a share plugin from a community member https://github.com/buildyourwebapp/tauri-plugin-sharesheet for starters.
