### ISSUE TITLE
[single-instance] disfunction when package.productName is longer than 15 bytes

### ISSUE THREAD

**Issue by huangjj27** [tauri-apps/plugins-workspace#181]
Here is how I did the experiment:
1. a minimal example from [emit-event](https://github.com/amrbashir/tauri-plugin-single-instance/tree/master/examples/emit-event)
2. just change the `package.productName` in the `tauri.conf.json` to `z12345678901234`, the function works well
3. but if the `package.productName`  to  `z123456789012345`, the example begins to open multi-window for me.

**Comment by amrbashir** [comment]
Which OS?

**Comment by amrbashir** [comment]
I reproduced the bug on Windows and pushed a fix. Thanks for the report and if this issue happens on Linux too, let me know.

**Comment by huangjj27** [comment]
> Which OS? 

I encountered this bug on Windows，and not sure if it occurs on Linux

**Comment by huangjj27** [comment]
I try [another fix](https://github.com/huangjj27/tauri-plugin-single-instance/commit/6fd3c8c2c518eb5eaa1101eb14a65603ca5e621e) inspired by [the LPCWSTR document](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-dtyp/76f10dd8-699d-45e6-a53c-5aefc586da20): 

> An LPCWSTR is a 32-bit pointer to a constant string of 16-bit [Unicode characters](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-dtyp/a66edeb1-52a0-4d64-a93b-2f5c833d7d92#gt_fd33af2e-e1ce-4f8e-a706-f9fb8123f9b0), which **MAY be null-terminated.**

As @PotatoTooLarge said, "In Win32 API, strings are always null-terminated, except specific indicated“.

**Comment by amrbashir** [comment]
the `encode_wide` funcrion adds the null terminator.

**Comment by huangjj27** [comment]
> the encode_wide funcrion adds the null terminator.

then it's weird that the function fixed after I had added the `\0` manually

**Comment by FabianLars** [comment]
encode_wide doesn't add the null terminator if i understand this correctly: https://doc.rust-lang.org/std/os/windows/ffi/trait.OsStrExt.html#tymethod.encode_wide

**Comment by amrbashir** [comment]
I meant the `util::encode_wide` function.

> then it's weird that the function fixed after I had added the \0 manually

Yeah that's weird indeed, `util::encode_wide` implementation is taken from rust docs. see https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.chain

**Comment by Berrysoft** [comment]
I've found that it was because of the dangling pointer... and fixed in tauri-apps/tauri-plugin-single-instance#6.

**Comment by amrbashir** [comment]
Thank you
