### ISSUE TITLE
[single-instance] Not working on windows

### ISSUE THREAD

**Issue by dungeon2567** [tauri-apps/plugins-workspace#182]
This plugin is not working on windows. I can still open multiple instances of tauri app

**Comment by amrbashir** [comment]
Haven't touched the project in a while but I just tried it and it worked just fine. can you provide a steps to reproduce or better a minimal repro?

**Comment by dungeon2567** [comment]
![image](https://user-images.githubusercontent.com/31074903/177428224-5fa2d5c3-610d-49c0-ace9-0d0a31862c4f.png)
This is my main.rs, maybe it does not work with tray or menu?

**Comment by amrbashir** [comment]
I don't think so. So please try to provide a minimal repo and I will investigate it further.

**Comment by dungeon2567** [comment]
The problem was on my code inside init, "app.get_window("main").unwrap().show().unwrap()"
It was throwing an exception or something like this.
