### ISSUE TITLE
global-shortcut报错

### ISSUE THREAD

**Issue by Sunrisies** [tauri-apps/plugins-workspace#1840]
在开发的过程中遇到了一个问题
![image](https://github.com/user-attachments/assets/05000218-47dd-4fc0-8aa2-f959a7dcbe6a)
刷新当前页面之后，在使用快捷键就会报上面这个错误，是我这边没有正确使用还是什么？

这个是我的代码 
![image](https://github.com/user-attachments/assets/1677488e-afb9-425e-81e6-5a51b80a0da7)

**Comment by FabianLars** [comment]
This is more or less a shortcoming of tauri's event/channel system. If you reload a page all registered JS functions will be cleared by the webview but tauri's backend won't notice that.

For a reload save implementation you either need to register the shortcuts in Rust or call unregisterAll() on page load before registering new ones.

**Comment by Sunrisies** [comment]
> This is more or less a shortcoming of tauri's event/channel system. If you reload a page all registered JS functions will be cleared by the webview but tauri's backend won't notice that.这或多或少是 tauri 的事件 / 频道系统的一个缺点。如果你重新加载一个页面，所有注册的 JS 函数都会被 webview 清除，但 tauri 的后端不会注意到这一点。
> 
> For a reload save implementation you either need to register the shortcuts in Rust or call unregisterAll() on page load before registering new ones.对于重新加载保存实现，您需要在 Rust 中注册快捷方式，或者在注册新快捷方式之前在页面加载时调用 unregisterAll（）。

好的，我已经通过查看插件的api解决了，谢谢
