### ISSUE TITLE
[sql] Unable to import plugin from JS frontend

### ISSUE THREAD

**Issue by Blatman** [tauri-apps/plugins-workspace#185]
Trying to get the plugin going but the showstopper is the import.

I use -
	      import Database from 'tauri-plugin-sql-api' as per the readme but of course this fails with 

TypeError: Module specifier, 'tauri-plugin-sql-api' does not start with "/", "./", or "../". Referenced from tauri://localhost/js/app.js

I sort of expected this because imports of the Tauri api fail in the same way but there is an alternative method which works well -

eg:     `var dialog = window.__TAURI__.dialog;`
        //  import { confirm } from '@tauri-apps/api/dialog';

So is there a similar alternative available for the plugin?

**Comment by FabianLars** [comment]
You could download this file https://github.com/tauri-apps/tauri-plugin-sql/blob/dev/webview-dist/index.min.js and use it locally.

**Comment by Blatman** [comment]
Thanks for that but still at sea as to how to use it - tried window.__TAURI_IPC__.t but no good.

**Comment by FabianLars** [comment]
I think you need to import the file with an import statement like this
```js
import Database from './sql.min.js'; //Or whatever you named the file.

const db = await Database.load("sqlite:mydb.db");
```


Alternatively you could also use this file instead https://github.com/tauri-apps/tauri-plugin-sql/blob/dev/webview-dist/index.mjs and replace the import at the top with `const invoke = window.__TAURI__.invoke;`

Edit: Change `new Database` to `Database.load`

**Comment by Blatman** [comment]
OK thanks - finally got the import to work and the db object is created but not sure where the db file is - can't find it anywhere - will have a go at using sqlite on the client side with sql.js I think.

**Comment by FabianLars** [comment]
> can't find it anywhere

it's in the path you can get via the [appDir() function](https://tauri.app/v1/api/js/path#appdir). For example on Windows this resolves to `AppData/Roaming/bundle-identifier/mydb.db` (see the configDir doc for linux and macos paths)

**Comment by Blatman** [comment]
Yup that's what I thought, my appDir shows as -
"/Users/USER/Library/Application Support/uk.org.wanderinghippo.winman.dev/" however the uk.org.wanderinghippo.winman.dev folder doesn't exist which is strange. If I manually create it the db file will still not appear so I think it is time to retrace my steps back to create-tauri-app ....

**Comment by FabianLars** [comment]
The database won't be created until it's actually loaded, which also means that i made bad decisions in my example code above, so instead of `new Database(path)` you'd use `Database.load(path)` - sorry about that if this was the issue.

**Comment by Blatman** [comment]
Mmmm - I think your initial angle was OK - my results are -

`    import Database from './sql.mjs';  //  (using var invoke = window.__TAURI__.invoke; at top of file) -

    //  import Database from './sql.min.js'  // also works

//	    const db = new Database.load("sqlite:hippo.db");  // TypeError: function is not a constructor (evaluating 'new Database.load("sqlite:hippo.db")')
//	    const db = Database.load("sqlite:hippo.db");  // Unhandled Promise Rejection: plugin sql not found
//	    const db = Database("sqlite:hippo.db");  // TypeError: Cannot call a class constructor without |new|
    const db = new Database("sqlite:hippo.db");  // works OK
console.log('DB', db);


    const getto = Database.get("sqlite:hippo.db");  // works OK
console.log('GETTO', getto);
`
<img width="557" alt="goodresult" src="https://user-images.githubusercontent.com/11089335/196628249-526da6fb-b253-4170-b7c0-488b7672db11.png">

As far as the import goes I think it works OK now but the new rabbit hole for me is the fact that the app Dir folder doesn't exist even though the path reports it OK. I have tried with default tauri-app and it also does not produce an appDir folder as expected (should be com.tauri.dev folder as set in config identifier). Strange that if the folder doesn't exist that the db creation doesn't error somehow. Maybe it is up to the dev to manually create the appDir folder although I expected that the Tauri app would have just done that particularly as the path reports it as such.

**Comment by FabianLars** [comment]
> // Unhandled Promise Rejection: plugin sql not found

This is the most (or only) relevant error message here. It means that the JS code was correct but you're missing the Rust part of the plugin, see: https://github.com/tauri-apps/tauri-plugin-sql#rust

> Maybe it is up to the dev to manually create the appDir folder although I expected that the Tauri app would have just done that particularly as the path reports it as such.

It's indeed up to the dev or in this case the plugin to create the dir. None of the paths from the path module necessarily exist, thanks to Linux you can't even expect Desktop, Document, etc to exist... The main reason in my eyes why Tauri shouldn't create the appDir automatically is pretty simple: Imagine a user installs 20 diffferent Tauri apps, they'd probably end up with 19 completely empty dirs 🤷

**Comment by Blatman** [comment]
OK - thanks very much for your help, got it working now - I had thought the Rust example and the Webview example on the readme were either(I did the webview) rather than both required. The create dir worked fine from the JS and the Rust in the main.js is good so now hippo.db exists where it should.
