### ISSUE TITLE
[sql] Plugin should close the database connection on exit

### ISSUE THREAD

**Issue by alllex** [tauri-apps/plugins-workspace#186]
Currently there is no way of cleanly closing the database connection when the user quits the app. Most databases are resilient to this, but such a behavior can lead to pollution of disk with temporary database files.

SQLite in particular when running in the WAL-mode would maintain additional `my.db-wal` and `my.db-shm` files which are normally deleted, when the database connection is closed. However, in the case of Tauri SQL integration the files remain on disk most likely due to the connection not being closed properly.

It's unclear whether there is a reasonable explanation why the database connection should NOT be cleanly closed when the application exits. If there is, then the connection closing functionality could be disabled by a flag. However, I would simply make the closing careful, in a sense that it does nothing if it's already closed.

This is related to https://github.com/tauri-apps/plugins-workspace/issues/200. If the referenced issue is solved, then at least plugin users would have an option to implement closing-on-exit by themselves.

**Comment by yankeeinlondon** [comment]
@alllex take a look at the PR i just merged and see if this fixes things for you ... it introduces `close(db: Option<String>)` to the API surface which allows closing one or all connections pools manually.

**Comment by yankeeinlondon** [comment]
note it's only in "dev" branch currently not "release" and it's a manual call not automatic; just noticed that you had created an automated way to close as well and I'll see if I can get this worked into my next one where I'm looking at improving and simplifying some of the deserialization logic

**Comment by alllex** [comment]
@yankeeinlondon I think this should work too! It also covers the use-case when one needs to close and open different database while the app is running, which is great.

I would be amazing to do a release including these changes (and tauri-apps/tauri-plugin-sql#156 too), to make it easier for people to depend on the plugin. I know you can specify a commit in dependencies, but it would be much easier to have a reference point, even if it's a `0.0.1` or similar.

Just for posterity, these are the changes that add the `close` command, as it's a bit involved to find it: https://github.com/tauri-apps/tauri-plugin-sql/commit/42a9ecd38b797024772b37612806b53d747444e5#diff-9b59ee4899ad0a5d008889ea89a124a7291316532e42f9f3d6ae842b906fb095
