### ISSUE TITLE
[request][updater][v2] beta updates

### ISSUE THREAD

**Issue by thewh1teagle** [tauri-apps/plugins-workspace#1871]
I'm using the updater plugin in the app [vibe](https://github.com/thewh1teagle/vibe) and host the binaries / update artifacts with tauri action on that public repository.
I would like to provide a way in the app to get beta updates. meaning that updater plugin will look for beta public release in Github and not only for the latest release. is that possible?
Thanks

**Comment by amrbashir** [comment]
Check this discussion https://github.com/tauri-apps/tauri/discussions/11069#discussioncomment-10699077

**Comment by thewh1teagle** [comment]
I don't use custom server for hosting. Just Github releases. 
Any chance I can do it with Github releases and actions and keep it simple as now?

**Comment by amrbashir** [comment]
yes, multiple json files and when your user changes from stable to beta or vice versa, you just point them to one of your update json files
