### ISSUE TITLE
[deep-link][v2] onOpenUrl Listener is being triggered when mounting even if the even was already processed

### ISSUE THREAD

**Issue by nicolaspapp** [tauri-apps/plugins-workspace#1879]
Hey there, I am trying to setup the `onOpenUrl` listener on my Tauri app, which is using React and React Router on the FE.

I have setup a single hook to hear on the frontend for the deep links event and generate a redirect based on the information. 
What I see is that when the redirect is triggered, a new listener will be mounted and I will get the deep link event again. 

I have already checked that the issue is not the double mounting React does on dev builds.

Is this a bug? Or I am missing something? 

Including a small snippet of the hook:

```
import { onOpenUrl } from "@tauri-apps/plugin-deep-link";
import { useEffect, useRef } from "react";
import { useNavigate } from "react-router-dom";

export const UseDeepLinkUrl = () => {
  const navigate = useNavigate();
  const isListenerRegistered = useRef(false);

  useEffect(() => {
    if (isListenerRegistered.current) {
      return;
    }

    const unlisten = onOpenUrl((url: string[]) => {
      console.log("url", url);
      const path: string = url[0].split("://")[1];
      console.log("Setting link to:", path);
      navigate(path);
    });
    isListenerRegistered.current = true;

    return () => {
      unlisten.then((f) => {
        console.log("unlisten", f);
        isListenerRegistered.current = false;
        return f();
      });
    };
  }, []);

  return null;
};
export default UseDeepLinkUrl;

```

**Comment by nicolaspapp** [comment]
Taking a glance at the code and now I understand why this is happening:

```
export async function onOpenUrl(
  handler: (urls: string[]) => void
): Promise<UnlistenFn> {
  const current = await getCurrent()
  if (current) {
    handler(current)
  }

  return await listen<string[]>('deep-link://new-url', (event) => {
    handler(event.payload)
  })
}
```

I understand that the `getCurrent()` may be be useful if the deep link is used to start new instances, but if you are using a single instance and navigation then this causes issues. For me just using the listen event without the `getCurrent` call did the trick for me

**Comment by lempira** [comment]
I think I am running into the same thing you were. When you say that you got rid of the `getCurrent`, was it something like this? It tried this but the `onOpenUrl_` doesn't seem to be firing.

```
export async function onOpenUrl_(handler: (urls: string[]) => void): Promise<UnlistenFn> {
  return await listen<string[]>('deep-link://new-url', (event) => {
    handler(event.payload)
  })
}
```

**Comment by nicolaspapp** [comment]
@lempira what I meant was that I just avoided using the `onOpenUrl` interface and did the following instead:

```
import { listen } from '@tauri-apps/api/event';

const unlisten = listen<string[]>('deep-link://new-url', (event) => {
            const url = event.payload;
            console.log('url', url);
        });
```

**Comment by lempira** [comment]
Thanks @nicolaspapp. I tried using just the listen and it doesn't seem to be working. [Here is the implementation](https://github.com/algorandfoundation/algokit-lora/blob/8b1115423d922d9370ec9957aef52e30da59fbbe/src/features/deep-link/hooks/use-deep-link.tsx#L25). It's essentially the same thing but with some logic around the redirect and some temporary logging. The code is getting to the useffect but not to the deeplink callback. You'll also see the `onOpenUrl` in there but commented out. That works, but with the remounting issue you described. I don't see why it's not working with the listen alone. Did you have to change anything to the lib.rs file to emit something?

**Comment by tubbo** [comment]
Haven't tested this, but tried to wrap this functionality in a hook that i could just call from my layout component:

```typescript
import { useState, useEffect } from "react";
import { onOpenUrl } from "@tauri-apps/plugin-deep-link";

function useDeepLink() {
  const [unlisten, setUnlisten] = useState<() => void>();
  const [urls, setUrls] = useState<string[]>([]);

  useEffect(() => {
    if (!unlisten) {
      onOpenUrl(setUrls).then(setUnlisten).catch(console.error);
    }

    return unlisten;
  }, [unlisten]);

  return urls;
}
```

If the type definitions are correct, I think this should remove the event listener whenever the component is unmounted.

But I think this is part of a larger issue with Tauri's APIs....many of these are implemented using promises, which are kinda hard to deal with in React components due to the way it handles state management/propagation. I understand that the APIs probably need a promise in order to do what they can do, but it seems kinda weird that we'd all have to implement hooks on our own _just_ to use Tauri with React.

I guess you could genericize the above hook into something that just calls `listen()` directly...

```javascript
function useTauriEvent(name, handler, onError = (error) => console.error(error)) {
  const [unlisten, setUnlisten] = useState();
  const [value, setValue] = useState();

  useEffect(() => {
    if (!unlisten) {
      listen(handler).then(setUnlisten).catch(onError);
    }

    return unlisten;
  }, [unlisten]);

  return value;
}
```

...but I'm just not sure if this is the best approach going forward.

**Comment by FabianLars** [comment]
Yeah, no way around Promises in the apis as the IPC (the bridge to the rust side) is async itself.

That said, when we're talking about events we have to compare them to native browser events as well imo. If you ask me, Tauri's events are easier but at least equivalent:
```ts
// assuming we're in a normal component and want to register on mount
// because o never really went for custom hooks

const nativeHandler = (event) => {};

useEffect(() => {
  const unlisten = onOpenUrl(handler);

  document.addEventListener('someevent', nativeHandler);

  return () => {
    unlisten.then(f => f());
    document.removeEventListener('someevent', nativeHandler);
  };
}, [])
```
So keeping in mind that you actually don't need to care about the Promise until you want to unlisten to the event i don't think it's right to blame the use of Promises in this context. Of course, take that with a grain of salt, i'm not used to custom hooks so that may indeed be the deciding factor i'm missing here :)

**Comment by nicolaspapp** [comment]
Just for refrence, this is the hook I am using and seems to work well on my particular case
```
import { listen } from '@tauri-apps/api/event';
import { useEffect } from 'react';
import { useNavigate } from 'react-router-dom';

export const UseDeepLinkUrl = () => {
    const navigate = useNavigate();

    useEffect(() => {
        const unlisten = listen<string[]>('deep-link://new-url', (event) => {
            const url = event.payload;
            const path: string = url[0].split('://')[1];
            navigate(path);
        });

        return () => {
            unlisten.then((f) => {
                console.log('unlisten', f);
                return f();
            });
        };
    }, []);

    return null;
};
export default UseDeepLinkUrl;
```

**Comment by lempira** [comment]
I tried using the listen directly and the new onOpenUrl from @FabianLars PR. They both work, but only when the app is already open. If the app is not open, the deeplink callback does not fire. Do I have to do something explicit to catch the case the app is not open?

I should have written this earlier, but for reference, here are the steps I am taking to test.
Env:
 - Apple silicon, MacOS Sequoia v 15.0.1
 - rustc 1.81.0 (eeb90cda1 2024-09-04)
 - cargo 1.81.0 (2dbb1af80 2024-08-20)
 - node v22.9.0
 - "@tauri-apps/api": "2.0.3"
 - "@tauri-apps/plugin-cli": "2.0.0",
 - "@tauri-apps/plugin-deep-link": "2.0.0",
 - "@tauri-apps/plugin-shell": "2.0.1"
Steps:
1. Making changes in code
2. Running `npm run tauri build` 
3. Installing the dmg but moving  app to Applications folder
4. Testing deep link by either using `open <scheme://path-to-deep-link>` or just scheme://path-to-deep-link in a browser

**Comment by FabianLars** [comment]
well, that's what getCurrent was for. Now you have to call it yourself on app start. The event won't wait for your frontend to register the listener.

**Comment by lempira** [comment]
Ok, I ended up doing something like this. Getting the `getCurrent` to run only the first time while registering the listener was a challenge since the navigate unmounts the component. This implementation is working for me. 

```
function useDeepLink() {
  const navigate = useNavigate()
  const [currentUrl, setCurrentUrl] = useState<string | null>(null)

  const onDeepLink = useCallback(
    (urls: string[]) => {
      const url = urls[0]
     // url-processing-logic here
      const newUrl = <results-from-url-processing-logic>
      setCurrentUrl(newUrl)
      navigate(newUrl)
    },
    [navigate]
  )

  useEffect(() => {
   // Only run if you're in TAURI
    if (!window.__TAURI_INTERNALS__) return
    // If currentUrl is empty then the app has just been opened. 
    if (!currentUrl) {
      getCurrent().then((current) => {
        if (current) {
          onDeepLink(current)
        }
      })
    }
    // register listener
    const unlisten = onOpenUrl((urls) => {
      onDeepLink(urls)
    })
    
    // clean up listener
    return () => {
      unlisten.then((f) => f())
    }
  }, [currentUrl, onDeepLink])
}
```
