### ISSUE TITLE
[sql] SQLite binary [Question]

### ISSUE THREAD

**Issue by Blatman** [tauri-apps/plugins-workspace#188]
Looking to try out the plugin but not sure if it assumes that SQLite is already installed on OS.

In my case I'm using MacOS and I usually just use the portable binary download from sqlite.org (SQLite-Tools-OSX) which doesn't require a hard OS install - is it possible that the plugin can somehow be pointed to the portable sqlite3 executable binary which is not located with the system folders of the OS? 

Looking at the source files all of the sqlite path references appear to relate to the location of the .db file not the sqlite3 binary.

I see the desktop app as being able to include the sqlite binary rather than depending on the host computer having SQLite installed.

If it needs it to be installed I will probably have to try the SQL.js (WASM) route on the client side (the databases I require are not generally large).

**Comment by FabianLars** [comment]
You don't need to install sqlite at all for this plugin, The sql crates we use bundle the latest available version inside the binary. (`libsqlite3-sys` via `sqlx` - using the `bundled` feature)
