### ISSUE TITLE
[autostart] The application break on windows when autostart

### ISSUE THREAD

**Issue by jason89521** [tauri-apps/plugins-workspace#1883]
![image](https://github.com/user-attachments/assets/8687ee18-2d7f-4b25-9af4-9f6771678520)
![image](https://github.com/user-attachments/assets/b9056b6e-a061-4d2a-9743-d44e734f55e7)

As the above images show, when I restart my windows, the application breaks.

Here is the reproduce repo.  https://github.com/jason89521/auto-start-tauri

Did I miss something to let the autostart work correctly?

**Comment by Legend-Master** [comment]
The auto started app is the debug one which uses your localhost server, would you try again with a release build? (`npx tauri build` and launch it then restart your computer)

**Comment by jason89521** [comment]
Oh! Thank you!
