### ISSUE TITLE
[sql] lastInsertId return null after insert

### ISSUE THREAD

**Issue by fanesz** [tauri-apps/plugins-workspace#1893]
tauri v2, tauri-plugin-sql v2

```ts
async create(product: ProductCreate): Promise<number> {
  const query = `
    INSERT INTO products (sku, name, description, brand, price, cost, stock_quantity, stock_threshold, is_active)
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9::boolean)
    RETURNING product_id as id
  `;
  const res = await this.db.execute(query, [
    product.sku,
    product.name,
    product.description,
    product.brand,
    product.price,
    product.cost,
    product.stock_quantity,
    product.stock_threshold,
    product.is_active ?? true,
  ]);

  console.log(res);
  return res.lastInsertId;
}
```
Using postgresql,
`lastInsertId` always return null, according to [this document](https://v2.tauri.app/reference/javascript/sql/#properties-1), I did add RETURNING clause, but still return a null.

Created data:
![image](https://github.com/user-attachments/assets/81afa850-a6f0-4825-938f-b6d692127a5c)

Result log:
![image](https://github.com/user-attachments/assets/f2b9950f-6623-4773-8f0f-4f60c4f3ffe6)

**Comment by fanesz** [comment]
missread, suppose to be ~db.execute~ db.select

**Comment by FabianLars** [comment]
I'll reopen this for now since we should document this behavior at least.

Right now, the lastInsertId is based on sqlx' methods on the query result https://docs.rs/sqlx/latest/sqlx/?search=last_insert and there is none for postgres (couldnt find out why on first glance).

P.S. would you mind sharing your solution/workaround? It may be interesting for others.

**Comment by fanesz** [comment]
As documented [here](https://v2.tauri.app/reference/javascript/sql/#properties-1),
to get any return value from a query, you should use `db.select("INSERT INTO ...")` instead of `db.execute("INSERT INTO ...")`.

By using this approach, the return value becomes a normal select function, which returns an array of objects.

For example, if you specify `RETURNING product_id` at the end of the query, it will return `[ { "product_id": 1 } ]`. Similarly, if you specify `RETURNING *`, it will return the entire created data.

The conclusion that I get is that it’s not possible to get the `lastInsertId` when using PostgreSQL with the `db.execute` function, based on the documentation.

@FabianLars

**Comment by FabianLars** [comment]
Thanks! Didn't know we had this documented already 😅 that said, I changed it from 0 to null recently so the docs are still wrong.

Thanks again :)
