### ISSUE TITLE
[fs] forbidden path error when using fs plugin to watch changes

### ISSUE THREAD

**Issue by patelka2211** [tauri-apps/plugins-workspace#1894]
![](https://github.com/user-attachments/assets/03b22159-8f7a-443e-9c6c-30b91dace32d)

I'm currently implementing the FS plugin to monitor changes in a specified folder. I’ve added the "watch" feature for the FS plugin in Cargo.toml and included the capabilities `fs:allow-watch` and `fs:allow-unwatch`. However, I'm encountering a `forbidden path` error. How can I solve this?

**Comment by Legend-Master** [comment]
You need to add that path to the allow list

Use this to allow that path for `watch`

```json
{
  "identifier": "fs:allow-watch",
  "allow": [
    {
      "path": "your-path"
    }
  ]
}
```

or this to allow all fs operations to that path

```json
"fs:allow-watch",
{
  "identifier": "fs:scope",
  "allow": [
    {
      "path": "your-path"
    }
  ]
}
```

> https://tauri.app/plugin/file-system/#permissions

**Comment by patelka2211** [comment]
![](https://github.com/user-attachments/assets/91453cf4-9dd3-4996-8973-7f52e606a016)
Can you help me with this?

**Comment by Legend-Master** [comment]
There's a config if you need to do all paths and including dot files/folders on unix systems

Put this in your tauri config

```json
"plugins": {
  "fs": {
    "requireLiteralLeadingDot": false
  }
}
```

Or use `$DESKTOP/local-repo/.git/refs/heads/**` instead of `**` if this path is fixed and you only need to watch this path

**Comment by patelka2211** [comment]
🎉🥳 It worked! A huge thank you to @Legend-Master for the help!

For anyone looking for this setting in the future, here’s the link: [Tauri Configuration Reference - fsScope](https://tauri.app/reference/config/#fsscope).
