### ISSUE TITLE
[websocket] Why received type of Buffer Message when Client send JSON.stringtify(msg)  message to WebsocketServer ?

### ISSUE THREAD

**Issue by xtcel** [tauri-apps/plugins-workspace#19]
I use tauri-plugin-websocket send a message to websocket server like this:

```javascript
const loginInfo = { student_id: this.studentId };
const msg = {event: 'stu_login', data: loginInfo};
websocket.send(JSON.stringify(msg));
```
the websocket sever received message like this:
![image](https://user-images.githubusercontent.com/27468963/139516705-7418b166-a79c-4723-8c75-fa8b2cd41a91.png)

**Comment by FabianLars** [comment]
I am pretty sure that this is a server-side issue, especially since this was not reported by anyone else.

If you still face this problem (sorry for the delay btw) please add a reproduction example at least for the server side and i'll re-open this issue.
