### ISSUE TITLE
[bug] The store plugin reports an error according to the configuration of the official website, and the autoSave type is incorrect.

### ISSUE THREAD

**Issue by moom-en** [tauri-apps/plugins-workspace#1902]
### Describe the bug

![image](https://github.com/user-attachments/assets/bcd8d0ab-bc35-48fa-b16c-e2656e59ad5e)
![image](https://github.com/user-attachments/assets/1481ea1a-a3eb-437a-b6d0-6c6efd0ca598)
https://tauri.app/plugin/store
As shown in the picture, according to the configuration type of the official website, it should be boolean, but an error will be reported. If you fill in the u64 type, there will be no problem.

### Full `tauri info` output

```text
Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 129.0.2792.79
    ✔ MSVC:
        - Visual Studio Enterprise 2022
        - Visual Studio ���ɹ��� 2022
    ✔ rustc: 1.80.1 (3f5fd8dd4 2024-08-06)
    ✔ Cargo: 1.80.1 (376290515 2024-07-16)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)
    - node: 20.17.0
    - yarn: 1.22.19
    - npm: 10.8.2
```

**Comment by Legend-Master** [comment]
This will be tracked in #1865
