### ISSUE TITLE
[sql] Querying JSON from text cell

### ISSUE THREAD

**Issue by sc00** [tauri-apps/plugins-workspace#191]
Hi,

is it possible to query json objects stored in string format? For instance..

Row in users:
> id: 1
> name: 'John Doe'
> contact: '{"phone":"123456","email":"john@doe.com"}'

Expected result from db.select(sql):
```
[
  {
   id: 1,
   name: 'John Doe',
   contact: {
    phone: '123456',
    email: 'john@doe.com'
   }
 }
]
```

I tried using [json1](https://www.sqlite.org/json1.html) functions (like shown [here](https://gist.github.com/akehrer/481a38477dd0518ec0086ac66e38e0e2) or [here](https://stackoverflow.com/questions/33432421/sqlite-json1-example-for-json-extract-set) but haven't been successful.

For instance
```
"SELECT json_extract(contact, '$.email') FROM users"
```
returns
```
[ { json_extract(contact, '$.email'): null } ]
```
and
```
"SELECT json_group_object(id, name) AS json_result FROM (SELECT * FROM users)"
```
returns
```
[ { json_result: null } ]
```

Maybe I use the functions incorrectly, but according to the examples these queries should have a different output? I want to mention these were just tests I did. I didn't come as far as to writing a query that would actually return the desired result.

Thanks and cheers!

**Comment by FabianLars** [comment]
There currently is no explicit json support so you have to "get" is as normal text and use `JSON.parse()` on the javascript side.
