### ISSUE TITLE
[bug] Shell plugin freezes when invoking open function on non-exist local path

### ISSUE THREAD

**Issue by Steve-xmh** [tauri-apps/plugins-workspace#1913]
I'm currently using `tauri-plugin-shell (v2.0.1)`, every time I use `open` to open any path of directory that doesn't exists, it will freeze the whole window and can't response.

OS: Windows 11 23H2 (22631.4169)

Code Example:

```typescript
import { open } from "@tauri-apps/plugin-shell";

// Any local path that not actually exists here
open("C:/nothing");
```

**Comment by amrbashir** [comment]
Should be fixed by https://github.com/tauri-apps/plugins-workspace/pull/1881
