### ISSUE TITLE
[window-state][v2] Using a plugin causes the terminal to keep outputting

### ISSUE THREAD

**Issue by ayangweb** [tauri-apps/plugins-workspace#1916]
I am causing this problem simply by using the plugin!

```rs
.plugin(
    tauri_plugin_window_state::Builder::default()
        .with_state_flags(StateFlags::all() & !StateFlags::VISIBLE)
        .build(),
)
```

https://github.com/user-attachments/assets/848dc890-549e-409f-a09d-ed51ea1c2383

**Comment by amrbashir** [comment]
That's not related to window-state plugin, this is logs emitted from the underlying library `tao`, and I belive you're using `tauri-plugin-log` to collect and print log which collects all logs

**Comment by ayangweb** [comment]
However, when I use window-state it keeps outputting and causes the app to get stuck!

**Comment by amrbashir** [comment]
the logs are not from `window-state`, they are emitted from `tao` then collected and printed by `tauri-plugin-log`. 

The app getting stuck is another issue, please make a minimal repro and open another issue for it.

**Comment by ayangweb** [comment]
https://github.com/user-attachments/assets/3de56008-cd50-4395-bf2b-dd813650cd07

**Comment by ayangweb** [comment]
@amrbashir And this problem only occurs on macOS, Windows doesn't have this problem!


https://github.com/user-attachments/assets/102d190f-e6cf-4ffa-87c6-cdd52c796365

**Comment by amrbashir** [comment]
I don't have a macOS to triage this issue so please open a new issue for the stuck problem and provide a minimal repro.

**Comment by ayangweb** [comment]
Okay, I'll create a new demo and issue!

**Comment by ayangweb** [comment]
@amrbashir #1918
