### ISSUE TITLE
[sql] How can I take backup or locate the created db on the device on which software is installed

### ISSUE THREAD

**Issue by Jaydeep189** [tauri-apps/plugins-workspace#193]

**Comment by FabianLars** [comment]
The .db file is always stored at the path [`appDir()`](https://tauri.app/v1/api/js/modules/path/#appdir) returns (plus the path and/or filename you specifed).

For example on Windows this resolves to `AppData/Roaming/bundle-identifier/mydatabase.db`

**Comment by Jaydeep189** [comment]
> The .db file is always stored at the path [`appDir()`](https://tauri.app/v1/api/js/modules/path/#appdir) returns (plus the path and/or filename you specifed).
> 
> For example on Windows this resolves to `AppData/Roaming/bundle-identifier/mydatabase.db`

![image](https://user-images.githubusercontent.com/68139837/182008800-eb6cf528-9c36-4a96-98e5-f6648594a1b8.png)
![image](https://user-images.githubusercontent.com/68139837/182008819-91124c00-c8ed-41c6-85b0-3129116de33f.png)
the only database file I could find was in default and It was empty even though I have data in it

**Comment by FabianLars** [comment]
1) EBWebView is one folder too deep, also tauri stores the ebwebview folder in AppData/Local, so no idea where the one in your screenshot comes from, this is probably not a Tauri folder ~~(unless you changed the `data_directory`)~~
2) The `bundle-identifier` looks odd too, it is what's specified in tauri.conf.json under `bundle.identifier`, example: https://github.com/tauri-apps/tauri/blob/dev/examples/api/src-tauri/tauri.conf.json#L59

**Comment by Jaydeep189** [comment]
Yes, I have changed that config, but I am not sure about the data directory, I have changed the identifier name, but is that an issue?
here is my tauri.config file for reference, I don't know what I did wrong
```
{
  "$schema": "..\\node_modules/@tauri-apps/cli\\schema.json",
  "build": {
    "beforeBuildCommand": "npm run build",
    "beforeDevCommand": "",
    "devPath": "http://localhost:3000",
    "distDir": "../build"
  },
  "package": {
    "productName": "Hisaab",
    "version": "0.1.0"
  },
  "tauri": {
    "allowlist": {
      "all": true
    },
    "bundle": {
      "active": true,
      "category": "DeveloperTool",
      "copyright": "",
      "deb": {
        "depends": []
      },
      "externalBin": [],
      "icon": [
        "icons/32x32.png",
        "icons/128x128.png",
        "icons/128x128@2x.png",
        "icons/icon.icns",
        "icons/icon.ico"
      ],
      "identifier": "com.stacknyu.hisaab",
      "longDescription": "",
      "macOS": {
        "entitlements": null,
        "exceptionDomain": "",
        "frameworks": [],
        "providerShortName": null,
        "signingIdentity": null
      },
      "resources": [],
      "shortDescription": "",
      "targets": "all",
      "windows": {
        "certificateThumbprint": null,
        "digestAlgorithm": "sha256",
        "timestampUrl": ""
      }
    },
    "security": {
      "csp": null
    },
    "updater": {
      "active": false
    },
    "windows": [
      {
        "fullscreen": false,
        "minHeight": 800,
        "resizable": true,
        "title": "Hisaab Software",
        "minWidth": 1400
      }
    ]
  }
}
`

**Comment by FabianLars** [comment]
With that identifier the folder you're looking for should be `AppData\Roaming\com.stacknyu.hisaab\yourdb.db`

**Comment by Jaydeep189** [comment]
It's there, I confused it with the wholesale.exe folder
Thanks for helping!!!
