### ISSUE TITLE
[sql] How to use .dump in sqlite ? 

### ISSUE THREAD

**Issue by Jaydeep189** [tauri-apps/plugins-workspace#194]
```
export async function DumpDB() {
  await load;
  return db.execute(".dump");
}
```

`Uncaught (in promise) error returned from database: near ".": syntax error`

**Comment by FabianLars** [comment]
as far as i know, `.dump` is only accessible via the sqlite3 CLI program which is not used to work with databases programmatically.
So in short: you can't do that in your code. Only manually in the console.
