### ISSUE TITLE
Updater 2.0 ERROR 'Download request failed with status: 404 Not Found'

### ISSUE THREAD

**Issue by xiaoyihao001018** [tauri-apps/plugins-workspace#1946]
I checked the official documentation version 2.0 of the updater update module on October 17, 2024, and found that everything was configured according to the official documentation. However, the error message was ERROR 'Download request failed with status: 404 Not Found', and the configuration was written in both TS and Rust  
![image](https://github.com/user-attachments/assets/7ee93c5a-437b-4067-abbb-c7bbe7b9fd7b)
Next, I will post the core code
Rust：
![image](https://github.com/user-attachments/assets/debc3fc2-0f29-4516-9b56-ab1f74ffcf09)
TS：
![image](https://github.com/user-attachments/assets/024f7da2-de56-4516-9e62-949b4182e747)
I don't know where to start troubleshooting this error from

**Comment by FabianLars** [comment]
What's the download url? If you can't share it, can you make sure it works in a _private_ browser tab?

Also, could a proxy be the issue here?

**Comment by xiaoyihao001018** [comment]
> What's the download url? If you can't share it, can you make sure it works in a _private_ browser tab?
> 
> Also, could a proxy be the issue here?

Thank you. I found out that I wrote the wrong address for the file on the server. I have corrected it, but I have encountered a new problem
![image](https://github.com/user-attachments/assets/1818fc3f-e652-4a77-b75d-60eb2f08109d)
After downloading, there will be this error message
![image](https://github.com/user-attachments/assets/f80ccb68-a34a-48fc-88b4-b9d864a7f09a)
And I set it to basicUI. After downloading, there were no pop ups or interactions, which was similar to not downloading

**Comment by FabianLars** [comment]
UnexpectedKeyId means something's wrong with the private key / public key / signature - what exactly is a bit hard to say so start by double checking that the private and public keys are set correctly and belong to each other, and that the `sig` field is the content of the .sig file of the shipped updater artifact.
