### ISSUE TITLE
[sql] How to use the plugin commands from Rust side?

### ISSUE THREAD

**Issue by ecmel** [tauri-apps/plugins-workspace#1960]
I want to use the plugin execute and select commands from Rust side. Is there a way to do that?

**Comment by FabianLars** [comment]
Nope, the commands are currently not exposed on the rust side and won't be for a while at least while we're still re-working parts of the plugins.

For now (or for ever) you're better of using a normal rust sql crate directly instead.

Lastly, the feature request for what you're asking for is here: https://github.com/tauri-apps/plugins-workspace/issues/506
