### ISSUE TITLE
Tauri v2 - error on writeTextFile with path arg

### ISSUE THREAD

**Issue by Silbad** [tauri-apps/plugins-workspace#1969]
Hello, I can't create / write to a file with Tauri 2 (it worked for Tauri 1) with writeTextFile :

```
Uncaught (in promise) invalid args `path` for command `write_text_file`: command write_text_file expected a value for key path but the IPC call used a bytes payload
```

I add new permission : 

```json
  {
    "identifier": "fs:allow-write-text-file",
    "allow": [{ "path": "$APPDATA/**/*" }]
  },
```

Test with :

```ts
import { writeTextFile, BaseDirectory } from '@tauri-apps/plugin-fs';
const contents = JSON.stringify({ notifications: true });
await writeTextFile('config.json', contents, {
  baseDir: BaseDirectory.AppData,
  append: true 
});
```

Thanks

**Comment by Legend-Master** [comment]
I can't reproduce this, what version of tauri and the plugins are you on? You can get the info by running tauri cli `npx tauri info`

![image](https://github.com/user-attachments/assets/02e17886-05e6-46c6-b6e6-37f8e5df9e20)

**Comment by amrbashir** [comment]
you probably have an older version of `fs`, run `cargo update -p tauri-plugin-fs` in `src-tauri`

**Comment by Silbad** [comment]
That's right, completely forgot to update it. Thank you so much.
