### ISSUE TITLE
[window-state] When adding the window state plugin, it ignores "decoration" : false

### ISSUE THREAD

**Issue by abarrafo** [tauri-apps/plugins-workspace#1970]
If we setup custom toolbar, with decorations = false. This is broken by window-state-plugin

        
        "decorations": false,        
       
```
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_shell::init())
        .invoke_handler(tauri::generate_handler![greet])
        .plugin(tauri_plugin_window_state::Builder::new().build())
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

```
        
![Screenshot from 2024-10-23 13-30-04](https://github.com/user-attachments/assets/b0f0952d-dea0-46a5-b693-987f64765a4c)

now, remove 

```
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_shell::init())
        .invoke_handler(tauri::generate_handler![greet])
        // .plugin(tauri_plugin_window_state::Builder::new().build())
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
```
       
![Screenshot from 2024-10-23 13-32-25](https://github.com/user-attachments/assets/b8d3f488-dbb0-4eed-8f4c-26c9615476bf)

       
I am on developing on Fedora Linux. This is a brand new project using project generator, with javascript and react frontend.

**Comment by amrbashir** [comment]
This could be due to previously saved window state contained `decorations: true`, you can check `$HOME/.config./<identifier>/.window-state.json`

**Comment by amrbashir** [comment]
You could also choose which things should the plugin restore and which not, using this API https://docs.rs/tauri-plugin-window-state/latest/tauri_plugin_window_state/struct.Builder.html#method.with_state_flags

**Comment by abarrafo** [comment]
> This could be due to previously saved window state contained `decorations: true`, you can check `$HOME/.config./<identifier>/.window-state.json`

:arrow_up:  This was it!
