### ISSUE TITLE
[bug] Invalid args `rid` for command `load`: command load missing required key rid.

### ISSUE THREAD

**Issue by deeivihh** [tauri-apps/plugins-workspace#1973]
**Describe the issue**
Using `Store.load` as [indicated in the docs](https://v2.tauri.app/reference/javascript/store/#example-3) results in an error:

`Uncaught (in promise) invalid args rid for command load: command load missing required key rid`

**Steps to Reproduce**
1. Copy this example: `const store = await Store.load("settings.json");`
2. See console

**Environment:**
[✔] Environment
    - OS: Windows 10.0.26100 x86_64 (X64)
    ✔ WebView2: 129.0.2792.89
    ✔ MSVC: Visual Studio Build Tools 2022
    ✔ rustc: 1.81.0 (eeb90cda1 2024-09-04)
    ✔ cargo: 1.81.0 (2dbb1af80 2024-08-20)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.17.0
    - pnpm: 9.12.2
    - npm: 10.8.2
    - bun: 1.1.27

[-] Packages
    - tauri 🦀: 2.0.4
    - tauri-build 🦀: 2.0.1
    - wry 🦀: 0.46.2
    - tao 🦀: 0.30.2
    - @tauri-apps/api : 2.0.3
    - @tauri-apps/cli : 2.0.5

[-] Plugins
    - tauri-plugin-shell 🦀: 2.0.2
    - @tauri-apps/plugin-shell : 2.0.1
    - tauri-plugin-os 🦀: 2.0.0-rc.1
    - @tauri-apps/plugin-os : 2.0.0
    - tauri-plugin-store 🦀: 2.0.1
    - @tauri-apps/plugin-store : 2.1.0

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite

**Comment by deeivihh** [comment]
I should add an id or something like that but it is wrongly indicated in the docs?

**Comment by deeivihh** [comment]
i have read that it is fixed using `createStore`, but there is no export named like that, i guess it has changed.

**Comment by Legend-Master** [comment]
Update rust crate tauri-plugin-store to 2.1.0 should fix this, judging from your `tauri info` output

> ```
> - tauri-plugin-store 🦀: 2.0.1
> - @tauri-apps/plugin-store : 2.1.0
> ```

**Comment by deeivihh** [comment]
> Update rust crate tauri-plugin-store to 2.1.0 should fix this, judging from your `tauri info` output
> 
> > ```
> > - tauri-plugin-store 🦀: 2.0.1
> > - @tauri-apps/plugin-store : 2.1.0
> > ```

Oh, he did, my mistake. I thought by doing tauri add store it would update, but it didn't.
