### ISSUE TITLE
Errors with plugin-localhost and Tauri v2

### ISSUE THREAD

**Issue by Shackless** [tauri-apps/plugins-workspace#1974]
I recently migrated my app to Tauri v2 and am trying to update the old localhost config I had in my v1 version:

```
// Prevents additional console window on Windows in release, DO NOT REMOVE!!
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

use tauri::{utils::config::AppUrl, WindowUrl};

fn main() {
    let port = 5173;

    let mut context = tauri::generate_context!();
    let url = format!("http://localhost:{}", port).parse().unwrap();
    let window_url = WindowUrl::External(url);
    // rewrite the config so the IPC is enabled on this URL
    context.config_mut().build.dist_dir = AppUrl::Url(window_url.clone());

    tauri::Builder::default()
        .plugin(tauri_plugin_shell::init())
        .plugin(tauri_plugin_localhost::Builder::new(port).build())
        .run(context)
        .expect("error while running tauri application");
}
```

I was trying to follow the README in the plugin-localhost v2 branch but it gives several errors that I'm unable to resolve because I have 0 knowledge of rust. In cargo.toml, I updated the dependency to: `tauri-plugin-localhost = {version = "2"}`.

According to the README, I should now do this:

```
// Prevents additional console window on Windows in release, DO NOT REMOVE!!
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

use tauri::{Manager, window::WindowBuilder, WindowUrl};

fn main() {
    let port = 5173;

    tauri::Builder::default()
    .plugin(tauri_plugin_localhost::Builder::new(port).build())
    .setup(move |app| {
      app.ipc_scope().configure_remote_access(
        RemoteDomainAccessScope::new("localhost")
          .add_window("main")
      );

      let url = format!("http://localhost:{}", port).parse().unwrap();
      WindowBuilder::new(app, "main".to_string(), WindowUrl::External(url))
        .title("Example")
        .build()?;
      Ok(())
    })
    .run(tauri::generate_context!())
    .expect("error while running tauri application");
}
```

Now I get several errors:

- struct `WindowBuilder` is private
- unresolved import `tauri::WindowUrl` - no `WindowUrl` in the root
- no method named `ipc_scope` found for mutable reference `&mut tauri::App` in the current scope
- failed to resolve: use of undeclared type `RemoteDomainAccessScope` - use of undeclared type `RemoteDomainAccessScope`

I'd really appreciate some help. Thank you!

**Comment by FabianLars** [comment]
Please use this guide for the rust code: https://v2.tauri.app/plugin/localhost/
Additionally you also need the `"remote"` config from here: https://v2.tauri.app/security/capabilities/#remote-api-access but for localhost

**Comment by Shackless** [comment]
Thank you @FabianLars. I think that part finally works. Now the only remaining problem is that my sidebar is not starting in v2 but this is another issue.

**Comment by glib-0** [comment]
@Shackless Would you mind sharing how you got the localhost plugin to work? I created a new tauri app just to test it and followed the guide above but I'm getting this error: 

`Failed to setup app: error encountered during setup hook: a webview with label 'main' already exists`

**Comment by FabianLars** [comment]
either give it a new label instead of `"main"` (this will open 2 windows) or remove the window from tauri.conf.json (this is the first window with the `main` label).

**Comment by glib-0** [comment]
Ah I see, that works. Thanks!

**Comment by sheonny** [comment]
Hello, I configured it according to the above process and it can be packaged successfully, but the application cannot be opened and there is no response when double clicked?
