### ISSUE TITLE
[plugin-http] Add a warning when using forbidden headers without the unsafe-headers feature

### ISSUE THREAD

**Issue by LightQuanta** [tauri-apps/plugins-workspace#1979]
When sending a request using the `fetch` method provided by the http-client, [unsafe headers](https://github.com/tauri-apps/plugins-workspace/blob/4341d7f500290165a94e05006abbfe7f40045fc9/plugins/http/src/commands.rs#L386) are filtered out for security reason. While this is beneficial, it can be confusing when users need to use these headers, since the removal of unsafe headers result in no extra output. It took me a long time to find out why I cannot set the Cookies.

I propose adding [output statements here](https://github.com/tauri-apps/plugins-workspace/blob/4341d7f500290165a94e05006abbfe7f40045fc9/plugins/http/src/commands.rs#L194) in development mode to provide users with hints related to the usage of unsafe headers.

**Comment by amrbashir** [comment]
Sounds like a good idea, @LightQuanta would you like to open a PR?
