### ISSUE TITLE
[sql ]Unable to find Sqlite db path

### ISSUE THREAD

**Issue by aftabnaveed** [tauri-apps/plugins-workspace#198]
I was able to compile the plugin and run the test todo app, the documentation says that the sqlite db path can be found here

```
// sqlite. The path is relative to `tauri::api::path::BaseDirectory::App`.
```
 Although my records are being stored properly, but I am unable to locate the database file

Can you please help here?

**Comment by FabianLars** [comment]
See here for the path docs: <https://tauri.app/v1/api/js/modules/path#appdir>, tldr:
- Linux: `$XDG_CONFIG_HOME or $HOME/.config/bundle-id/`
- macOS: `$HOME/Library/Application Support/bundle-id/`
- Windows: `{FOLDERID_RoamingAppData}\bundle-id\` (-> AppData\Roaming\bundle-id\)
