### ISSUE TITLE
[feat] [notifications] Add support for Notification Badges (windows)

### ISSUE THREAD

**Issue by ahqsoftwares** [tauri-apps/plugins-workspace#1987]
I think we can also add support for Notification Badges. There's windows.rs api for the name.

# Use Case
- To show quick notifications
- Also, it'll make us attain feature richness for new users

Reference: <https://learn.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/badges#create-a-badge>

**Comment by ahqsoftwares** [comment]
Also, I can give it a try, if it can be considered

**Comment by FabianLars** [comment]
related tauri feature request: https://github.com/tauri-apps/tauri/issues/4489

not 100% sure if this should really be coupled with the notification plugin though 🤔

**Comment by amrbashir** [comment]
probably better be an API on `tauri::Window` and `tauri::WebviewWindow` can be implemented directly in tauri code base.

**Comment by ahqsoftwares** [comment]
Yeah, that seems that it should be implemented on the tauri code base

**Comment by amrbashir** [comment]
alright, closing in favor of https://github.com/tauri-apps/tauri/issues/4489
