### ISSUE TITLE
[fs][v2] how to get all the permissions of fs?

### ISSUE THREAD

**Issue by qzd1989** [tauri-apps/plugins-workspace#1989]
I want to read, write, mkdir files/folders into anywhere on windows 11....

I tried this:
> //src-tauri/capabilities/default.json
```json
  "permissions":[
    "fs:default",
    "fs:read-all",
    "fs:write-all",
    "fs:allow-rename",
    "fs:allow-mkdir",
    "fs:allow-exists",
    "fs:allow-watch",
    "fs:read-dirs"
]
```
but I still get error such as :
```
forbidden path: C:\scripts\hello\scripts\newFile
```
and ...
```
save file C:\scripts\hello\scripts\main.abc failed: invalid args `path` for command `write_text_file`: command write_text_file expected a value for key path but the IPC call used a bytes payload
```
**does anyone have the full right permissions? thank you...** 

my tauri info:
[✔] Environment
    - OS: Windows 10.0.22621 x86_64 (X64)
    ✔ WebView2: 130.0.2849.56
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.83.0-nightly (6c6d21008 2024-09-22)
    ✔ cargo: 1.83.0-nightly (eaee77dc1 2024-09-19)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: nightly-aarch64-pc-windows-msvc (default)
    - node: 20.17.0
    - yarn: 1.22.22
    - npm: 10.8.2

[-] Packages
    - tauri 🦀: 2.0.5
    - tauri-build 🦀: 2.0.1
    - wry 🦀: 0.46.3
    - tao 🦀: 0.30.3
    - @tauri-apps/api : 2.0.3
    - @tauri-apps/cli : 2.0.5

[-] Plugins
    - tauri-plugin-global-shortcut 🦀: 2.0.1
    - @tauri-apps/plugin-global-shortcut : 2.0.0
    - tauri-plugin-store 🦀: 2.1.0
    - @tauri-apps/plugin-store : 2.1.0
    - tauri-plugin-fs 🦀: 2.0.1
    - @tauri-apps/plugin-fs : 2.0.1
    - tauri-plugin-shell 🦀: 2.0.1
    - @tauri-apps/plugin-shell : 2.0.1
    - tauri-plugin-dialog 🦀: 2.0.1
    - @tauri-apps/plugin-dialog : 2.0.1
    - tauri-plugin-os 🦀: 2.0.1
    - @tauri-apps/plugin-os : 2.0.0

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite

**Comment by amrbashir** [comment]
read https://tauri.app/plugin/file-system/#permissions

**Comment by jaycliff** [comment]
@qzd1989 Try this:

```json
"permissions":[
    "fs:default",
    "fs:read-all",
    "fs:write-all",
    "fs:allow-rename",
    "fs:allow-mkdir",
    "fs:allow-exists",
    "fs:allow-watch",
    "fs:read-dirs",
    {
      "identifier": "fs:scope",
      "allow": ["**/*"]
    }
]
```

**Comment by DaniilSkLi** [comment]
@jaycliff Does not work with hidden dirs on linux :(

**Comment by FabianLars** [comment]
@DaniilSkLi scroll down in amr's link all the way to the bottom of the page
