### ISSUE TITLE
[sql] [examples:todos-app] yarn tauri dev error: Additional property 'useBootstrapper' is not allowed

### ISSUE THREAD

**Issue by shinshin86** [tauri-apps/plugins-workspace#199]
Hello!
I wanted to try `tauri-plugin-sql` and tried `todos-app(examples)` locally.

But when I run `yarn tauri dev`, I get the following error.

```
$ tauri dev
`tauri.conf.json` error on `tauri > bundle > deb`: Additional property 'useBootstrapper' is not allowed
`tauri.conf.json` error on `tauri > bundle > macOS`: Additional property 'useBootstrapper' is not allowed
error Command failed with exit code 1.
```

I am not familiar with `tauri` and `tauri-plugin-sql` yet, is this something else I need to command?

My environment and the actual command I ran are listed below.

```sh
$ tauri info

Environment
  › OS: Mac OS 11.6.7 X64
  › Node.js: 16.14.0
  › npm: 8.3.1
  › pnpm: 7.1.0
  › yarn: 1.22.17
  › rustup: 1.24.3
  › rustc: 1.59.0
  › cargo: 1.59.0
  › Rust toolchain: stable-aarch64-apple-darwin

Packages
  › @tauri-apps/cli [NPM]: 1.0.3
  › @tauri-apps/api [NPM]: 1.0.0
```

Command executed is here.

```sh
git clone https://github.com/tauri-apps/tauri-plugin-sql.git
cd tauri-plugin-sql/examples/todos-app
yarn install
yarn tauri dev
```

**Comment by AlwaysFocus** [comment]
@shinshin86 If you remove the 'useBootstrapper' in the macOS and deb objects in tauri.conf.json it will compile and run properly.

**Comment by shinshin86** [comment]
@AlwaysFocus I see. Thank you!

However, at this time, this todos-app does not seem to work yet.
(The errors are as follows)

```
[0] > svelte-kit dev is no longer available — use vite dev instead
[0]   1. Install vite as a devDependency with npm/pnpm/etc
[0]   2. Create a vite.config.js with the @sveltejs/kit/vite plugin (see below)
[0]   3. Update your package.json scripts to reference `vite dev` instead of `svelte-kit dev`
```

The cause is due to the following breaking change in `@sveltejs/kit`.
https://github.com/sveltejs/kit/pull/5332

I have created a PR that add a response to this.
Would it possible to have it checked?
https://github.com/tauri-apps/tauri-plugin-sql/pull/123
