### ISSUE TITLE
[dialog][v2][macOS] The other two methods such as `ask` have incorrect `kind` arguments.

### ISSUE THREAD

**Issue by ayangweb** [tauri-apps/plugins-workspace#2009]
On macOS, the default `kind` of `ask`, `message` and `confirm` methods is `info` no problem, but setting it to `warning` is still an `info` popup, and setting it to `error` is a `warning` popup! It works fine on Windows.

BTW, Both development and production environments have the same result!

Demo project: https://github.com/ayangweb/tauri-plugin-dialog-demo

macOS:

https://github.com/user-attachments/assets/42aebcd6-52f1-4b0c-9fd1-0b3f9164180b

Windows:

https://github.com/user-attachments/assets/0edd6d14-0620-4a68-bcdb-3922e4b53c27

**Comment by Legend-Master** [comment]
Seems like an upstream (rfd) thing, from the code, they seem to map the kind to [`NSAlertStyle`](https://developer.apple.com/documentation/appkit/nsalertstyle)

> https://github.com/PolyMeilex/rfd/blob/11b96518823e2e5ed9ca2907814b3b53f4415d76/src/backend/macos/message_dialog.rs#L34-L38

From the docs, it seems like the info and warning dialog look the same though

> https://developer.apple.com/documentation/appkit/nsalertstyle#:~:text=Currently%2C%20there%E2%80%99s%20no%20visual%20difference%20between%20informational%20and%20warning%20alerts.
