### ISSUE TITLE
On macOS a deadlock occurs when opening windows using the `on_open_url` method with the `deep_link` plugin

### ISSUE THREAD

**Issue by vincent-herlemont** [tauri-apps/plugins-workspace#2017]
I'm trying to open a `Windows` instance by dragging files onto the Dock icon on macOS. But when I do it, the application freezes and a DeadLock appears in the error report.

Note: This error does not occur if the app is not running.

## How to reproduce ?

I use the deeplink plugin [v2.tauri.app/deep-linking](https://v2.tauri.app/fr/plugin/deep-linking/), below the setup:

```rust
    tauri::Builder::default()
        .plugin(tauri_plugin_deep_link::init())
        .setup(move |app| {
             use tauri_plugin_deep_link::DeepLinkExt;

             let app_handle_deep_link: tauri::AppHandle = app.handle().clone();

             app.deep_link().register_all()?;
             app.deep_link().on_open_url(move |event| {
                log::info!("## deep link URLs: {:?}", event.urls());

                let mut window_config = tauri_utils::config::WindowConfig::default();
                window_config.title = "External from deep link".to_string();
                window_config.label = "external_from_deep_link".to_string();

                log::info!("## creating window from deep link");
                let _window =
                    tauri::window::WindowBuilder::from_config(&app_handle_deep_link, &window_config)
                        .unwrap()
                        .build()
                        .expect("failed to build window");
                log::info!("## window created from deep link");
              }
         ...
        }
    ...
```

## Result 

In the logs, we can clearly see that the first two `log::info!` were called, just before the assignment of the variable `let _window =`, which is the creation of the window. The last log `## window created from deep link` never appears. I can conclude that it is the creation of the window that is causing the deadlock.

```txt
[2024-11-07][06:58:02][test_tray_app_lib][INFO] ## deep link URLs: [Url { scheme: "file", cannot_be_a_base: false, username: "", password: None, host: None, port: None, path: "/Users/../Movies/test_1.mp4", query: None, fragment: None }]
[2024-11-07][06:58:02][test_tray_app_lib][INFO] ## creating window from deep link
```

The application freezes.

```bash
Deadlocked:       1 thread - Thread 0x7ad5 "main" DispatchQueue "com.apple.main-thread"(1)
...
```

You can access the full report here: [report.txt](https://github.com/user-attachments/files/17657335/report.txt)

## Expected result

The window should open without a deadlock.

## Info

<details><summary>cargo tauri info</summary>

```
❯ cargo tauri info

[✔] Environment
    - OS: Mac OS 15.0.1 arm64 (X64)
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.81.0 (eeb90cda1 2024-09-04)
    ✔ cargo: 1.81.0 (2dbb1af80 2024-08-20)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (environment override by RUSTUP_TOOLCHAIN)
    - node: 22.4.1
    - npm: 10.8.1

[-] Packages
    - tauri 🦀: 2.0.6
    - tauri-build 🦀: 2.0.2
    - wry 🦀: 0.46.3
    - tao 🦀: 0.30.5
    - tauri-cli 🦀: 2.0.2

[-] Plugins
    - tauri-plugin-deep-link 🦀: 2.0.1
    - tauri-plugin-shell 🦀: 2.0.2
    - tauri-plugin-global-shortcut 🦀: 2.0.1
    - tauri-plugin-single-instance 🦀: 2.0.1
    - tauri-plugin-log 🦀: 2.0.2

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
 ```

</details>

**Comment by FabianLars** [comment]
Can you try moving the Window builder into a `tauri::async_runtime::spawn()` task?

**Comment by vincent-herlemont** [comment]
@FabianLars Thank you for your response, it works perfectly. Is it possible to have an explanation? (Maybe it would be wise to indicate this kind of thing in the documentation, if possible, I am available to do it)

**Comment by FabianLars** [comment]
i'm not exactly sure. Opening windows on the main thread is always a bit tricky. While we only warn about this in the window builder docs for Windows (os) it's not the first time i hear about this on macOS.
