### ISSUE TITLE
permissions:How http allows dynamic domain name access?

### ISSUE THREAD

**Issue by lhc122525** [tauri-apps/plugins-workspace#2040]
Error: url not allowed on the configured scope
Domain name is returned through the interface，How can I allow http dynamic domain name access to the api?

{
      "identifier": "http:default",
      "allow": [
        {
          "url": "http://**"
        }
      ]
    },

**Comment by FabianLars** [comment]
What kind of url are we talking about? For example `http://google.com` (and its https equiv if configured) works fine for me.

If the url contains a port though then the scope has to be configured a bit more ugly: `"url": "http://*:*"`
