### ISSUE TITLE
[http] can't debug requests

### ISSUE THREAD

**Issue by thewh1teagle** [tauri-apps/plugins-workspace#2055]
with fetch i can see plain request/response body
with tauri fetch i can't
does it possible? and if not how can we improve it?

**Comment by thewh1teagle** [comment]
It's actually an issue, not a bug. I literally copied pasted working curl command as fetch command and I get 401 (unauthrized)
the feature `unsafe-headers` enabled.

I fixed the issue by adding

```console
Origin: '',
Referer: '',
```

For unsetting the headers. but it was very hard to debug I needed to manually construct curl requests from fetch and try outside of tauri

**Comment by amrbashir** [comment]
I have added tracing behind a feature flag in #2079, so you can use tauri-plugin-log or CrabeNebula devtools to inspect the requests and responses
