### ISSUE TITLE
[sql] I want to run SQL file, how do I need to do it

### ISSUE THREAD

**Issue by cuizhijun** [tauri-apps/plugins-workspace#206]
Execute the SQL file directly without reading the SQL file

`db = await Database.load(`sqlite:${dbPath}`)`

Can I use db.** or fs.** command

maybe other

**Comment by FabianLars** [comment]
If you want to initialize your database with this file then this is what migrations are for: <https://github.com/tauri-apps/tauri-plugin-sql/blob/dev/examples/vue-todos/src-tauri/src/main.rs#L15-L23>.
If you want to execute .sql files at runtime you need to _read_ it first (`fs.readBinaryFile`) and use `db.execute(content_of_sql_file)`. Keep in mind that you have to manually include the .sql file in the bundled app then! (for example via tauri.conf.json's `resources`)
