### ISSUE TITLE
[bug] Could not connect to localhost: Connection refused on autostart at Linux

### ISSUE THREAD

**Issue by ansirotenko** [tauri-apps/plugins-workspace#2063]
### Describe the bug

Recently added autostart plugin to my application. Now I'm observing following situation. After restart of the system application cannot display gui, saying "Could not connect to localhost: Connection refused".
Happens only on linux, macOS and windows are ok.

If you close app and then start normally, it will work correctly.

link to the app https://github.com/ansirotenko/ccv/tree/main

### Reproduction

Build application for release. Install it with snap or dpkg. Check autostart. Restart system. Open application.

### Expected behavior

After restart app must work correctly

### Full `tauri info` output

```text
Enviromnet
- linux: Ubuntu 22.0.4

Packages
    - tauri : 2.0.4
    
Plugins
- tauri-plugin-autostart : 2.0.1
- tauri-plugin-autostart : 2.0.1
- tauri-plugin-clipboard : 2.1.9
- tauri-plugin-global-shortcut : 2.0.1
- tauri-plugin-log : 2.0.1
- tauri-plugin-process : 2.0.1
- tauri-plugin-single-instance : 2.0.1
- tauri-plugin-shell : 2.0.1
- tauri-plugin-updater : 2.0.2

App
    - build-type: bundle
    - CSP: none
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: react.js
    - bundler: Vite
```

**Comment by FabianLars** [comment]
can you share the content of the `~/.config/autostart/{app_name}.desktop` file? This can only really happen if a dev instance is registered there 🤔

**Comment by ansirotenko** [comment]
> can you share the content of the `~/.config/autostart/{app_name}.desktop` file? This can only really happen if a dev instance is registered there 🤔

You are right. I had debug version at startup file
```
[Desktop Entry]
Type=Application
Version=1.0
Name=ccv
Comment=ccvstartup script
Exec=/home/ansirotenko/ccv/src-tauri/target/debug/ccv
StartupNotify=false
Terminal=false
```

Guess first time I tried autostart with debug version. But it is little bit wired, because I have logic on every start of the application checking following

```
    if autostart && !autostart_manager.is_enabled()? {
        autostart_manager.enable()?;

        return Ok(());
    }
```
Probably `autostart_manager.is_enabled` does not check for application path. Because release version was opened after right installation and debug version was untouched.

**Comment by FabianLars** [comment]
> Probably autostart_manager.is_enabled does not check for application path

That could be, yeah. Maybe guard that blog with `#[cfg(not(debug_assertions))]` or `#[cfg(not(dev))]` then.

**Comment by Kieirra** [comment]
For me, this was happening because the OS tried to launch the debug version of the application instead of the installed production version. This occurred because I enabled the "Run at startup" feature while developing on the same machine.

In development mode, the Rust backend and the web frontend run as separate processes. At system startup, the web development server is not active, so the backend fails to connect to the frontend, resulting in the Connection refused error.
