### ISSUE TITLE
[dialog] `okLabel` and `cancelLabel` options in `ConfirmDialogOptions` seem to go ignored

### ISSUE THREAD

**Issue by Raphiiko** [tauri-apps/plugins-workspace#2064]
I am currently using `tauri` 2.1.1 with `tauri-plugin-dialog` 2.0.3.

### What happens
When I call the following:

```typescript
import { ask } from '@tauri-apps/plugin-dialog';
...
let result = await ask('MESSAGE', {
        title: 'TITLE',
        okLabel: 'A',
        cancelLabel: 'B',
});
```
It results in the following dialog:
![image](https://github.com/user-attachments/assets/051b0eb9-6d19-41b7-93a9-e0baefb4e4f1)

### Expected behaviour

I would expect the dialog buttons labeled 'Yes' and 'No' to instead show 'A' and 'B' respectively.

**Comment by Legend-Master** [comment]
I can't reproduce this, are your js and rust tauri-plugin-dialog version all on latest? (v2.0.1 for js and v2.0.3 for rust)

![image](https://github.com/user-attachments/assets/31ee8f39-c67b-4d49-b5ad-38507d545cb6)

**Comment by Raphiiko** [comment]
I am indeed already on the latest versions, but now the next day I suddenly can't seem to reproduce it anymore either. Thanks for taking a look anyways!
