### ISSUE TITLE
tauri_plugin_single_instance callback runs on "tokio-runtime-worker"

### ISSUE THREAD

**Issue by abhinavrathore-ts** [tauri-apps/plugins-workspace#2080]
```
pub fn run() {
    eprintln!("main: {:?}", thread::current().name());

    // Reading message works here.

    tauri::Builder::default()
        .setup(|app| {
            #[cfg(desktop)]
            let _ = app
                .handle()
                .plugin(tauri_plugin_single_instance::init(|app, args, cwd| {
                   // Reading message does not work here.
                    eprintln!(
                        "tauri_plugin_single_instance: {:?}",
                        thread::current().name()
                    );
                }));
            Ok(())
        })
        .plugin(tauri_plugin_shell::init())
        // .plugin(tauri_plugin_single_instance::init(|app, args, cwd| {
        //     eprintln!(
        //         "tauri_plugin_single_instance: {:?}",
        //         thread::current().name()
        //     );
        // }))
        .invoke_handler(tauri::generate_handler![greet])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
    }
```
**Output:**
```
main: Some("main")
tauri_plugin_single_instance: Some("tokio-runtime-worker")
```

### Objective?

I am attempting to send a message from `chrome.runtime.sendNativeMessage` to a Tauri app. The issue arises because the `init` callback is running in a separate thread, causing the `stdio` to be empty and the message to not be received. 

When I read the message on the main thread, it works correctly.

### Why do I need to run this in `tauri_plugin_single_instance::init`?

I need to process the messages in the `init` callback because I want to emit the received message from the Chrome extension to the frontend of the Tauri app. To achieve this, I require access to the `App` instance.

**Comment by FabianLars** [comment]
> Why do I need to run this in tauri_plugin_single_instance::init?
I need to process the messages in the init callback because I want to emit the received message from the Chrome extension to the frontend of the Tauri app. To achieve this, I require access to the App instance.

Sorry but i still don't understand why you need the single instance plugin for this. You're literally using `app` outside of it (the `app.handle()` call).

The single instance callback is only executed if another tauri app instance is opened. Therefore i think this isn't a thread issue but simply the callback never getting executed.
Edit: Okay sorry this didn't make 100% sense, if it wouldn't be executed you wouldn't see the thread name. Still something doesn't add up here...

**Comment by abhinavrathore-ts** [comment]
> > Why do I need to run this in tauri_plugin_single_instance::init?
> > I need to process the messages in the init callback because I want to emit the received message from the Chrome extension to the frontend of the Tauri app. To achieve this, I require access to the App instance.
> 
> Sorry but i still don't understand why you need the single instance plugin for this. You're literally using `app` outside of it (the `app.handle()` call).
> 
> The single instance callback is only executed if another tauri app instance is opened. Therefore i think this isn't a thread issue but simply the callback never getting executed.

I want to ensure that only a single instance of the application is running. Without this, every message sent from the Chrome extension would launch a new instance of the application.

**Comment by FabianLars** [comment]
how does the chrome extension send the data? As a launch argument? Those would be available in `args`.
If the extension first launches the second instance, and then sends the data to that instance via stdio then it will get lost because the single-instance plugin will exit right away.

also just to be clear, the single-instance callback runs in your main app context, not in your secondary app, so you can't read the stdin of the secondary app in that callback.

**Comment by abhinavrathore-ts** [comment]
> how does the chrome extension send the data? As a launch argument? Those would be available in `args`. If the extension first launches the second instance, and then sends the data to that instance via stdio then it will get lost because the single-instance plugin will exit right away.
> 
> also just to be clear, the single-instance callback runs in your main app context, not in your secondary app, so you can't read the stdin of the secondary app in that callback.

All I know is that chrome extension writes it to the `stdio` of the application [Native Messaging](https://developer.chrome.com/docs/extensions/develop/concepts/native-messaging#native-messaging-host)

**The code below works** — could you please explain why it functions correctly with a single instance?

```
pub fn run() {
    eprintln!("$$$$$ main: {:?}", thread::current().name());

   // Reading stdio messages works correctly here for each message received in a single instance.
   // The only issue here is that I don’t have an instance of AppHandle to emit messages.
   
    tauri::Builder::default()
        .plugin(tauri_plugin_shell::init())
        .plugin(tauri_plugin_single_instance::init(|app, args, cwd| {}))
        .invoke_handler(tauri::generate_handler![greet])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
   }

```

**Comment by FabianLars** [comment]
> could you please explain why it functions correctly with a single instance?

basically what i said in my last message. It seems like the instance spawned by the chrome instance has to be kept running to read/write data from/to the extension.

The single-instance plugin makes the secondary instance close immeditaly though. But even then, you couldn't forward the stdio from that second instance to your primary one.

This means that you need 2 instances of your app (or outsource the extension communication into a second binary). Your main app that also shows the tauri windows etc, and a second instance spawned by the chrome extension that will communicate with the extension but also with the main app instance.

The single-instance plugin won't help you here.
