### ISSUE TITLE
[feat][http-plugin] Allow/Deny based on bundle external file

### ISSUE THREAD

**Issue by 0xhckr** [tauri-apps/plugins-workspace#2083]
Currently, the only way of allowing or disallowing access to certain urls is based on the following file:

```jsonc
// capabilities/main.json
"permissions": [... ,{
  "identifier": "http:default",
  "allow": [{ "url": "http://127.0.0.1:*" }, { "url": "http://localhost:*" }]
}]
```
My suggestion simply is to allow application developers to do something like:
```jsonc
// capabilities/main.json
"permissions": [... ,{
  "identifier": "http:default",
  "allow": [{ "url": "http://127.0.0.1:*" }, { "url": "http://localhost:*" }, { "file": "~/.config/app/allow.json" }]
}]
```

```jsonc
// ~/.config/app/allow.json
[{ "url" : "https://example.com:*" }, ...]
```

This allows end-users to manually allow additional urls to be accessible that can be configured within the tauri-built app without arbitrarily allowing all urls and giving the end user control.

(The specific use case this is trying to solve is one where you can specify a custom url for an ollama instance inside of GitButler. GitButler uses the http plugin but it only allows 127.0.0.1:* and localhost:*. An ollama instance exists on my local network which means I'd need to update main.json and run my own build to allow access to the ollama instance. With this change, myself, and other end users will be allowed to specify custom urls under ~/.config/gitbutler/allow.json (or other directories specified by GitButler's team) and leaves permissibility of url access in the hands of the end user should the developers allow it)

**Comment by amrbashir** [comment]
You can use https://docs.rs/tauri/latest/tauri/trait.Manager.html#method.add_capability and pass it either, a JSON as a string or [`CapabilityBuilder`](https://docs.rs/tauri/latest/tauri/ipc/struct.CapabilityBuilder.html)

**Comment by 0xhckr** [comment]
This probably does what we need it to do - thanks! I'm going to try implementing this locally and go from there!
