### ISSUE TITLE
[sql] Consider replacing the examples with a simpler one

### ISSUE THREAD

**Issue by JonasKruckenberg** [tauri-apps/plugins-workspace#209]
Both example apps in this repo are broken. I'd vote for removing and replacing them with a simpler example app, as they are super complex to understand and maintain. Not great for an example IMO.

**Comment by FabianLars** [comment]
Can you explain in what way they are broken? Because we did extensive testing and everything was working fine. (at least for the vue example)

**Comment by JonasKruckenberg** [comment]
> Can you explain in what way they are broken? Because we did extensive testing and everything was working fine. (at least for the vue example)

Sorry, I think my cargo setup was weird when trying to run the vue example, it wouldn't even start. (Seeing @ksnyde PR I think that example works pretty well 😉)

The other one doesn't though

**Comment by staniboy** [comment]
Cargo.toml example in installation should look like something like this: 

[dependencies.tauri-plugin-sql]
git = "https://github.com/tauri-apps/tauri-plugin-sql"
features = ["sqlite"] # or "postgres", or "mysql"
branch = "release"

otherwise it won't wint 0.1.0 tag

**Comment by yankeeinlondon** [comment]
Wow, not sure how I missed this issue. Sorry to be so late to the party. Looking at the thread i'm not sure whether there is still an open issue here?

**Comment by truestbyheart** [comment]
Thanks a lot, @staniboy. I think we need to do a more in-depth documentation

**Comment by FabianLars** [comment]
Both examples work now but i'll keep this issue open for now because i kinda agree that they are too complex.

**Comment by yankeeinlondon** [comment]
We should close this. I have one and soon two PRs to reduce the the example apps to just the VueJS one which is the only one I'm maintaining. As for "being too complex" ... I'm not sure I follow this logic. This is precisely as complex as a million other TODO examples i've seen before.
