### ISSUE TITLE
[window-state] window state does not record maximize correctly

### ISSUE THREAD

**Issue by joshua7v** [tauri-apps/plugins-workspace#21]
Here is a video clip to show the issue

https://user-images.githubusercontent.com/4159858/168640743-561163bd-a570-456b-9fdf-ee84f05e1eb3.mp4

Its not a high quality recording, but should be enough to see what I'm doing

This is a brand new app created from create-tauri-app, and the only modification is adding window-state plugin.

expected behavior:
reopen a maximized app should stay in maximized

**Comment by manuel3108** [comment]
Apparently this does not only occur while maximizing the window, but after using any of the integrated windows resizing mechanisms, like splitting the screen in half.

https://user-images.githubusercontent.com/30698007/175800111-7f9b6bb4-63ec-4cf9-bb77-45f1a527f608.mp4

```
[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.0.0", features = ["api-all"] }
tauri-plugin-window-state = "0.1"
```

**Comment by FabianLars** [comment]
This should be fixed since a few months when we switched to saving the window state when closing the window instead of listening to move/resize events
