### ISSUE TITLE
[HTTP] Wildcarding for all URLs does not work with [host]:[port] notation

### ISSUE THREAD

**Issue by nicholasdgoodman** [tauri-apps/plugins-workspace#2131]
Unsure if this is a "bug" or a "feature", but a somewhat mixed observation between #1468 and #1484 -- namely that specifying an HTTP allow list with wildcarded URLs does no work the same as V1:

```
{
  "identifier": "http:default",
  "allow": [
    {
      "url": "http://*"
    },
    {
      "url": "https://*"
    }
  ]
},
```

Previously, these wildcard patterns work with all URLs, whether or not the port number is specified:
- `http://localhost/route`
- `http://localhost:8080/route`
- `https://example.com`
- etc.

However, I observe that using Tauri runtime v2.2.0, this wildcard syntax is now inadequate.

If this is actual bug, there is a workaround -- you can specify the alternate syntax explicitly:

```
{
  "identifier": "http:default",
  "allow": [
    {
      "url": "http://*"
    },
    {
      "url": "https://*"
    },
    {
      "url": "http://*:*"
    },
    {
      "url": "https://*:*"
    }
  ]
},
```

If this behavior is by-design or intended, please close.

**Comment by FabianLars** [comment]
as far as i know this is intentional. in v1 the pattern logic was a bit, let's say "simple". In v2 it's trying to follow the URLPattern standard.
