### ISSUE TITLE
[bug][plugin-fs] Access events not being generated on Windows

### ISSUE THREAD

**Issue by nicolaspapp** [tauri-apps/plugins-workspace#2159]
Hey there. I am trying the FS plugin on Tauri v2.0
OS: Windows 11

I basically want to track changes in a particular directory. I can see the plugin working well in:
- WatchEventKindCreate
- WatchEventKindModify
- WatchEventKindRemove

However I am not getting any event for WatchEventKindAccess. Is there any compatibility issue on windows? Or that should be working there as well?

**Comment by FabianLars** [comment]
This isn't exactly clearly documented in the upstream project: https://docs.rs/notify-types/1.0.0/notify_types/event/enum.EventKind.html#variant.Access
> Only some platforms are capable of generating these.

But looking at the source code it looks like the Windows implementation indeed doesn't contain that event. The crates are pretty solid imo so i assume this is indeed an OS limitation.

**Comment by nicolaspapp** [comment]
@FabianLars, yes, you are right. I can confirm since I did a quick demo with just the Notify crate and had exactly the same issue.
