### ISSUE TITLE
[sql] Support update hook in sqlite3

### ISSUE THREAD

**Issue by percy507** [tauri-apps/plugins-workspace#216]
Hi!
I am trying to build a desktop app by using tauri.
And I need to store data locally and sync data to server when local data changes.
Through some research, I find sqlite3 have native [update hook](https://www.sqlite.org/c3ref/update_hook.html).

**Comment by percy507** [comment]
Use [rusqlite](https://github.com/rusqlite/rusqlite)

**Comment by TobiasGrothmann** [comment]
I'm working on a react-native app also running on tauri. How could you access the update hook there?

**Comment by lethargistic** [comment]
would also like to have this without having to use another lib
