### ISSUE TITLE
[sql] Add support for iOS (SQLite)

### ISSUE THREAD

**Issue by velocitysystems** [tauri-apps/plugins-workspace#2177]
Hello! 👋 I'm currently evaluating Tauri for a cross platform Android, iOS and Windows project.

However there is currently no iOS (SQLite) support for the `sql` plugin. Is this on the roadmap? If not, is there community interest in contributing toward this effort?

**Comment by kzKallisti** [comment]
+1; came here looking for this exact information for the same reasons

I am potentially willing to lend development efforts to make this happen, if a maintainer can help identify the scope of the work required

**Comment by FabianLars** [comment]
More context here: https://github.com/tauri-apps/plugins-workspace/issues/1867

**Comment by velocitysystems** [comment]
Thanks for the context @FabianLars. What’s the process for moving forward with adding iOS support?

If interest exists to get this done, is a member of the working group assigned to coordinate this effort or is it simply a matter of pushing a draft PR etc for discussion?

**Comment by FabianLars** [comment]
> What’s the process for moving forward with adding iOS support?

Well again, i don't think anyone even tested the plugin on iOS yet, so that would be good a first step 🙃 Without that it's hard for me to suggest how to move forward.

So far i only know about an issue in the low level sqlite bindings when building for the ios simulator rust target `aarch64-apple-ios-sim` https://github.com/rusqlite/rusqlite/issues/1579

> If interest exists to get this done, is a member of the working group assigned to coordinate this effort or is it simply a matter of pushing a draft PR etc for discussion?

At the moment I don't have any member available (including myself) to whom i could assign this to. So the more initiative there is from the community, the better.

**Comment by jfahrenkrug** [comment]
@velocitysystems @FabianLars It seems to work on iOS. I've added the plugin by following the steps from the docs (https://v2.tauri.app/plugin/sql/):

```
npm run tauri add sql
cd src-tauri
cargo add tauri-plugin-sql --features sqlite
```

Then I added these two lines to `capabilities/default.json`:

```
"sql:default",
"sql:allow-execute",
```

After that, I was able to open and read a SQLite DB from TypeScript, running both in the iOS Simulator and on device:

```
import Database from '@tauri-apps/plugin-sql';

...

const db = await Database.load('sqlite:customers/customers.db');
const result = await db.select<Customer[]>(`SELECT ...`);
```

I'd venture to say that the docs can be updated to reflect that it works on iOS.

**Comment by FabianLars** [comment]
Thank you for testing it (and telling us about the result...)! I updated the docs just now (waiting for CI to get it live)

**Comment by velocitysystems** [comment]
Great work @jfahrenkrug. Thanks @FabianLars!
