### ISSUE TITLE
[store] Cannot install plugin either for Rust or JS/TS

### ISSUE THREAD

**Issue by boguz** [tauri-apps/plugins-workspace#219]
I tried to follow the readme instructions, but i get a couple of different errors when installing the plugin both for Rust and for the FE

**For Rust** i have added the following to my `Cargo.toml`:
```
[dependencies.tauri-plugin-store]
git = "https://github.com/tauri-apps/tauri-plugin-store"
tag = "v0.1.0"
#branch = "main"
```

When i try to run the app i get this on the console:
```
 Updating git repository `https://github.com/tauri-apps/tauri-plugin-store`
error: failed to get `tauri-plugin-store` as a dependency of package `app v0.1.0 (/Users/myName/Sites/my-app/app/src-tauri)`

Caused by:
  failed to load source for dependency `tauri-plugin-store`

Caused by:
  Unable to update https://github.com/tauri-apps/tauri-plugin-store?tag=v0.1.0

Caused by:
  failed to find tag `v0.1.0`

Caused by:
  reference 'refs/remotes/origin/tags/v0.1.0' not found; class=Reference (4); code=NotFound (-3)
```

**On the JS side** i have tried to install it by running:
```
npm install github:tauri-apps/tauri-plugin-store#v0.1.0
```

but this gives me:
```
npm ERR! code 1
npm ERR! The git reference could not be found
npm ERR! command git --no-replace-objects checkout v0.1.0
npm ERR! error: pathspec 'v0.1.0' did not match any file(s) known to git

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/myName/.npm/_logs/2022-10-15T18_39_27_111Z-debug-0.log
```

Not sure if this is needed, but here is the output from `npm run tauri info`:
```
Environment
  › OS: Mac OS 12.4.0 X64
  › Node.js: 16.14.0
  › npm: 8.3.1
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.64.0
  › cargo: 1.64.0
  › Rust toolchain: stable-aarch64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.1.1
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.1.1,
  › tauri-build [RUST]: 1.1.1,
  › tao [RUST]: 0.14.0,
  › wry [RUST]: 0.21.1,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:5173/

App directory structure
  ├─ types
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ src-tauri
  └─ src
```

This is my first project with Tauri, so i am sorry if it isn't working because i am doing something wrong. If that is the case, maybe we should improve the docs / readme instructions

**Comment by FabianLars** [comment]
The plugin wasn't released yet so the readme is still wrong. For now just remove the tag line from cargo.toml and #v0.1.0 from the npm install command

**Comment by boguz** [comment]
@FabianLars Oh, ok.
I would suggest that you add some kind of notice to the README, so people know it still isn't ready to use.  :/

**Comment by JonasKruckenberg** [comment]
> @FabianLars Oh, ok.
> 
> I would suggest that you add some kind of notice to the README, so people know it still isn't ready to use.  :/

It is ready to use and already used in a handful of production apps :), we just haven't had the time to polish it to something that would be acceptable on npm or crates.io (docs, readme, etc.).

That's why you still need to install it from git/github instead of a registry.

**Comment by boguz** [comment]
@JonasKruckenberg sure, that is fine. But as you can see on my original i couldn't use it even when installing it from github.

Like we already discussed on the issue for the tauri-plugin-positioner issue, i do understand that keeping documentation update can be a lot of work.
But i think it is worth it!
Tauri is still a relatively new project, so a lot of people will be using it for the first time and relying on docs to get things to work.
I am sure a lot os users, like myself, have not even used Rust before and come from a FE (Electron ?!) world.

I can speak only for myself, but while this as not made me look for a Tauri alternative, it has made my first experience with not really good. Good docs are essential for any project!

I would love to help out, but i don't really know how...
Maybe i can do some testing, or help with writing the docs from a noob pov. 😉
