### ISSUE TITLE
[autostart] After integration no pop up comes up to allow for activating autostart

### ISSUE THREAD

**Issue by crudolf** [tauri-apps/plugins-workspace#22]
I do not get how to activate autostart for the tauri app. I integrated it as described, but nothing happends when I start the app. I use 12.2.1 Monterey with MacBook Pro (16", 2021).

Do I need to trigger the setup somehow?

**Comment by lucasfernog** [comment]
Did you run the enable function? See the example: https://github.com/tauri-apps/tauri-plugin-autostart/blob/dev/examples/svelte-app/src/App.svelte

**Comment by crudolf** [comment]
Ok, now I see. I'll try out. Is there a way to execute those functions from Rust? Sorry, I am migrating from electron and am a beginner with tauri-environment.

**Comment by FabianLars** [comment]
No there is no way. Tauri plugins are generally a tool to create javascript apis for existing rust stuff (the auto_launch crate in this case). So if you want to use it in rust, you'd need to use the crate directly which seems to be fairly easy looking at this plugin's source code.

**Comment by crudolf** [comment]
Thank you for clarification!
