### ISSUE TITLE
[store] Installation Method did not work

### ISSUE THREAD

**Issue by dchicchon** [tauri-apps/plugins-workspace#220]
When trying to install this plugin in my `Cargo.toml`, I received the following error: 
```
error:  `failed to get `tauri-plugin-store` as a dependency of package app
caused by: failed to load source for dependency `tauri-plugin-store`
caused by: failed to find tag `v0.1.0`
```

So in this case I assume that the tags were not found. I then opted to use the `main` branch config which also did not work for me.

The below config is the only install method that worked for me

```
[dependencies.tauri-plugin-store]
git = "https://github.com/tauri-apps/tauri-plugin-store"
branch = "dev"
```

Is this the case where the documentation install instructions may be outdated?

**Comment by nothingismagick** [comment]
You are right, there's not been an official release of this in the git tree.

**Comment by nothingismagick** [comment]
So the documentation is actually "predated" 😓

**Comment by ndom91** [comment]
This seems to be the case for a lot of the official tauri plugins, please update install docs to point to the `dev` branch, instead of a non-existent tag :grin:

**Comment by dchicchon** [comment]
Went ahead and made a pr https://github.com/tauri-apps/tauri-plugin-store/pull/110
