### ISSUE TITLE
[opener] One "open" to rule them all

### ISSUE THREAD

**Issue by martpie** [tauri-apps/plugins-workspace#2201]
Would it be possible in the `tauri_plugin_opener` to export a single helper to open any URL/path?

- if path is a valid folder, `revealItemInDir`
- if path is a valid file, `open_path`
- fallback to `open_url`

Why? Because UI components don't need to know about this differtiation

```tsx
type Props = {
  children: string;
  href: string;
};

export default function ExternalButton(props: Props) {
  const openLink = useCallback(
    (e: React.SyntheticEvent) => {
      // props.href need to be handled in some way here, but could be arbitrarily a path, folder or URL
    },
    [props.href],
  );

  return <Button onClick={openLink}>{props.children}</Button>;
}
```

**Comment by martpie** [comment]
In the meantime, here's what I'll do (It's react, but the spirit would be the same with any other UI library:

```tsx
import { openPath, openUrl, revealItemInDir } from '@tauri-apps/plugin-opener';
import { useCallback } from 'react';

export default function useOpener(
  href: string,
  type: 'file' | 'dir' | 'url',
): () => void {
  return useCallback(() => {
    switch (type) {
      case 'dir':
      case 'file':
        revealItemInDir(href);
        break;
      case 'url':
        openUrl(href);
        break;
    }
  }, [href, type]);
}
```

And from my components:

```tsx
type Props = {
  children: string;
  href: string;
  type: 'file' | 'dir' | 'url';
};

export default function ExternalLink(props: Props) {
  const onClick = useOpener(props.href, props.type)

  return (
    <button type="button" onClick={onClick}>
      {props.children}
    </button>
  );
}
```

But I assume some other people may not be able to know in advance what kind of link they are dealinth with.

**Comment by amrbashir** [comment]
I believe this should be done in user code not in the library, because we can't know for sure if you mean to reveal a file in directory, or open said file. We also can't be surer if `C:/User/file` is a Windows path or a weird URL with `C:` as its protocol. These differences that we can't be sure about, made me provide them as separate functions and you (the user) need to decide what you're trying to do.
