### ISSUE TITLE
"decorations: false" Not Working with Specific Identifier When Using Window State Plugin

### ISSUE THREAD

**Issue by project-AI39** [tauri-apps/plugins-workspace#2203]
"decorations: false" Not Working with Specific Identifier When Using Window State Plugin

[Environment Details]
OS: Windows 10.0.26100 x86_64 (X64)
Tauri Version: 2.1.1
Rust Version: 1.82.0
Node.js Version: 22.12.0
npm Version: 10.9.2

[Installed Plugins]
tauri-plugin-window-state: 2.2.0

[Bug Description]
When using the Tauri Window State plugin, the "decorations": false configuration becomes non-functional specifically when the "identifier" is set value like "com.tauri-app.app"

[Reproduction Steps]
Install Tauri 
Project Name: tauri-app  (using default settings)
Identifier: com.tauri-app.app  (using default settings)
Frontend: TypeScript / JavaScript
Package Manager: npm
UI Framework: Solid.js

Add "decorations": false to configuration
Initially works as expected

Install Window State plugin
'npm run tauri add window-state'
"decorations": false no longer effective

Change identifier
"identifier": "com.tauri-app.app" -> "identifier": "test"
"decorations": false works correctly

I am unsure whether this is a bug or an intended feature, but I would appreciate an investigation into the cause and a resolution to the issue.

**Comment by Legend-Master** [comment]
This might not be very intuitive, but window state plugin saves and restores the decoration state by default (it means if you used `decorations: true` the first time and `decorations: false` the second time, the decorations will be restored to true because it's saved in that way), you can disable it through `with_state_flags` though

**Comment by project-AI39** [comment]
>This might not be very intuitive, but window state plugin saves and restores the decoration state by default (it means if you used decorations: true the first time and decorations: false the second time, the decorations will be restored to true because it's saved in that way), you can disable it through with_state_flags though

I investigated the possibility that the window state plugin's default behavior of saving and restoring decoration states might be related to this issue.


1. Create a project
```
irm https://create.tauri.app/ps | iex
```
```
✔ Project name · tauri-app
✔ Identifier · com.tauri-app.app
✔ Choose which language to use for your frontend · TypeScript / JavaScript - (pnpm, yarn, npm, deno, bun)
✔ Choose your package manager · npm
✔ Choose your UI template · Solid - (https://solidjs.com/)
✔ Choose your UI flavor · TypeScript
```
2. Add `"decorations": false` to `tauri.conf.json` to remove the title bar right after creating Tauri project.

3. Set up the project and install the window state plugin
```
cd tauri-app
npm install
npm run tauri add window-state
```
4. Build and run the project for the first time
```
npm run tauri dev
```

5. Since it was the first build, there was no title bar for the window state plugin to restore, and `"decorations": false` was set from the beginning. However, the window still displayed a title bar. Even after closing the app and rebuilding several times, the result remained the same.
6. However, when I changed `"identifier": "com.tauri-app.app"` to `"identifier": "test"` and rebuilt, the title bar disappeared. When I changed it back to `"identifier": "com.tauri-app.app"`, the title bar reappeared.

It seems illogical that the title bar appears and disappears despite having `"decorations": false` set from the beginning. I would appreciate if others could verify if they can reproduce this issue in their environment and provide any insights into what might be causing this unexpected behavior.

**Comment by Legend-Master** [comment]
If you have done this once on your computer before, the state is already stored, maybe clear the data and try again? (seems like you're on Windows, just delete this folder: `%APPDATA%/com.tauri-app.app/`)

**Comment by project-AI39** [comment]
Thank you for helping me resolve the issue! Following your advice to clear the cache and then reinstalling Tauri from the start, the problem was finally solved. For anyone encountering the same issue with window decorations not working as expected with the window-state plugin, try clearing the cache in your %APPDATA%/(your-app-identifier) folder. This solution might work for you as well. Happy coding everyone!
