### ISSUE TITLE
[store] Change the log level to warning

### ISSUE THREAD

**Issue by persiliao** [tauri-apps/plugins-workspace#221]
I believe there are two log level

[here](https://github.com/tauri-apps/tauri-plugin-store/blob/dev/src/lib.rs#L47)
[here](https://github.com/tauri-apps/tauri-plugin-store/blob/dev/src/lib.rs#L343)

The log level here is error, which actually has no effect on usage, which brought me confusion when I first started using it and made me think there were errors all the time, I think it can be changed to warning

**Comment by JonasKruckenberg** [comment]
Agree, it's not an error because we explicitly have a fallback behavior and we notify users about that fallback behavior.
