### ISSUE TITLE
[plugin-fs] Recent update returns UTF8 ArrayBuffer instead of String, Docs lacking

### ISSUE THREAD

**Issue by abarrafo** [tauri-apps/plugins-workspace#2218]
Hey there! It looks like after upgrading from Tauri Plugin FS 2.0.x to 2.2.x, you now need to decode the `readTextFile` output before using it as JSON. In the older version, `readTextFile` returned a string directly, but now it provides an `ArrayBuffer` that needs to be decoded into a string first. Something like this:

```js
  try {
    const resource = await resolveResource("resources/data/genres.json");
    const fileContentBuffer = await readTextFile(resource);
    const decoder = new TextDecoder("utf-8");
    const fileContent = decoder.decode(fileContentBuffer);
    return JSON.parse(fileContent);
  } catch (e) {
    await error(`Failed to load genres: ${e}`);
    return { fictionGenres: {}, nonFictionGenres: {} };
  }
```

This might be an intentional change, but it would definitely be helpful if the official docs were updated to reflect these breaking changes. It’s always good to know about any API adjustments ahead of time, along with updated examples.

As for the warning about `tauri_plugin_shell::Shell::<R>::open` being deprecated, it looks like you’re now supposed to use `tauri-plugin-opener`. It’s a bit frustrating that the docs for `tauri-plugin-opener` aren’t available yet? Ideally, a deprecation should come with updated documentation to guide you on what to use instead. Hopefully this will be addressed soon.

**Comment by abarrafo** [comment]
https://github.com/tauri-apps/plugins-workspace/blob/da64d9b665694f541b1ee2d533535210e118969f/plugins/fs/guest-js/index.ts#L765C1-L781C2 

Hmmm. Something is wonky. Looks like the plugin should be decoding.

**Comment by abarrafo** [comment]
For docs on `opener`. 

They are available here: https://lib.rs/crates/tauri-plugin-opener.

**Comment by abarrafo** [comment]
Closing this as this the fs issues seems related to something else. Im going to do more research to identify the update culprit.

**Comment by FabianLars** [comment]
The fs error means you updated only the rust package but not the J's one. Starting with the plugins' 2.2.0 releases you should keep their rust and js versions in sync for best compatibility.
