### ISSUE TITLE
[store] Please update the readme

### ISSUE THREAD

**Issue by zhaoygcq** [tauri-apps/plugins-workspace#222]
the tag "v0.1.0" is not exist
<img width="679" alt="image" src="https://user-images.githubusercontent.com/33622894/173717277-9732457a-794d-47eb-8cfc-5f9fc4f0cd5b.png">

**Comment by lucasfernog** [comment]
For now you can use the dev branch instead, the plugin will be published soon (maybe over the weekend).

**Comment by goenning** [comment]
just stumbled across this too, might be worth keeping this open for visibility until 0.1.0 is published?
