### ISSUE TITLE
Plugin-FS v2.2.0: readTextFile returns an ArrayBuffer instead of String

### ISSUE THREAD

**Issue by lorenz-misax** [tauri-apps/plugins-workspace#2222]
I recognized that in the newest version of the fs-plugin the following method is returning an ArrayBuffer instead of a string.

```
/**
 * Reads and returns the entire contents of a file as UTF-8 string.
 * @example
 * ```typescript
 * import { readTextFile, BaseDirectory } from '@tauri-apps/plugin-fs';
 * const contents = await readTextFile('app.conf', { baseDir: BaseDirectory.AppConfig });
 * ```
 *
 * @since 2.0.0
 */
declare function readTextFile(path: string | URL, options?: ReadFileOptions): Promise<string>;

```

**Comment by amrbashir** [comment]
please post the output of `tauri info` and make sure all packages are up to date

**Comment by FabianLars** [comment]
This means you updated only the rust package but not the js one. Starting with the plugins' 2.2.0 releases you should keep their rust and js versions in sync for best compatibility.

**Comment by lorenz-misax** [comment]
> This means you updated only the rust package but not the js one. Starting with the plugins' 2.2.0 releases you should keep their rust and js versions in sync for best compatibility.

Yes you are right! My js version was 2.2.0 while my rust version was older.
Setting my rust plugin-fs version to 2.2.0 fixed the problem!
Thanks!
