### ISSUE TITLE
Error : plugin sql not found

### ISSUE THREAD

**Issue by ArbifyFun** [tauri-apps/plugins-workspace#2229]
I have excuted ` pnpm tauri add sql` and `cargo add tauri-plugin-sql --features sqlite`. but i got an error 'plugin sql not found'

[✔] Environment
    - OS: Mac OS 14.6.1 arm64 (X64)
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.83.0 (90b35a623 2024-11-26) (Homebrew)
    ✔ cargo: 1.83.0
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: 
    - node: 18.19.0
    - pnpm: 9.6.0
    - yarn: 1.22.22
    - npm: 10.2.3

[-] Packages
    - tauri 🦀: 2.1.1
    - tauri-build 🦀: 2.0.3
    - wry 🦀: 0.47.2
    - tao 🦀: 0.30.8
    - tauri-cli 🦀: 2.1.0
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli : 2.1.0

[-] Plugins
    - tauri-plugin-log 🦀: 2.2.0
    - @tauri-apps/plugin-log : not installed!
    - tauri-plugin-fs 🦀: 2.2.0
    - @tauri-apps/plugin-fs : not installed!
    - tauri-plugin-sql 🦀: 2.2.0
    - @tauri-apps/plugin-sql : 2.2.0
    - tauri-plugin-http 🦀: 2.2.0
    - @tauri-apps/plugin-http : 2.2.0
    - tauri-plugin-websocket 🦀: 2.2.0
    - @tauri-apps/plugin-websocket : 2.2.0

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../out
    - devUrl: http://localhost:3000/
    - framework: React (Next.js)
    - bundler: Webpack

**Comment by FabianLars** [comment]
This sounds more like an issue with the `tauri add` command, so let's keep it in https://github.com/tauri-apps/tauri/issues/12027 for now.
