### ISSUE TITLE
[store] if I set store location is ".setting." Can I found it and see it ? where is location path?

### ISSUE THREAD

**Issue by awkj** [tauri-apps/plugins-workspace#226]

**Comment by FabianLars** [comment]
Windows: `C:\Users\username\AppData\Roaming\bundle-identifier\.setting`
Linux: `~/.config/bundle-identifier/.setting`
macOS: `~/Library/Application Support/bundle-identifier/.setting` (not 100% sure about that one)

You can get these path in-code via https://tauri.studio/docs/api/js/modules/path/#appdir

**Comment by awkj** [comment]
thanks
