### ISSUE TITLE
[autostart] failed to find tag `tauri-plugin-autostart-v0.1.0`？

### ISSUE THREAD

**Issue by xdewx** [tauri-apps/plugins-workspace#23]
error: failed to get `tauri-plugin-autostart` as a dependency of package `app v0.1.0`

Caused by:
  failed to load source for dependency `tauri-plugin-autostart`

Caused by:
  Unable to update https://github.com/tauri-apps/tauri-plugin-autostart?tag=tauri-plugin-autostart-v0.1.0

Caused by:
  failed to find tag `tauri-plugin-autostart-v0.1.0`

Caused by:
  reference 'refs/remotes/origin/tags/tauri-plugin-autostart-v0.1.0' not found; class=Reference (4); code=NotFound (-3)

**Comment by FabianLars** [comment]
The plugin wasn't released yet. Just remove the `tag` for now.
