### ISSUE TITLE
[window-state] Window always invisible

### ISSUE THREAD

**Issue by goenning** [tauri-apps/plugins-workspace#243]
I don't know how this happened as I can no longer reproduce, but somehow the state stored in disk had `visible = false`. And as per the README, my app also had visible = false. Whenever I tried to open the app, it would never actually show the window, no matter how many times I closed/reopened it.

After deleting the `.window-state` file, everything started working again. I tried multiple times to get into that scenario again, but I couldn't. 

After looking at the code, I wonder if this is causing it:

https://github.com/tauri-apps/tauri-plugin-window-state/blob/2f4cd57b1e7544155484faab769c91c4bf25120e/src/lib.rs#L262-L267

Imagine a scenario where the app is starting but the window is not yet visible. Then for some reason the OS requested the app to be closed or the user intentionally closed it, which triggered that event and saved the visible=false. I tried reproduce that, but also couldn't.

**Comment by goenning** [comment]
Would it be acceptable to change `with_auto_show` to receive an enum: `Always`, `Auto`, `Never`? I'm happy to send a PR

```
/// - `Always`: the window will always be shown, regardless of what's the last store state was
/// - `Auto `: the window will be automatically shown if the last stored state for visibility was `true`
/// - `Never `: the window will not be automatically shown by this plugin
```

**Comment by FabianLars** [comment]
i personally like that idea 👍
