### ISSUE TITLE
[window-state] Closing when Maximized results in fake maximized window

### ISSUE THREAD

**Issue by elibroftw** [tauri-apps/plugins-workspace#249]
after building a release version, I opened the app and maximized it like so

![image](https://user-images.githubusercontent.com/21298211/160223346-85d92925-b080-4ffa-a346-c052e5d4a0fe.png)

I close it, and when I open it I get the image below. Furthermore, the window position saved from the release app affects the dev mode.
![image](https://user-images.githubusercontent.com/21298211/160223364-c3b8c623-9bc4-4e13-85c1-d3f7f7f9b665.png)

**Comment by amrbashir** [comment]
I think we aren't saving maximized state

**Comment by elibroftw** [comment]
I tried the latest commit and it didn't work. The window restores to the top left non-maximized state rather than its maximized state. It's better than previously though.

**Comment by amrbashir** [comment]
thanks for the feedback, pushed a commit to fix that. Run `cargo update` inside `src-tauri` and test again.

**Comment by elibroftw** [comment]
Still does not work. I'm using a83be7ae60356e06f05450a00e55c427b288db59.
Now what happens is that when the app is maximized and re-opened, the window shows up top left for 0.1 seconds, and is noticeably moved to the pre-maximized position.

**Comment by elibroftw** [comment]
Are we sure we can maximize before showing the window? https://github.com/tauri-apps/tauri-plugin-window-state/blob/dev/src/lib.rs#L72 and do we know if maximizing a window even triggers an event in the first place?

**Comment by amrbashir** [comment]
> Still does not work. I'm using https://github.com/tauri-apps/tauri-plugin-window-state/commit/a83be7ae60356e06f05450a00e55c427b288db59.
> Now what happens is that when the app is maximized and re-opened, the window shows up top left for 0.1 seconds, and is noticeably moved to the pre-maximized position.

Are you sure you're using the latest commit? It works fine for me.

> Are we sure we can maximize before showing the window? [dev/src/lib.rs#L72](https://github.com/tauri-apps/tauri-plugin-window-state/blob/dev/src/lib.rs?rgh-link-date=2022-04-04T15%3A30%3A00Z#L72)

yeah

**Comment by elibroftw** [comment]
Well yeah I'm sure. My Cargo.lock has this
```
[[package]]
name = "tauri-plugin-window-state"
version = "0.1.0"
source = "git+https://github.com/tauri-apps/tauri-plugin-window-state?branch=dev#a83be7ae60356e06f05450a00e55c427b288db59"
dependencies = [
 "bincode",
 "serde",
 "serde_json",
 "tauri",
]
```

**Comment by amrbashir** [comment]
here it is working fine using the example in this repo Here is a recoding 
![s](https://user-images.githubusercontent.com/48618675/161582014-b0699250-b726-4573-a308-3bd40ba326f3.gif)
you can see that the second run, it maximized itself because it was maximized in the first run.

Can you make a minimal repro I can test?

**Comment by elibroftw** [comment]
See if you can follow https://github.com/elibroftw/modern-desktop-app-template#instructions

**Comment by amrbashir** [comment]
It works fine.

**Comment by elibroftw** [comment]
Running the debug build works, but the release build is not working

**Comment by elibroftw** [comment]
I'll probably just cargo clean then

**Comment by elibroftw** [comment]
Nope it simply does not work in a release build.

**Comment by amrbashir** [comment]
Can you upload that build?

**Comment by elibroftw** [comment]
https://we.tl/t-UELXwo5D6V

**Comment by amrbashir** [comment]
It works fine. Can you try deleting the file `C:\Users\<your-username>\AppData\Roaming\com.lenerva.r2t2`

**Comment by elibroftw** [comment]
No change
