### ISSUE TITLE
[window-state] On Windows, closing a minimized window causes the app to be stuck in an invalid state

### ISSUE THREAD

**Issue by aschey** [tauri-apps/plugins-workspace#253]
On Windows, minimizing an app causes a `WindowEvent::Resized` event to be fired with `{width: 0, height: 0}` and a `WindowEvent::Moved` event to be fired with `{x: -32000, y: -32000}` (not sure if that's a static value or somehow related to monitor size). If the window is closed while minimized, the plugin persists these values to disk which causes the app to be stuck in an invisible state until the `.window-state` file is deleted. I also tested this on Linux and neither event is fired on minimize so it doesn't cause an issue. I'd be happy to attempt to fix this, but not sure if this is something that should be fixed upstream in Tao. Thanks!

Tauri info:
```
Operating System - Windows, version 10.0.19043 X64
Webview2 - 94.0.992.47

Node.js environment
  Node.js - 16.6.2
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 7.20.3
  yarn - 1.22.11

Rust environment
  rustc - 1.55.0
  cargo - 1.55.0

App directory structure
/node_modules
/public
/src
/src-tauri

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../build
  devPath - http://localhost:3000
  framework - React
```

**Comment by lucasfernog** [comment]
@wusyong @lemarier @amrbashir is the event values here correct? the Moved one seems crazy.

**Comment by amrbashir** [comment]
I haven't tested this before and I couldn't find a clear-cut documentation about this behavior but it seems that Windows will report different position for the minimized state and usually it is offscreen, so I think this is normal behavior on Windows.

As for Linux not firing these events when the window is minimized/maximized, this is an inconsistency and we can and should add the code to fire them but the values might not be similar to those of Windows.

I don't know about macOS behavior though.

The recommendation is to ignore the events when the window is minimzed and not save them.

**Comment by FabianLars** [comment]
whoops, my bad. Closed by accident. I need to be more careful with referencing issues in descriptions :/

**Comment by amrbashir** [comment]
> The recommendation is to ignore the events when the window is minimzed and not save them.

I wasn't aware when I made that comment that we don't provide any way to detect minimized state, so I opened an issue at tao for it  https://github.com/tauri-apps/tao/issues/257. 

I will PR a workaround soon until the above mention issue gets added.

**Comment by aschey** [comment]
Thanks for the fix!
