### ISSUE TITLE
[single-instance] Single Instance Plugin has no User Feedback

### ISSUE THREAD

**Issue by JohannesMerkt** [tauri-apps/plugins-workspace#280]
When the single instance plugin is included into an application, the second instance that you try to launch doesnt start as expected. But there is no user feedback at all. When launching the app literally nothing happens, which could look like the app is broken.

Maybe to eliminate this confusion I would suggest when trying to launch another app putting the first instance in focus / making it visible as top most window. And giving the drawer Icon a notifcation state.

Or triggering a notification / dialog explaining what is going on when trying to launch a second app before closing it.

**Comment by FabianLars** [comment]
Hmm, I totally agree with the issues themselves here! But to be honest I feel like this is not something the plugin should do by itself (think of system-tray only apps for example). Do you think this is something we could solve with examples/docs instead?

**Comment by JohannesMerkt** [comment]
Yea agree it shouldnt be on by default and rather some sort of opt in or do yourself way.

Can the plugin provide a callback function when it closes due to multiple instance?

Or even better can the first instance recieve an event when another instance has been blocked. This way the developer can define how the running instance should behave

I can definetly provide an example when this functionality is there.

I am not so sure however if I am able to understand/extend the plugin

**Comment by amrbashir** [comment]
There is already a callback that is executed after the new instance is closed, see https://github.com/tauri-apps/plugins-workspace/blob/dev/plugins/single-instance/examples/vanilla/src-tauri/src/main.rs#L8-L10 

you can use the first argument which is an `AppHandle` to get the main window of your app and focus it.

```rs
.plugin(tauri_plugin_single_instance::init(|app, argv, cwd| {
    let window = app.get_window("main").unwrap();
    window.set_focus();
    window.request_user_attention(Some(UserAttentionType::Informational));
}))
```

**Comment by jetli** [comment]
@amrbashir Hi, with tauri 1.5, the callback is not executed after the new instance is closed, for example:
```rust
.plugin(tauri_plugin_single_instance::init(|app, argv, cwd| {
            println!("{}, {argv:?}, {cwd}", app.package_info().name);

            app.emit_all("single-instance", Payload { args: argv, cwd }).unwrap();
        }))
```
when I build with --debug, nothing is printed on console. I believe this plugin works with previous versions, I don't know when it breaks.

**Comment by amrbashir** [comment]
@jetli no need to post in multiple issues, will keep the discussion in https://github.com/tauri-apps/plugins-workspace/issues/648

**Comment by Smart-yang** [comment]
@amrbashir Install the exe file automatically for the first time, click on the shortcut, single_ Instance does not have a callback, closing exe and reopening shortcut is sufficient to solve the first single issue_ Instance callback issue No, thank you

**Comment by naman-crabnebula** [comment]
Hi @JohannesMerkt ,

I mentioned this on the Tauri 2.0 ( beta ) docs. See https://github.com/tauri-apps/tauri-docs/pull/1931

I hope this will provide users more clarity over these.
