### ISSUE TITLE
[single-instance] Will single-instance support MacOS in the future?

### ISSUE THREAD

**Issue by Pylogmon** [tauri-apps/plugins-workspace#287]

**Comment by FabianLars** [comment]
Probablyyy not since apps on macos are single instance by default (unless started manually in the terminal). If you do have a use-case where you need the plugin on top of macos' default behavior we'd like to hear about it :)

**Comment by Pylogmon** [comment]
As you said, I need to start it from the terminal. I have implemented the function of calling the software from the terminal when the software is running. I can get the command line parameters through this plugin, so that my software can be called through other software (such as popclip). It works well under Windows and Linux, but this plugin does not support macos。

**Comment by FabianLars** [comment]
alright, understandable use-case, thanks! Still no promises that we will work on it anytime soon but i'll bring it up in a few conversations and see what happens.

p.s. for anyone interested, community contributions are always welcome!
