### ISSUE TITLE
[sql] Support sqlite mysql feature simultaneously

### ISSUE THREAD

**Issue by yipjunkai** [tauri-apps/plugins-workspace#288]
I have a usecase where my app swaps between sqlite and mysql, would this be possible under the same plugin?

**Comment by FabianLars** [comment]
The plugin currently doesn't support this use-case, but it _should_ be possible to rewrite it to make it possible. It likely won't be a small change though so it may take some time to add it.

**Comment by staaph** [comment]
+1, postgres & mysql

**Comment by LePichu** [comment]
+1

**Comment by NeboCode** [comment]
+1 need this

**Comment by FabianLars** [comment]
whoops, forgot to link this in https://github.com/tauri-apps/plugins-workspace/pull/1838
