### ISSUE TITLE
[store] Where does the store plugin store the files?

### ISSUE THREAD

**Issue by HuakunShen** [tauri-apps/plugins-workspace#298]
I am wondering where I can find the file of data persistence in the file system for debugging purpose.

Cannot seem to find it in the source code.

Could someone point me to the source code and path on file system?

Thank You!

**Comment by FabianLars** [comment]
For some reason it changed from app_data from last time we talked about this (https://github.com/tauri-apps/plugins-workspace/issues/92#issuecomment-1383126508) to [app_data_dir](https://docs.rs/tauri/latest/tauri/api/path/fn.app_data_dir.html) (shouldn't have happened imo), this only makes a different on Linux though.

**Comment by FabianLars** [comment]
Since you asked for the relevant code, it's here https://github.com/tauri-apps/plugins-workspace/blob/dev/plugins/store/src/store.rs#L182 and here https://github.com/tauri-apps/plugins-workspace/blob/dev/plugins/store/src/store.rs#L197
