### ISSUE TITLE
Add ability to get __filename and __dirname like in Nodejs

### ISSUE THREAD

**Issue by Aviv-Frenkel** [tauri-apps/plugins-workspace#300]
I would like to be able to get the file's name and dir name like __filename and __dirname in Nodejs.
I don't know if this is realistic but this would help me a lot.

**Comment by FabianLars** [comment]
Could you provide some example (at least in pseudo code)? I don't see what the use-cases would look like to be honest.

Also just to be sure, do you need that at build time or also at runtime?

**Comment by lucasfernog** [comment]
The files are embedded in the binary, not on the file system.
