### ISSUE TITLE
[positioner] Unable to set x, y position using the positioner plugin

### ISSUE THREAD

**Issue by billyjacoby** [tauri-apps/plugins-workspace#301]
I'm trying to build an app that will open a window at the location of the cursor when an event is fired.

I can't quite seem to find a method on `tauri_plugin_positioner::move_window()` to allow me to do this as it expects an enum of type `Position`.

If I'm overlooking something simple please just point me in the right direction as I'm new to Rust

**Comment by FabianLars** [comment]
I _think_ this is outside of the plugin's scope. It's supposed to make it easier to move the window to _known_ locations, like monitor corners and the systray location.

For arbitrary x,y values you can use the standard window / windowbuilder position apis https://docs.rs/tauri/latest/tauri/window/struct.Window.html#method.set_position / https://docs.rs/tauri/latest/tauri/window/struct.WindowBuilder.html#method.position
