### ISSUE TITLE
tauri-plugin-store-api does not work with ts

### ISSUE THREAD

**Issue by DavidSichau** [tauri-apps/plugins-workspace#321]
It seems that `tauri-plugin-store-api` does not specify the correct path for the types:

in package.json the path is:
```
"types": "./dist-js/index.d.ts",
```
However the correct path would be:    
```
"types": "./dist-js/dist/index.d.ts",
```

**Comment by FabianLars** [comment]
Looks like i messed up yesterday. the types are not supposed to end up in the dist subdir, i'm going to take a look what i did wrong, thanks for the report.
