### ISSUE TITLE
[websocket] When using the `connect` command, it will slightly block the program

### ISSUE THREAD

**Issue by A-kirami** [tauri-apps/plugins-workspace#336]
When it is connected, the front end will be blocked, and in the case of automatic reconnection, this will become very bad, and the front end will frequently get stuck.

I think the problem lies here:
https://github.com/tauri-apps/plugins-workspace/blob/dev/plugins/websocket/src/lib.rs#L89-L90

**Comment by FabianLars** [comment]
Thanks for the report! Can you try the `ws/blocking` branch and see if it works better? To do this, just replace `branch = "dev"` with `branch = "ws/blocking"` in Cargo.toml (you may have to run `cargo update` in your src-tauri dir afterwards)

**Comment by A-kirami** [comment]
> Thanks for the report! Can you try the `ws/blocking` branch and see if it works better? To do this, just replace `branch = "dev"` with `branch = "ws/blocking"` in Cargo.toml (you may have to run `cargo update` in your src-tauri dir afterwards)

Thanks, after using the `ws/blocking` branch, this issue has been resolved.
