### ISSUE TITLE
`window-state`: Opt out of visibility visibility state

### ISSUE THREAD

**Issue by probablykasper** [tauri-apps/plugins-workspace#344]
Would like to be able to *always* keep my window hidden when the app opens. That would mean the plugin shouldn't auto-show any windows / restore window visibility state.

Ideally the `visible` state wouldn't be stored at all

**Comment by amrbashir** [comment]
This already implemented, 

```rs
use tauri_plugin_window_state::StateFlags;
tauri::Builder::default()
		.plugin(tauri_plugin_window_state::Builder::default().with_state_flags(StateFlags::all() & !StateFlags::VISIBLE).build())
        .run(tauri::generate_context!())
        .expect("error while running tauri application")
```

**Comment by probablykasper** [comment]
Oh nice, any reason it's not released yet @amrbashir?

**Comment by amr-crabnebula** [comment]
the plugins release workflow has not been sorted out yet but you can use the `v1` branch of this repo for now

**Comment by amrbashir** [comment]
the plugins release workflow has not been sorted out yet but you can use the `v1` branch of this repo for now
