### ISSUE TITLE
Move PRs

### ISSUE THREAD

**Issue by JonasKruckenberg** [tauri-apps/plugins-workspace#37]
- [x] https://github.com/tauri-apps/tauri-plugin-upload/pull/61
- [x] https://github.com/tauri-apps/tauri-plugin-stronghold/pull/75
- [x] https://github.com/tauri-apps/tauri-plugin-stronghold/pull/69
- [ ] https://github.com/tauri-apps/tauri-plugin-stronghold/pull/59
- [x] https://github.com/tauri-apps/tauri-plugin-stronghold/pull/46
- [x] https://github.com/tauri-apps/tauri-plugin-sql/pull/166
- [x] https://github.com/tauri-apps/tauri-plugin-log/pull/90
- [x] https://github.com/tauri-apps/tauri-plugin-store/pull/133
- [x] https://github.com/tauri-apps/tauri-plugin-persisted-scope/pull/9

**Comment by Beanow** [comment]
Yeah so there's no special admin feature to move PRs. A co-author new commit as you've done is the way to go. Let me know if there's any blockers though :smile:

**Comment by JonasKruckenberg** [comment]
I think this is done now
