### ISSUE TITLE
[feat] withGlobalTauri for plugins

### ISSUE THREAD

**Issue by ManeraKai** [tauri-apps/plugins-workspace#380]
If I want to access [tauri fs API](https://tauri.app/v1/api/js/fs) through Vanilla JS, I would use `window.__TAURI__.fs`, by enabling [withGlobalTauri](https://tauri.app/v1/api/config/#buildconfig.withglobaltauri).
Though I'm also using [fs-watch](https://github.com/tauri-apps/plugins-workspace/tree/v1/plugins/fs-watch) plugin, how would I use it through the `window.__TAURI__` variable?

**Comment by FabianLars** [comment]
I marked this as a feature request since we don't have this implemented. In the meantime you could download this file <https://github.com/tauri-apps/tauri-plugin-fs-watch/blob/v1/dist-js/index.min.js> into your project.

**Comment by FabianLars** [comment]
This was implemented for the v2 versions of the plugins and i doubt we will backport that change to the v1 ones. Since there's a workaround mentioned above i'm going to close this issue. Thanks for the request :)
