### ISSUE TITLE
[window-state] Forces window decorations to show

### ISSUE THREAD

**Issue by DarkPreacher** [tauri-apps/plugins-workspace#396]
Enabled plugin `window-state` forces window `decorations` to show, then it is set to `false` in `tauri.conf.json`
I'm on Windows 10 22H2.

**Comment by FabianLars** [comment]
I think this is the same as https://github.com/tauri-apps/plugins-workspace/issues/254. For undecorated you have to save the state when the window closes yourself with the new js apis introduced in https://github.com/tauri-apps/plugins-workspace/pull/309.

you'd basically call the example from the readme:
```ts
import { saveWindowState, StateFlags } from "tauri-plugin-window-state-api";

saveWindowState(StateFlags.ALL);
```
wherever you call window.close() or app.exit()

**Comment by FabianLars** [comment]
Actually, that may not fully explain it if you already set it to false in tauri.conf.json. Can you show the code where you are restoring the window state?

Edit: What i think is happening here is that the saved state ondisk is "outdated" from a time where you had decorations enabled.

**Comment by DarkPreacher** [comment]
Oh, you are right! I deleted `.window-state` and decorations gone, after restart, thank you!
