### ISSUE TITLE
[localhost] Support HTTP Methods?

### ISSUE THREAD

**Issue by evbo** [tauri-apps/plugins-workspace#4]
I'm very thankful for this plugin! Rather than roll my own, I could see one possible enhancement being support for HTTP methods?

If I'm reading the `lib.rs` correctly, currently the path routes the request to a given Tauri command. What if we enhanced this slightly to also route based on HTTP method as is usually done?

The benefit is of course security for whatever client is making the request ("security first" as they say...)

I know this one is hot-off-the-press, so of course this might even be a feature you're already planning and that's good too!

**Comment by lucasfernog** [comment]
Sorry for the lack of documentation, but this plugin currently serves as a replacement for the tauri:// protocol used by the framework, exposing a localhost server that just serves the app assets. I think what you want is something for another plugin, maybe tauri-plugin-http.

**Comment by xiaowang-web** [comment]
Can this local plug-in remove the windows online SSL Protocol? The EXE package after cargo Tauri build supports HTTP and WS protocols

**Comment by Richyeoh** [comment]
> 这个本地插件可以去掉windows online SSL Protocol吗？cargo Tauri 构建后的 EXE 包支持 HTTP 和 WS 协议
Can this local plug-in remove the windows online SSL Protocol? The EXE package after cargo Tauri build supports HTTP and WS protocols
@lucasfernog It that Ok?
