### ISSUE TITLE
[window-state] The app freezes right after the window opens

### ISSUE THREAD

**Issue by tksoft** [tauri-apps/plugins-workspace#40]
On Windows, the app freezes right after the window opens when the window's visible property is set to false and .window-state file doesn't exist. If you set the visible property to true, this problem doesn't occur. Once .window-state file is created, it doens't happen even if the visible property is false.

**Comment by tksoft** [comment]
Isn't this problem related to tauri-plugin-window-state?

**Comment by FabianLars** [comment]
it is, yes. that's why it has `[window-state]` in its title. All plugins now live in this repo, but we still need a bit more time to set everything up so the other repos are still "writable" in the sense that people can open issues etc

**Comment by tksoft** [comment]
ok. thank you.

**Comment by FabianLars** [comment]
This seems to work fine in the latest versions. Please reach out if you still encounter this issue.
