### ISSUE TITLE
[log] Log message is coming as [2022-12-28][08:01:34][Error][INFO] Mounting wim file. Whether its info,trace or anything.[Error] is common

### ISSUE THREAD

**Issue by Shivang-idrive** [tauri-apps/plugins-workspace#41]
How to get rid of [Error] from log message

**Comment by HarshilSharaf** [comment]
Hi, i am also facing this issue while using this plugin. Any updates on the fix?

**Comment by Shivang-idrive** [comment]
out.finish(format_args!(
                        "{}[{}][{}]",
                        time::OffsetDateTime::now_utc().format(&format).unwrap(),
                        record.level(),
                        message
                    ))

In format_args put "{}[{}][{}]"

**Comment by Shivang-idrive** [comment]
> Hi, i am also facing this issue while using this plugin. Any updates on the fix?
out.finish(format_args!(
"{}[{}][{}]",
time::OffsetDateTime::now_utc().format(&format).unwrap(),
record.level(),
message
))

In format_args put "{}[{}][{}]"

**Comment by Shivang-idrive** [comment]
> Hi, i am also facing this issue while using this plugin. Any updates on the fix?


out.finish(format_args!(
"{}[{}][{}]",
time::OffsetDateTime::now_utc().format(&format).unwrap(),
record.level(),
message
))

In format_args put "{}[{}][{}]"

**Comment by HarshilSharaf** [comment]
Hi @FabianLars , even though this is marked as completed i m still facing this issue.
I've tried after running `cargo update` too.
Am i missing something here?

**Comment by FabianLars** [comment]
You must update the javascript dependency (i think you just re-run the install command from the readme for that?)

**Comment by HarshilSharaf** [comment]
> You must update the javascript dependency (i think you just re-run the install command from the readme for that?)

Yes, i did that too but didn't work.
Can you please verify the same?

@FabianLars  Does @Shivang-idrive's suggestion should work?

**Comment by FabianLars** [comment]
> Can you please verify the same?

Yep, works fine on my end:
![grafik](https://user-images.githubusercontent.com/30730186/235366027-c2d9e121-ee28-4b52-b261-430aab5f26a8.png)

(`webview::unknown` is what used to be `Error`)

> `@FabianLars` Does `@Shivang-idrive`'s suggestion should work?

Depends of your goal, if you completely want to remove the target/location (in my screenshot it's `webview::unknown` and `mio::poll` for example. It's trying to show you where the error happened), then yes. If you want to keep that information then no.

**Comment by HarshilSharaf** [comment]
![image](https://user-images.githubusercontent.com/62461329/235366234-6a8422ce-0d6f-4440-a621-b89ec212e84f.png)
i am still getting this

**Comment by FabianLars** [comment]
Hmm, that means that neither the rust side and javascript side was updated. If the javascript dependency was update it wouldn't show `Error` and if the rust side was updated it would be `[INFO][Error]` not `[Error][INFO]` 🤔 

Are you sure it's the correct file? Are you using the plugin from the dev branches?

**Comment by HarshilSharaf** [comment]
> Are you sure it's the correct file? Are you using the plugin from the dev branches?

Yes i m using the correct branches

**Comment by HarshilSharaf** [comment]
@FabianLars , i've made a clean install of this plugin and now it is showing `[INFO][Error]`.
But i am confused that why it is still showing `[Error]`...doesn't this fix should remove the `[Error]` from `info()` method

**Comment by FabianLars** [comment]
Can you delete your node_modules folder and re-install?

**Comment by HarshilSharaf** [comment]
> 



> Can you delete your node_modules folder and re-install?

Nope didn't worked out
![image](https://user-images.githubusercontent.com/62461329/235368670-30fad920-8f2d-47d8-a5f5-726ffe94b4ac.png)


This is in  my package.json
![image](https://user-images.githubusercontent.com/62461329/235368753-6cfed44c-af0a-4e57-b368-2996fdb80cba.png)

And this in my package-lock.json
![image](https://user-images.githubusercontent.com/62461329/235368790-2ce74e94-866c-4a4c-82f6-95044f9fa095.png)

**Comment by FabianLars** [comment]
I have no idea what could cause this then. The commit your lock file points to is indeed the correct one: https://github.com/tauri-apps/tauri-plugin-log/commit/be811332676ff73e1e891f31ce3de8d447fdf07e 🤔

**Comment by HarshilSharaf** [comment]
> I have no idea what could cause this then. The commit your lock file points to is indeed the correct one: [tauri-apps/tauri-plugin-log@be81133](https://github.com/tauri-apps/tauri-plugin-log/commit/be811332676ff73e1e891f31ce3de8d447fdf07e) 🤔

I've deleted the whole project folder and cloned it again. It worked though✌
