### ISSUE TITLE
[authenticator] tauri-plugin-authenticator depends on u2f, which might break

### ISSUE THREAD

**Issue by djc** [tauri-apps/plugins-workspace#411]
I noticed that tauri-plugin-authenticator recently appeared on crates.io. Is this code actively being developed/used? It depends on the u2f crate, which itself doesn't seem to be getting any more development. I am the lead maintainer for chrono and we're considering making some [changes](https://github.com/chronotope/chrono/pull/1095) that might break the 0.2 version of the u2f crate. Because tauri-plugin-authenticator recently appeared on crates.io (it looks like this might have been due to #402?) I was worried that this code is being actively developed, but based on this repository's history, it doesn't look like that's the case.

**Comment by FabianLars** [comment]
actively developed? No
used? Yes. Plugins for Tauri v1 are only available via git and we were only able to publish v2 plugins really recently as you noticed, so this plugin never popped up on crates.io before.

I'll keep an eye on the u2f PR you guys opened. If it won't get merged, we will think of another way (forking it, pinning chrono, rewriting the plugin, deprecating the plugin, or whatever else) so as far as i am concerned the plugin should not be a blocker for the chrono change.
That said, huge thanks for reaching out to us!!

**Comment by djc** [comment]
@FabianLars thanks for the prompt response!

**Comment by Morgbn** [comment]
Hello, any news here?
I'm trying to use the authenticator plugin, but I can't build the app because u2f compilation fails (mismatched types: expected `time::Duration`, found `chrono::Duration`)
How to solve the problem?  Is there a workaround?

**Comment by FabianLars** [comment]
For now it should be enough to add this to the dependencies in your Cargo.toml file
```toml
chrono = "<=0.4.29"
```

We're still a bit unsure what to do with the plugin because we're unhappy with it's current state in general. As a short term solution we may just add that to the readme too. In the longer term we (or someone from the community) can give it the love it deserves and rewrite it, probably using 0.4 of https://crates.io/crates/authenticator
