### ISSUE TITLE
[plugin-localhost] Display duplicate dialogs when use plugin-localhost

### ISSUE THREAD

**Issue by xiaominglee4github** [tauri-apps/plugins-workspace#420]
I have integrated the `plugin-localhost` to my project(React) on windows as the [Usage](https://github.com/tauri-apps/plugins-workspace/tree/v1/plugins/localhost#usage) said. But `WindowLabelAlreadyExists` error will occurs. Then I changed the name `main`  to another one. The error disappeared. But two duplicate dialogs will be shown. Anybody can help me? thanks

**Comment by forestsource** [comment]
@xiaominglee4github 
Did you solve this problem?
If so, how did you correct it?

I found a document: https://github.com/tauri-apps/plugins-workspace/issues/160#issuecomment-1431290561
