### ISSUE TITLE
[global-shortcut] Return value from isRegistered seems incorrect

### ISSUE THREAD

**Issue by austenc** [tauri-apps/plugins-workspace#430]
When using the latest 2.0.0-alpha, the `global-shortcut` plugin doesn't seem to return the correct value from `is_registered`. 
It seems like the problem is on the Rust side of the equation. The JS side just invokes the rust `is_registered` method, but I can't get it to work from either end. 

Here's the code:
```js
let theShortcut = 'CommandOrControl+Shift+J'
register(theShortcut, async () => {
  // do stuff
})

// shows false
console.log('Exists:', await isRegistered(theShortcut))
console.log(await invoke('test_rust'))
```

Rust side:
```rs
#[tauri::command]
fn test_rust(app_handle: tauri::AppHandle) -> bool {
    return app_handle
        .global_shortcut()
        .is_registered("CommandOrCtrl+Shift+J");
}
```

**Comment by amrbashir** [comment]
run `cargo update` in `src-tauri` and it should be fixed

**Comment by austenc** [comment]
Thank you so much @amrbashir !
