### ISSUE TITLE
[window-state] JS api should await promise in saveWindowState

### ISSUE THREAD

**Issue by ahodesuka** [tauri-apps/plugins-workspace#432]
The main use case for this API, I assume, is to call `saveWindowState` before closing the window via `appWindow.close`.
In it's current state this does not work because the window is closed before the state is actually updated and saved, on my hardware at least.
The other functions in the API should probably be awaited as well.

~~On a side note exposing the `window.update_state` function through the API would allow the user to mimic what the plugin does on the `onCloseRequested` event, and prevent saving all window states when one window is closed.
Again this invoke call would have to be awaited in this case to work correctly.~~
After looking more at the plugin this would require a bit of a refactor.

This whole issue still stems from the fact that `appWindow.close` does not invoke the `onCloseRequested` event on the window. (tauri-apps/tauri#5288)

**Comment by FabianLars** [comment]
Thanks for the report :)

> On a side note exposing the window.update_state function through the API would allow the user to mimic what the plugin does on the onCloseRequested event, and prevent saving all window states when one window is closed.

How so (genuine question)? From what i can see, what the plugin does on close is to call save_window_state (which uses update_state internally) which is what the saveWindowState function does too.

Did you test if adding await actually fixes the issues you're having? Because from the usage of this function i've seen so far it seemed to work as-is (we should add the await anyway)

**Comment by ahodesuka** [comment]
>How so (genuine question)? From what i can see, what the plugin does on close is to call save_window_state (which uses update_state internally) which is what the saveWindowState function does too.

It's a bit of a premature optimization, but in my case it causes 2 disk writes, one when you call the `saveWindowState` and another one when the plugins `Exit` event handler fires.

>Did you test if adding await actually fixes the issues you're having? Because from the usage of this function i've seen so far it seemed to work as-is (we should add the await anyway)

Yes, albeit I didn't modify the plugin, but I mimicked what it does whilst adding an `await`.
