### ISSUE TITLE
[fs-watch] Usage not updated

### ISSUE THREAD

**Issue by NaokiM03** [tauri-apps/plugins-workspace#450]
Hi.

I noticed that the Usage in the README has not been updated.
The following pull requests are related.
https://github.com/tauri-apps/plugins-workspace/pull/71

```diff
import { watch, watchImmediate } from "tauri-plugin-fs-watch-api";

// can also watch an array of paths
const stopWatching = await watch(
  "/path/to/something",
  (event) => {
-    const { type, payload } = event;
+    const { kind, path } = event;
  },
  { recursive: true }
);

const stopRawWatcher = await watchImmediate(
  ["/path/a", "/path/b"],
  (event) => {
-    const { path, operation, cookie } = event;
+    const { type, paths, attrs } = event;
  },
  {}
);
```

**Comment by FabianLars** [comment]
Thanks for the extensive report! Would you mind opening a PR for it? :) 
(since it's a readme change you can just use github's web ui to edit it so you don't have to setup commit signing)

**Comment by NaokiM03** [comment]
@FabianLars 
Created. Thanks for the response.
https://github.com/tauri-apps/plugins-workspace/pull/451
