### ISSUE TITLE
[sql] integer columns for postgresql return null

### ISSUE THREAD

**Issue by jeffshadap** [tauri-apps/plugins-workspace#462]
select integer_value from mytable limit 1;

returns
 [
    {
        "integer_value": **null**
    }
]

The Setup:
-PostgreSQL 14.2, compiled by Visual C++ build 1914, 64-bit
-rustc 1.70.0 (90c541806 2023-05-31)
-tauri 1.4

**Comment by FabianLars** [comment]
thanks for the report. Do you have an example sql statement (the `create table ...` thingy) or something which i can use to test this?

**Comment by CursedMun** [comment]
@FabianLars Hello, faced the same issue today, here is some data to play around


Create Table: `CREATE TABLE IF NOT EXISTS passwords (id int4 PRIMARY KEY NOT NULL,name varchar  NOT NULL,password varchar  NOT NULL,tags varchar  ,createdAt timestamptz  NOT NULL,updatedAt timestamptz  NOT NULL);`


Insert Data: `INSERT INTO passwords (\"id\",\"name\",\"password\",\"tags\",\"createdAt\",\"updatedAt\") VALUES ('1','test','test','test1,test2','2023-08-12T03:40:03.520Z','2023-08-12T03:40:03.520Z'),('2','test2','test2','test3,test2','2023-08-12T03:40:03.520Z','2023-08-12T03:40:03.520Z'),('3','test3','test3','test5,test4','2023-08-12T03:40:03.520Z','2023-08-12T03:40:03.520Z');
`

Select: `SELECT "passwords"."id" FROM passwords ;`

**Comment by CursedMun** [comment]
@jeffshadap An temporary solutions would be cast it to varchar like so
`Select id::varchar from ...`

**Comment by jeffshadap** [comment]
> @jeffshadap An temporary solutions would be cast it to varchar like so `Select id::varchar from ...`

Thanks
