### ISSUE TITLE
plugin store not found in android

### ISSUE THREAD

**Issue by Tlntin** [tauri-apps/plugins-workspace#465]
i add `"@tauri-apps/plugin-fs": "github:tauri-apps/tauri-plugin-fs#v2"`,
    `"@tauri-apps/plugin-store": "github:tauri-apps/tauri-plugin-store#v2",` in package.json
and add `#tauri-plugin-fs = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v2" }` and `tauri-plugin-store = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v2" }` in Cargo.toml

when I build windows, it works well.
but when I build Android with use `pnpm tauri android dev --release`, andorid show `plugin store not found` in localhost.

plugin store not found

**Comment by Tlntin** [comment]
I solve it, is my problem.

**Comment by ildella** [comment]
@Tlntin I've having the same problem with `dialog` and `fs` plugin. What was wrong with your config? 
Thanks.
