### ISSUE TITLE
[single-instance] Allow multiple instances for semver incompatible versions

### ISSUE THREAD

**Issue by matthme** [tauri-apps/plugins-workspace#494]
At least in my use case, versions that are incompatible according to SemVer are supposed to be able to run alongside each other, while versions that are compatible according to SemVer shouldn't. I *think* this logic makes sense in general, beyond my use case.

As I understand, on macOS there is a "single-instance-policy" in general, so I'm not sure whether it's possible to still allow
running multiple, SemVer-incompatible instances alongside each other by modyfing this plugin.

**Comment by matthme** [comment]
I created a draft modification of the single-instance plugin [here](https://github.com/tauri-apps/plugins-workspace/compare/v1...matthme:plugins-workspace:single-instance-semver) (tested on Linux but not on Windows). I'm happy to make a PR if this looks reasonable and there is general agreement that the semver logic is desired. Otherwise one may add it behind a boolean flag or similar to have it be optional.

**Comment by FabianLars** [comment]
imo this could be a nice addition, though it should be behind a non-default feature flag.

cc @amrbashir

**Comment by amrbashir** [comment]
yeah sure, let's see a PR, I don't mind it to be the default either.
