### ISSUE TITLE
[positioner] no variant or associated item named `TrayCenter` found for enum `tauri_plugin_positioner::Position` in the current scope

### ISSUE THREAD

**Issue by boguz** [tauri-apps/plugins-workspace#5]
I am trying to center a tauri app to the tray icon. Someone suggested i use the `tauri-plugin-positioner` plugin, and it does seem like a good solution.

I have followed the instructions on the readme file to use it with just rust, but when i run `npm run tauri dev` i get the following error

![image](https://user-images.githubusercontent.com/15846102/195976720-4e4d6cc4-c789-476b-9492-af4f6435a63e.png)

If i use `let _ = win.move_window(Position::TopCenter);` or `let _ = win.move_window(Position::TopRight);` they all work without problems. But when i use one of the `Tray...` positions (like `Position::TrayCenter`) then i get the error.

This is my main.rs
```
#![cfg_attr(
    all(not(debug_assertions), target_os = "windows"),
    windows_subsystem = "windows"
)]

use tauri::{CustomMenuItem, SystemTray, SystemTrayMenu, SystemTrayMenuItem, SystemTrayEvent};
use tauri::Manager;
use tauri_plugin_positioner::{WindowExt, Position};

fn main() {
    let quit = CustomMenuItem::new("quit".to_string(), "Quit");
    let hide = CustomMenuItem::new("hide".to_string(), "Hide");

    let tray_menu = SystemTrayMenu::new()
        .add_item(quit)
        .add_native_item(SystemTrayMenuItem::Separator)
        .add_item(hide);
    let tray = SystemTray::new().with_menu(tray_menu);

    tauri::Builder::default()
        .setup(|app| {
            let win = app.get_window("main").unwrap();
            let _ = win.move_window(Position::TrayCenter);
            Ok(())
        })
        .system_tray(tray)
        .on_system_tray_event(|app, event| match event {
            SystemTrayEvent::LeftClick {
                position: _,
                size: _,
                ..
            } => {
                println!("system tray received left click");
            }
            SystemTrayEvent::RightClick {
                position: _,
                size: _,
                ..
            } => {
                println!("system tray received right click")
            }
            SystemTrayEvent::MenuItemClick { id, .. } => {
                let item_handle = app.tray_handle().get_item(&id);
                match id.as_str() {
                    "quit" => {
                        std::process::exit(0);
                    }
                    "hide" => {
                        println!("Clicked the test menu item");
                    }
                    _ => {}
                }
            }
            _ => {}
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
```

Not sure if this is important, but this is the output of `npm run tauri info`
```
Environment
  › OS: Mac OS 12.4.0 X64
  › Node.js: 16.14.0
  › npm: 8.3.1
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.64.0
  › cargo: 1.64.0
  › Rust toolchain: stable-aarch64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.1.1
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.1.1,
  › tauri-build [RUST]: 1.1.1,
  › tao [RUST]: 0.14.0,
  › wry [RUST]: 0.21.1,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:5173/

App directory structure
  ├─ types
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ src-tauri
  └─ src
```

This is my first time working with Rust, so i am sorry if this is a problem on how i am doing it, instead of a problem with the library. But maybe better safe than sorry...

**Comment by JonasKruckenberg** [comment]
Tray-relative positions are gated behind a feature flag so people that haven't enabled the system tray for their Tauri app don't have to pay the price of the systray positing logic.

Just change this line from the docs:
```toml
[dependencies]
tauri-plugin-positioner = "1.0"
```
To this:
```toml
[dependencies]
tauri-plugin-positioner = { version = "1.0", features = ["system-tray"] }
```
And everything should work as expected.

This should be clearer in the Readme I agree with you, will fix that asap.

**Comment by boguz** [comment]
@JonasKruckenberg Thank you for your quick answer!

Having it behind a flag seems like a good idea.

Unfortunately, when i make the change you suggested i then get the following error:
```
thread 'main' panicked at 'state() called before manage() for given type', /Users/myName/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-1.1.1/src/lib.rs:749:8
```

and this happens even if i choose for instance `Position::topRight`

**Comment by JonasKruckenberg** [comment]
Ahh yes, there was another reason why system-tray position is not enabled by default. Due to a limitation in Tauri, you currently have to do this (snippet from the example app):

https://github.com/JonasKruckenberg/tauri-plugin-positioner/blob/main/examples/svelte-app/src-tauri/src/main.rs#L36-L37

(`on_tray_event()` here comes from `tauri_plugin_positioner::on_tray_event()`)

This should be documented too ofc.

**Comment by boguz** [comment]
Ah, ok, thank you.

I have tried it, and it seems to kind of work.
The problem is, than when i must click twice on `TrayCenter` before it gets the correct position.
After the 1st click it gets kind of "top centered on the page". And on the 2nd `TrayCenter` item click it gets the correct position.

So, there isn't really an option to set the position when the app starts, just on events?

**Comment by JonasKruckenberg** [comment]
wut

Edit: oooooh @Beanow maybe we do need to go through the commit messages after all

**Comment by Beanow** [comment]
Oh dear `fixes` / `closes` references? I didn't think of that, marvelous :joy:

**Comment by JonasKruckenberg** [comment]
> Oh dear `fixes` / `closes` references? I didn't think of that, marvelous 😂

yup

**Comment by FabianLars** [comment]
> So, there isn't really an option to set the position when the app starts, just on events?

I spent some time trying to find a way to get the tray position without relying on events but couldn't find anything good.

(In theory i think we could get a hwnd to the systemtray and _maybe_ use that to get a rough position but that feels too hacky and unreliable imo, and no way that macos has something similar)

Going to close this for now but i'm open to reconsider this when somebody finds a way to implement this or finds a different (popular) gui framework that does support.

**Comment by luis-szn** [comment]
To fix it, do the [@JonasKruckenberg suggest](https://github.com/tauri-apps/plugins-workspace/issues/5#issuecomment-1351988335) and add this lines after  `tauri::Builder::default()`:

```
.plugin(tauri_plugin_positioner::init())
.on_system_tray_event(|app, event| {
      tauri_plugin_positioner::on_tray_event(app, &event);
   })
```


Expanded snippet:


```
use tauri::Manager;
use tauri::{CustomMenuItem, SystemTray, SystemTrayMenu, SystemTrayEvent, SystemTrayMenuItem};
use tauri_plugin_positioner::{WindowExt, Position};

fn main() {

  let tray_menu = SystemTrayMenu::new();

  let system_tray = SystemTray::new().with_menu(tray_menu).with_title("mementu");
  
  tauri::Builder::default()
    .plugin(tauri_plugin_positioner::init())
    .on_system_tray_event(|app, event| {
      tauri_plugin_positioner::on_tray_event(app, &event);
   })

    .system_tray(system_tray)
    
    [...]
```
