### ISSUE TITLE
[window-state] add group function

### ISSUE THREAD

**Issue by a1156883061** [tauri-apps/plugins-workspace#507]
I want to save window state by group.
For example, the main window save to main group, and other window save to child group.
I expected such api: 
`add_group("main", "main")`
`add_group("child", "child")`
first param is group name, and second is match rule.
while window label contain `main`, save window state to main group, and while window label contain `child`, save window state to child group.
I think it will be very helpful if we can save state by group

**Comment by amrbashir** [comment]
Could you give more info about your use-case? I don't see how groups can be helpful.

**Comment by a1156883061** [comment]
For Example, a comic reader app, it loads comic list in main window, and open comic in reader window, and there could be multiple reader window.
I expect the main window have a window state, and other reader window have another window state. It will be troublesome if user need resize reader window when open a new reader window.
Or you may only have a main group, which every window is main group and have a same window state. 
***
For first use case
`
add_group("main", "main")
.add_group("reader", "reader")
`
First add group in builder, then open new reader window with label start with `reader`(for example: `reader-1`, `reader-2`), the reader can have same window state which I expected.
***
For second use case,
`add_group("main", "main")`, and open new window with label start with `main`, this way, every window could be same state.
***
The match rule maybe more complicated, supported regex rule.
