### ISSUE TITLE
[window-state] Set the name of the saved config file

### ISSUE THREAD

**Issue by luucasrb** [tauri-apps/plugins-workspace#516]
## Description

Instead of using the default `.window-state`, I want to set the name of the config file as a parameter to the `tauri_plugin_window_state::Builder::default().build()`, and be able to restore the same file when needed.

## Reference

The feature is similar to the [electron-store#name](https://github.com/sindresorhus/electron-store#name).

**Comment by amrbashir** [comment]
I am a bit curious why you need to change the file name? since all state are managed by the plugin, so you can't modify it on your own

**Comment by luucasrb** [comment]
> I am a bit curious why you need to change the file name? since all state are managed by the plugin, so you can't modify it on your own

I have two different frontend applications under the same Host and different ports that runs with the same Tauri code.

I want to be able to store different states for each application in a way that the state of the app1 don't intefere in the app2.

**Comment by amrbashir** [comment]
that should already be covered by the [`identifier`](https://tauri.app/v1/api/config/#bundleconfig.identifier) field which should be unique

**Comment by luucasrb** [comment]
> that should already be covered by the [`identifier`](https://tauri.app/v1/api/config/#bundleconfig.identifier) field which should be unique

Based on my understanding of the [identifier](https://tauri.app/v1/api/config/#bundleconfig.identifier) docs, it should be unique for the application domain name, right? In my use case, the domain is the same but the application port is different. 

- my.application.com:8000
- my.application.com:8001

Or should I simply set an random identifier for each application?

**Comment by amrbashir** [comment]
the `identifier` should be unique for each app, you can reuse your domain but it has to at least be different in one character, so it should be something like this:
- com.domain.calculator
- com.domain.clock
- com.domain.dialer
and so on...

and I don't think `:` is allowed in the identifiers, so I think it gets stripped and thus the identifiers become the same and conflicts happen.
