### ISSUE TITLE
[store] Not allowed by the scope only in release build

### ISSUE THREAD

**Issue by heshiming** [tauri-apps/plugins-workspace#547]
Hi,

I'm trying to use the "store" plugin. I set things up according to [the documentation](https://github.com/tauri-apps/tauri-plugin-store). I also put the following segment into `tauri.conf.json`:

    "security": {
      "csp": "",
      "dangerousRemoteDomainIpcAccess": [
        { "domain": "localhost", "windows": ["main"], "plugins": ["tauri-plugin-store"] }
      ]
    },

My program runs its own HTTP server in a background process. I call the plugin like this in react:

    import { Store } from "tauri-plugin-store-api";
    const store = new Store("settings.dat");
    store.set('name', 'value').then();
    store.save().then(function () {
      toast.success('settings saved');
    })
    .catch(function (error) {
      toast.error('save setting failed ' + error);
    });

In development (`npm run tauri dev`), it runs fine. But when running the release build, it shows the error "Not allowed by the scope". I'm running Tauri v1.4 on Intel Mac.

Any ideas what I did wrong?

Thanks!

**Comment by heshiming** [comment]
After numerous tries, I discovered that the correct form of `plugins` under `dangerousRemoteDomainIpcAccess` is `"store"`, not `"tauri-plugin-store"`.

**Comment by FabianLars** [comment]
Are you serving your frontend over that http server meaning the origin will be something http://localhost:port ? And is that why you added `dangerousRemoteDomainIpcAccess` ?

**Comment by heshiming** [comment]
> Are you serving your frontend over that http server meaning the origin will be something http://localhost:port ? And is that why you added `dangerousRemoteDomainIpcAccess` ?

Yes, I'm serving from a port, like http://localhost:55101 . But there is no "port" field in the configuration.

**Comment by FabianLars** [comment]
Alright, thanks! So is there any issue left or just missing documentation?

**Comment by heshiming** [comment]
> Alright, thanks! So is there any issue left or just missing documentation?

Well I think just documentation at this point. I found practically nothing mentioning the syntax of the plugin. But `"store"` worked flawlessly. Thanks.

**Comment by FabianLars** [comment]
added a docs hotfix for a start here: https://github.com/tauri-apps/tauri/pull/7605
