### ISSUE TITLE
[shell] shell.open not working in production

### ISSUE THREAD

**Issue by FlysoftBeta** [tauri-apps/plugins-workspace#553]
I'd tried calling shell.open by using the javascript api but it doesn't work in production builds.

**Comment by FabianLars** [comment]
1) Please include the output of the `tauri info` command.
2) Try a debug build via the `--debug` flag (note that if you use `npm` you'll need an extra `--` like `npm run tauri build -- --debug`), output in `target/debug/` and check the terminal and devtools console for errors.
3) If you can't solve it with the debug flag, please add a reproduction example or at least exact reproduction steps.

**Comment by FlysoftBeta** [comment]
Solved. I used the wrong configuration. `plugins` field should use `shell` instead of `tauri-plugin-shell`:
```json
{
	"security": {
		"csp": null,
		"dangerousRemoteDomainIpcAccess": [
			{
				"domain": "tauri.localhost",
				"windows": ["main"],
				"plugins": ["shell"]
			}
		]
	}
}
```
