### ISSUE TITLE
[sql] When trying to connect to postgresql getting error: Not allowed by the scope 

### ISSUE THREAD

**Issue by CursedMun** [tauri-apps/plugins-workspace#554]
After the build, it says 'Not allowed by the scope', it's something with access to an external domain.
I'm not sure how to give SQL plugin access to my host the whole path looks something like this: `postgres://login:pass@domain:4902/db`
it works in dev mode

```
"security": {
"dangerousRemoteDomainIpcAccess": [
{
          "scheme": "http",
          "domain": "domain",
          "windows": ["main"],
          "plugins": [
            "tauri-plugin-sql-api",
            "sql-api"
          ]
        }
]
}
```

**Comment by FabianLars** [comment]
Thanks for the report, could you also include the output of the `tauri info` command please?

**Comment by FabianLars** [comment]
Oh and, try using just `sql` in the `plugins` property.

**Comment by CursedMun** [comment]
> Oh and, try using just `sql` in the `plugins` property.

Thanks, that worked xd
