### ISSUE TITLE
[deep-link] v2 - desktop support

### ISSUE THREAD

**Issue by FabianLars** [tauri-apps/plugins-workspace#568]
We can start with my v1 plugin and then migrate to Amr's bundler work. We'll probably end up with both to also support portable apps.

**Comment by dscso** [comment]
What is the status of this issue?

**Comment by FabianLars** [comment]
the v2 beta cli/bundler supports it already so the app installers can register schemes at install time. Runtime apis are worked on here https://github.com/tauri-apps/plugins-workspace/pull/916

**Comment by dscso** [comment]
Thanks for the fast awnser :)
Therefore `CFBundleURLSchemes` is not yet supported right?
I have to use Tauri v2 (https://github.com/tauri-apps/tauri/tree/dev/examples/file-associations)
and https://github.com/tauri-apps/plugins-workspace/pull/916 has to be merged, to be able to open custom protocols (e.g. irc://) on MacOS + Tauri, right?

**Comment by FabianLars** [comment]
the url _events_ on macos are supported basically by accident (because of ios support). `CFBundleURLSchemes` is part of the installer/bundler thing i mentioned though you can always add your own Info.plist file like the example you linked.

The plugin PR also won't add anything for macOS at all.
