### ISSUE TITLE
[example] API example is unresponsive when opening on Windows

### ISSUE THREAD

**Issue by FlysoftBeta** [tauri-apps/plugins-workspace#571]
Hello, I'm building the official API example on my Windows machine with following commands:
```bash
git clone git@github.com:tauri-apps/plugins-workspace.git && cd plugins-workspace/examples/api
touch yarn.lock
yarn install
yarn tauri build
```
Click on the output executable, the window opens, but it quickly becomes unresponsive.
![screenshot](https://github.com/tauri-apps/plugins-workspace/assets/49718840/1db6d574-272f-43b6-88ea-8116a7559270)

Output of `yarn tauri info`
```
[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 115.0.1901.203
    ✔ MSVC: 
        - Visual Studio Community 2022
        - Visual Studio ���ɹ��� 2019
    ✔ rustc: 1.71.1 (eb26296b5 2023-08-03)
    ✔ Cargo: 1.71.1 (7f1d04c00 2023-07-29)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.17.0
    - pnpm: 8.6.12
    - yarn: 3.6.1
    - npm: 9.6.7

[-] Packages
    - tauri [RUST]: 2.0.0-alpha.11
    - tauri-build [RUST]: 2.0.0-alpha.8
    - wry [RUST]: 0.31.0
    - tao [RUST]: 0.22.0
    - @tauri-apps/api [NPM]: 2.0.0-alpha.6
    - @tauri-apps/cli [NPM]: 2.0.0-alpha.11

[-] App
    - build-type: bundle
    - CSP: connect-src ipc: https://ipc.localhost; default-src 'self' customprotocol: asset:; img-src 'self' asset: https://asset.localhost blob: data:; font-src https://fonts.gstatic.com; style-src 'unsafe-inline' 'self' https://fonts.googleapis.com
    - distDir: ../dist
    - devPath: http://localhost:5173/
    - framework: Svelte
    - bundler: Vite
```

Edit: I tried calling dialog.open on a separate app, it becomes unresponsive too.🫤

**Comment by reyamir** [comment]
not sure same issue or not
but in my app, it hang if using fetch from `HTTP` or `Stronghold` plugin (latest tauri v2.0.0-alpha.11)

**Comment by zitiger** [comment]
Same issue in Mac too. 

How to reproduce it:

1. create a new app with create-tauri-app
2. Add following code in Greet.vue
 import { message } from '@tauri-apps/plugin-dialog';
3. and following in greet() of Greet.vue
  await message('Tauri is awesome', 'Tauri');
4. run the project and click Greet button, the app is unresponsive.


I tested message and open function, both are unresponsive.

**Comment by reyamir** [comment]
same issue in my mac too
I guess this issue cause by new IPC

**Comment by dfrnoch** [comment]
> same issue in my mac too I guess this issue cause by new IPC

Most probably. In my case, getting the current theme from the window plugin and maximizing the app by double clicking will cause the app to freeze indefinitely (using `data-tauri-drag-region`)

**Comment by reyamir** [comment]
> > same issue in my mac too I guess this issue cause by new IPC
> 
> Most probably. In my case, getting the current theme from the window plugin and maximizing the app by double clicking will cause the app to freeze indefinitely (using `data-tauri-drag-region`)

same with `HTTP` plugin, `Stronghold` plugin freeze few second but still work fine after that

**Comment by zitiger** [comment]
> > same issue in my mac too I guess this issue cause by new IPC
> 
> Most probably. In my case, getting the current theme from the window plugin and maximizing the app by double clicking will cause the app to freeze indefinitely (using `data-tauri-drag-region`)

群主好，

to get theme , you can try the following way, it works well for me:

#[tauri::command]
pub fn get_theme(window: tauri::Window) -> Option<String> {
    let theme = window.theme();

    if theme.is_ok() {
        Some(theme.unwrap().to_string())
    } else {
        Some("dark".to_string())
    }
}

**Comment by ImUrX** [comment]
This seems to be the actual issue:
![image](https://github.com/tauri-apps/plugins-workspace/assets/3698237/2d69da1e-e8d1-4353-89f0-1fbdaeaa9da5)

**Comment by zitiger** [comment]
> 

currently, i use rfd directly to fix this issue temp.

use rfd::{FileDialog};

#[command]
pub fn open_folder() -> String {
    let folder = FileDialog::new().pick_folder();
    let folder = folder.unwrap_or_default();
    String::from(folder.to_str().unwrap_or_default())
}

**Comment by yohannlog** [comment]
I've got the same issue (based on @ImUrX message) on linux. The problem is global to all platforms.

**Comment by LetrixZ** [comment]
There is a fix for Linux: https://github.com/tauri-apps/tauri/pull/7677
macOS and Windows still not working.

**Comment by pewsheen** [comment]
I guess this should be an issue in `tauri-runtime-wry`
https://github.com/tauri-apps/tauri/blob/29818de682146a75cd9a886f7b215154cad1d42d/core/tauri-runtime-wry/src/lib.rs#L2703-L2709

The `protocol` fn is not running asynchronously, so it's blocking the main thread and waiting for the response. But in the meantime, the response also needs to be sent back in the main thread causing a deadlock.

I think this PR may solve the issue, but it still needs to rewrite the `tauri-runtime-wry` to make it asynchronous.
https://github.com/tauri-apps/wry/pull/1017 

These issues might be related.

https://github.com/tauri-apps/tauri/issues/7727
https://github.com/tauri-apps/tauri/issues/7673
[Discord | UI freezes even with async fn on new IPC - Tauri 2.0.0-alpha11](https://discord.com/channels/616186924390023171/1148867843744608287)
