### ISSUE TITLE
[updater] v2 - updater fails to install an update on macos

### ISSUE THREAD

**Issue by pashokitsme** [tauri-apps/plugins-workspace#591]
MacOS
Download works fine, but fails on install
When updater tries to install update, it iterates through entries in archive and skip every where it can't get path. But, since archive is compressed, updater skips all entries
It doesn't return any error or something and corrupts .app

**Comment by Binlogo** [comment]
@pashokitsme It seems that you're working on fixing this issue. Are you going to create a PR to proceed it?

**Comment by pashokitsme** [comment]
@Binlogo yep, i fixed it for me. And i already created PR #592 but seems everyone (including me) forgot about it

**Comment by Binlogo** [comment]
> @Binlogo yep, i fixed it for me. And i already created PR #592 but seems everyone (including me) forgot about it

Great work, I tested your fix, and it worked for me. Let's merge pull request #592 to fix this issue. cc @amrbashir @lucasfernog 😉
