### ISSUE TITLE
[shell] v2 - how can tauri mobile open the url in default android browser?

### ISSUE THREAD

**Issue by zpng** [tauri-apps/plugins-workspace#595]
**Describe the bug**
 tauri mobile can't open the url in default android browser.

I have try the 
`-import {open} from '@tauri-apps/api/shell';
open('https://www.baidu.com')
`
but when i build the apk, and install in android, i click the url, nothing happens.

**Steps To Reproduce**
I have try the 
`-import {open} from '@tauri-apps/api/shell';
open('https://www.baidu.com')
`
but when i build the apk, and install in android, i click the url, nothing happens.

**Expected behavior**
expect click the url and open in default android browser.

**Screenshots**

**Platform and Versions (please complete the following information):**
Host OS:  android
Target OS: android
Rustc:

cargo.toml is below:
`[package]
name = "chatgptenhanced"
version = "1.2.3"
description = "A cross platform app for LLM ChatBot."
authors = ["eic", "sanks"]
license = "mit"
repository = ""
default-run = "chatgptenhanced"
edition = "2021"
rust-version = "1.60"
[build-dependencies]
tauri-build = { version = "2.0.0-alpha.0", features = [] }

[dependencies]
serde_json = "1.0"
tauri-utils = { version = "=2.0.0-alpha.0"}
tauri-macros = { version = "=2.0.0-alpha.0"}
tauri-codegen = { version = "=2.0.0-alpha.0"}
tauri-build = { version = "=2.0.0-alpha.0"}
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "=2.0.0-alpha.0", features = ["clipboard-all", "fs-all", "http-all", "path-all", "shell-all", "system-tray", "window-close", "window-hide", "window-maximize", "window-minimize", "window-set-icon", "window-set-ignore-cursor-events", "window-set-resizable", "window-show", "window-start-dragging", "window-unmaximize", "window-unminimize"] }
tauri-plugin-window-state = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }

[features]
custom-protocol = ["tauri/custom-protocol"]

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]
`

tauri.conf.json is below:
`{
  "$schema": "../node_modules/@tauri-apps/cli/schema.json",
  "build": {
    "beforeBuildCommand": "pnpm export",
    "beforeDevCommand": "pnpm export:dev",
    "devPath": "http://localhost:3000",
    "distDir": "../out"
  },
  "package": {
    "productName": "chatgpt-enhanced",
    "version": "1.2.3"
  },
  "tauri": {
    "security": {
      "csp": null
    },
    "systemTray": {
      "iconPath": "icons/32x32.png"
    },
    "allowlist": {
      "all": false,
      "fs": {
        "all": true,
        "scope": ["$APP/*", "$DESKTOP/*"]
      },
      "path": {
        "all": true
      },
      "http": {
        "all": true,
        "request": true
      },
      "shell": {
        "all": true,
        "open": true
      },
      "clipboard": {
        "all": true
      },
      "window": {
        "all": false,
        "close": true,
        "hide": true,
        "maximize": true,
        "minimize": true,
        "setIcon": true,
        "setIgnoreCursorEvents": true,
        "setResizable": true,
        "show": true,
        "startDragging": true,
        "unmaximize": true,
        "unminimize": true
      }
    },
    "bundle": {
      "active": true,
      "category": "DeveloperTool",
      "copyright": "2023, Zhang Peng All Rights Reserved.",
      "deb": {
        "depends": []
      },
      "externalBin": [],
      "icon": [
        "icons/32x32.png",
        "icons/128x128.png",
        "icons/128x128@2x.png",
        "icons/icon.icns",
        "icons/icon.ico"
      ],
      "identifier": "com.zpng.chatgpt.enhanced.web",
      "longDescription": "ChatGPT Enhanced Web is a cross-platform ChatGPT client, including Web/Win/Linux/OSX/PWA.",
      "macOS": {
        "entitlements": null,
        "exceptionDomain": "",
        "frameworks": [],
        "providerShortName": null,
        "signingIdentity": null
      },
      "resources": [],
      "shortDescription": "ChatGPT Enhanced",
      "targets": "all",
      "windows": {
        "certificateThumbprint": null,
        "digestAlgorithm": "sha256",
        "timestampUrl": ""
      }
    },
    "security": {
      "csp": null
    },
    "windows": [
      {
        "fullscreen": false,
        "height": 600,
        "resizable": true,
        "title": "ChatGPT Enhanced",
        "width": 960,
        "hiddenTitle": true,
        "titleBarStyle": "Overlay"
      }
    ]
  }
}
`

**Would you want to assign yourself to resolve this bug?**
 No

**Additional context**

**Comment by progzone122** [comment]
I support the same bug

**Comment by progzone122** [comment]
I have the same bug(((

**Comment by lucasfernog** [comment]
It hasn't been implemented yet.

**Comment by progzone122** [comment]
Then I'll stay tuned for updates, I'm missing this feature for my application

**Comment by marcusho21** [comment]
encountered the same issue with iOS and safari

**Comment by cck190891** [comment]
I attempted to open a URL using `<a>` or `open` on Android 
but encountered the following error: ```Msg: Uncaught (in promise) Scoped shell IO error: No such file or directory (os error 2)``` 

Is there a solution to this problem now?

**Comment by ImUrX** [comment]
this should be tagged as `good first issue` if its not a priority for now, i might be interested in PRing partial support just for opening URLs

**Comment by xlambein** [comment]
I'm interested in this as well, for the opening of URLs specifically, but I'm not totally sure how to proceed with an implementation. I will have time to dedicate to it in the near future, so if someone has even vague suggestions of how it could be implemented, I'm interested to have a chat.
