### ISSUE TITLE
Tauri throws an error relating to that I cannot name window with "main", cause there is already one.

### ISSUE THREAD

**Issue by St4niuu** [tauri-apps/plugins-workspace#597]
So, I am using the localhost-plugin for tauri app, because I got a problem with mixed content trying to reach API endpoints. Everything works just fine, but I gotta set the window name to something different than "main", because it's already used by actual main window. As it turns out, it cannot be overwritten. So, when I run my app I am getting 2 windows. The main with not working API and the second with working API.

How do I resolve this problem to let it on "main"?

> thread 'main' panicked at 'error while running tauri application: Setup(SetupError(WindowLabelAlreadyExists("main")))', src\main.rs:30:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```rs
// Prevents additional console window on Windows in release, DO NOT REMOVE!!
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

// Learn more about Tauri commands at https://tauri.app/v1/guides/features/command

use tauri::{utils::config::AppUrl, window::WindowBuilder, WindowUrl};

fn main() {
  let port = portpicker::pick_unused_port().expect("failed to find unused port");

  let mut context = tauri::generate_context!();
  let url = format!("http://localhost:{}", port).parse().unwrap();
  let window_url = WindowUrl::External(url);
  // rewrite the config so the IPC is enabled on this URL
  context.config_mut().build.dist_dir = AppUrl::Url(window_url.clone());

  tauri::Builder::default()
    .plugin(tauri_plugin_localhost::Builder::new(port).build())
    .setup(move |app| {
      WindowBuilder::new(
        app,
        "main",
        window_url
      )
      .title("Localhost Example")
      .build()?;
      Ok(())
    })
    .run(context)
    .expect("error while running tauri application");
}
```

**Comment by FabianLars** [comment]
You'll need to either remove the window config from the tauri.conf.json file and only spawn the window from rust, or delete the `.setup` stuff from the code and only use the tauri config to spawn the window (<https://github.com/tauri-apps/plugins-workspace/issues/148#issuecomment-1692776095>) - otherwise you're indeed creating 2 windows here.
