### ISSUE TITLE
[notification] I can't import the Schedule class ？。。

### ISSUE THREAD

**Issue by lxfxy** [tauri-apps/plugins-workspace#625]
![image](https://github.com/tauri-apps/plugins-workspace/assets/56082897/c95ec380-9340-418c-b5f8-7141dae02741)

![image](https://github.com/tauri-apps/plugins-workspace/assets/56082897/0498874b-c352-4ccb-8a98-0a1008369ca2)

![image](https://github.com/tauri-apps/plugins-workspace/assets/56082897/f57d694d-e0b0-4e00-b350-6b02c89a045f)

"@tauri-apps/plugin-notification": "2.0.0-alpha.1"

**Comment by ItsRoy69** [comment]
Can someone assign me ? Ican work on this issue.

**Comment by FabianLars** [comment]
Awesome, we appreciate it!
