### ISSUE TITLE
[fs-watch] v2 - Will the Fs-Watch plugin migrate to V2

### ISSUE THREAD

**Issue by Pylogmon** [tauri-apps/plugins-workspace#628]
I notice that the fs-watch plugin is not yet available in the V2 branch, please tell me if it is deprecated in v2 or just not migrated yet, Thank you.

**Comment by FabianLars** [comment]
It was merged into the `fs` plugin. I'd like to revert that change but for the time being that's where you can find it.

**Comment by Pylogmon** [comment]
Okay, thanks for your reply.
