### ISSUE TITLE
[autostart] Help with autostart on macOS (LaunchAgent)

### ISSUE THREAD

**Issue by vovayatsyuk** [tauri-apps/plugins-workspace#634]
When I use `tauri_plugin_autostart::MacosLauncher::LaunchAgent` macOS shows me the following message: "App is an item that can run in the background. You can manage this in login items settings." But it's not added to the login apps and doesn't run automatically after restart.

Is `LaunchAgent` supposed to work as I describe or am I missing something?

**Comment by vovayatsyuk** [comment]
In case if someone has the same question:

> LaunchAgent: **Your app will not appear in the user's Login Items.**

Source: https://github.com/Teamwork/node-auto-launch#mac (It's a nodejs project, but https://github.com/zzzgydi/auto-launch works in the same way)

I still don't know why autostart is not working. Maybe the app must be signed to make it work?

**Comment by morajabi** [comment]
@vovayatsyuk I've fixed this issue, will create a PR soon. If you're able to fork the minimal fix that fixes Launch Agent is changing the plugin init here: https://github.com/tauri-apps/plugins-workspace/blob/v2/plugins/autostart/src/lib.rs#L124
To this:
```
 #[cfg(target_os = "macos")]
      {
        let exe_path = current_exe.canonicalize()?.display().to_string();

        match macos_launcher {
          MacosLauncher::AppleScript => {
            // current_exe gives path to /Applications/Example.app/MacOS/Example
            // but this results in seeing a Unix Executable in macOS login items
            // on macOS via AppleScript it must be: /Applications/Example.app
            // If it didn't find exactly a single occurance of .app, it will default to
            // exe path to not break it.
            let parts: Vec<&str> = exe_path.split(".app/").collect();
            let app_path = if parts.len() == 2 {
              format!("{}.app", parts.first().unwrap())
            } else {
              exe_path
            };
            info!("auto_start path {}", &app_path);
            builder.set_app_path(&app_path);
          }
          MacosLauncher::LaunchAgent => {
            builder.set_app_path(&exe_path); // <- this fixes it
          }
        }
      }
```

I've recently realized launch agent requires the exe path contrary to AppleScript that is best to use the .app path.
Also, you probably have to sign the app before attempting to test autostart.

**Comment by vovayatsyuk** [comment]
Yay, thank you so much!

I've just tested it on my fork: https://github.com/vovayatsyuk/tauri-plugins-workspace/commit/4e463eb226bd3bc741ee4b5adfab6899bc6db04b, and it's working! 

It works without signing too.

p.s. I'm using v1 branch. Will you create a PR for it as well, or should I do that?

**Comment by morajabi** [comment]
@vovayatsyuk go ahead!

**Comment by allentown521** [comment]
https://github.com/tauri-apps/plugins-workspace/issues/2342
