### ISSUE TITLE
[single-instance]The callback is not executed after the new instance is closed

### ISSUE THREAD

**Issue by jetli** [tauri-apps/plugins-workspace#648]
With tauri 1.5, the callback is not executed after the new instance is closed, for example:
```rust
.plugin(tauri_plugin_single_instance::init(|app, argv, cwd| {
            println!("{}, {argv:?}, {cwd}", app.package_info().name);

            app.emit_all("single-instance", Payload { args: argv, cwd }).unwrap();
        }))
```
when I build with --debug, nothing is printed on console. I believe this plugin works with previous versions, I don't know when it breaks.

**Comment by bling-yshs** [comment]
same

**Comment by bling-yshs** [comment]
You can install and run the current program first, and then use "tauri dev" to trigger it properly. And this callback will be triggered within the first program, not the second one. I'm using tauri 1.5.2

**Comment by bling-yshs** [comment]
> Sorry, I made a mistake. The callback won't be triggered during "cargo run," but you can install and run the current program first, and then use "tauri dev" to trigger it properly. And this callback will be triggered within the first program, not the second one. I'm using tauri 1.5.2

my code:
```
#![cfg_attr(
all(not(debug_assertions), target_os = "windows"),
windows_subsystem = "windows"
)]

use tauri::Manager;
use window_vibrancy::apply_mica;

#[derive(Clone, serde::Serialize)]
struct Payload {
    args: Vec<String>,
    cwd: String,
}

fn main() {
    tauri::Builder::default()
        .plugin(tauri_plugin_single_instance::init(|app, argv, cwd| {
            let window = app.get_window("main").unwrap();
            window.unminimize().unwrap();
            window.set_focus().unwrap();
            println!("{}, {argv:?}, {cwd}", app.package_info().name);
            app.emit_all("single-instance", Payload { args: argv, cwd }).unwrap();
        }))
        .plugin(tauri_plugin_upload::init())
        .setup(|app| {
            let window = app.get_window("main").unwrap();
            #[cfg(target_os = "windows")]
            match apply_mica(&window, None) {
                Ok(_) => (),
                Err(_) => ()
            }
            window.set_decorations(true).unwrap();
            Ok(())
        })
        .invoke_handler(tauri::generate_handler![
            // page::start::start::start_yunzai_and_api,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application")
}

```

**Comment by Smart-yang** [comment]
@bling-yshs Install the exe file automatically for the first time, click on the shortcut, single_ Instance does not have a callback, closing exe and reopening shortcut is sufficient to solve the first single issue_ Instance callback issue No, thank you
