### ISSUE TITLE
[websocket] v1 to v2 merge error

### ISSUE THREAD

**Issue by Dreaming-Codes** [tauri-apps/plugins-workspace#695]
I noticed that my contribution to v1, which added header support for websockets, has been merged into v2. However, it appears to have been merged incorrectly, as it's missing those lines https://github.com/tauri-apps/plugins-workspace/blob/8d6045421a553330e9da8b9e1e4405d419c5ea88/plugins/websocket/src/lib.rs#L104-L115

**Comment by FabianLars** [comment]
I'm only on my phone right now so take it with a grain of salt but I'm pretty sure I did not yet merge v1 into v2 after that PR 🤔

**Comment by Dreaming-Codes** [comment]
> I'm only on my phone right now so take it with a grain of salt but I'm pretty sure I did not yet merge v1 into v2 after that PR 🤔

I assumed they had been merged due to the presence of the field header in the config

**Comment by Dreaming-Codes** [comment]
> I'm only on my phone right now so take it with a grain of salt but I'm pretty sure I did not yet merge v1 into v2 after that PR 🤔

I assumed they had been merged due to the presence of the field header in the config

**Comment by FabianLars** [comment]
It indeed wasn't merged yet: https://github.com/tauri-apps/plugins-workspace/pull/702/files#diff-dee408ed956e8dd38398059404d9d9ea771834fb2792fc93ac816043cef088a1
