### ISSUE TITLE
window-state doesn't save or restore

### ISSUE THREAD

**Issue by thewh1teagle** [tauri-apps/plugins-workspace#701]
Hello!
I'm using the plugin `window-state` with `tauri`, and I create the window manually inside setup so my `main.rs` looks like:
```rust
 tauri::Builder::default()
    .setup(move |app| {
      let mut window = tauri::WindowBuilder::new(app, "main", tauri::WindowUrl::External(Url::parse("https://google.com/").unwrap())
      window = window.title("app");
      window = window.min_inner_size(800.0, 400.0);
      window.build()?;
      Ok(())
     })
    .plugin(tauri_plugin_window_state::Builder::default().build())
    .run(tauri::generate_context!())
    .expect("error while running tauri application");
```

For some reason the window state isn't restored, after I close the window and reopen the program the size and position of the window isn't restored.
If I don't manually create the window but create it using `tauri.config.json` it works.

**Comment by thewh1teagle** [comment]
Update: 
It only happens when using [window-customization](https://tauri.app/v1/guides/features/window-customization/) buttons to close the window with `appWindow.close()`. 
when using the default controls to close the app it works normally

**Comment by thewh1teagle** [comment]
Update: 
I found a workround, I close the app with custom command.
```rust
#[tauri::command]
fn close_app(app: AppHandle) {
    app.save_window_state(StateFlags::all());
    app.exit(0);
}
```

**Comment by FabianLars** [comment]
Something like that is currently the only way, if you close the window yourself the plugin won't be notified about the closed window, and we'd have to change the Tauri apis for that to work (iirc there were plans for that).
