### ISSUE TITLE
[dialog] v2 confirm always returns true

### ISSUE THREAD

**Issue by Zercerium** [tauri-apps/plugins-workspace#711]
tauri alpha.17, dialog plugin 2.0.0-alpha.4, macOS
```ts
import { confirm } from "@tauri-apps/plugin-dialog";
const confirmed = await confirm("Are you sure?");
console.log(confirmed);
```

Current behaviour:
Press Ok => returns true
Press Cancel => returns **true**

Expected behaviour:
Press Ok => returns true
Press Cancel => returns **false**

**Comment by Zercerium** [comment]
Ok after some digging into the code this doesn't work as intended
```rust
let response = tauri::async_runtime::block_on((MessageDialog::from(dialog).show()));
f(!match response {
    rfd::MessageDialogResult::No | rfd::MessageDialogResult::Cancel => true,
     _ => false,
});
```

if the buttons labels are set manual `show()` returns `MessageDialogResult::Custom(String)`, so the Strings have to be compared to see which button is pressed.

(think would be easier if rfd just returned the default buttons, also if a custom string is set)

**Comment by pashokitsme** [comment]
Same problem.

In `show_message_dialog` fn ([here](https://github.com/tauri-apps/plugins-workspace/blob/v2/plugins/dialog/src/desktop.rs#L225)) you can access `ok` and `cancel` labels and match the `MessageDialogResult` right after macro call instead of doing it inside (cuz linux and non-linux match!(..) are same)

Pseudocode:
```rust
pub fn show_message_dialog<...>(dialog: MessageDialogBuilder<R>, f: F) {
  let ok_str = dialog.ok_button_label.as_ref().unwrap();
  let cancel_str = dialog.cancel_button_label.as_ref().unwrap();
  let result = run_dialog!(MessageDialog::from(dialog).show());
  // match ...
  f(/* result of match */);
}
```
