### ISSUE TITLE
[v2 branch] The way of exporting module seems not friendly in package.json

### ISSUE THREAD

**Issue by percy507** [tauri-apps/plugins-workspace#738]
### Description

In my project, I use typescript(v4.7) with config `"module": "esnext", "moduleResolution": "node"`.

If I use the lasted release of the tauri plugin package(eg: @tauri-apps/plugin-log). I will get type error which says can't recognize package `@tauri-apps/plugin-log`. Then I check the package.json of the plugin, I notice below code.

https://github.com/tauri-apps/plugins-workspace/blob/5a8bbe296704f679063ef8b820d582d7f728400b/plugins/log/package.json#L9-L14

After some research, they told me should use typescript(v5) with config `"module": "esnext", "moduleResolution": "bundler"`. They are right. The plugin package now are recognizable.

But new type error appears. `tsc` now can't recognize subpath of package. Eg:

```ts
// Cannot find module '@zing/helpers/dist/tippy' or its corresponding type declarations.
import { getTippy } from '@zing/helpers/dist/tippy';

// package.json of @zing/helpers
{
  ...
  "main": "dist/index.js",
  "module": "dist/index.js",
  "types": "dist/index.d.ts",
  "files": ["dist"],
  "exports": {
    ".": "./dist/index.js",
    "./dist/": "./dist/"
  },
}
```

### Hope

Change the way of exporting module to a more friendly one. 

Here is a example. https://github.com/ProseMirror/prosemirror-model/blob/master/package.json#L5-L12

![](https://bashupload.com/dQ0hb/SMWGb.png)

**Comment by percy507** [comment]
Well, I switch back to typescript(v4.7) with config `"module": "esnext", "moduleResolution": "node"`.

```ts
// get type error, but the app can run well
import log from '@tauri-apps/plugin-log';

// no type error, but get a vite runtime error
import log from '@tauri-apps/plugin-log/dist-js/index';

// runtime error
✘ [ERROR] Missing "./dist-js/index" specifier in "@tauri-apps/plugin-log" package [plugin vite:dep-scan]

    src/services/tauri.ts:9:21:
      9 │ export * as log from '@tauri-apps/plugin-log/dist-js/index';
        ╵                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  This error came from the "onResolve" callback registered here:

    node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1292:20:
      1292 │       let promise = setup({
```

**Comment by FabianLars** [comment]
The released plugin uses these exports: https://github.com/tauri-apps/plugins-workspace/blob/d4d1633c4d0b63b26db987037d1ed7e57d5cefbe/plugins/log/package.json#L9-L17
Which to me looks similar to the prosemirror example right?

The package.json you linked will be used in the next release (unless we find issues with it now of course) - maybe the new one actually works better for you? You can try the unreleased version by pulling the npm package from git: https://github.com/tauri-apps/tauri-plugin-log/tree/v2#Usage - for example `yarn add https://github.com/tauri-apps/tauri-plugin-log#v2`

If neither the old version, nor the new one work i really don't understand what we have to change to make it work tbh.

**Comment by percy507** [comment]
In my project, I already use v2 branch.

```json
  "dependencies": {
    ...
    "@tauri-apps/api": "^2.0.0-alpha.11",
    "@tauri-apps/plugin-clipboard-manager": "github:tauri-apps/tauri-plugin-clipboard-manager.git#v2",
    "@tauri-apps/plugin-dialog": "github:tauri-apps/tauri-plugin-dialog.git#v2",
    "@tauri-apps/plugin-fs": "github:tauri-apps/tauri-plugin-fs.git#v2",
    "@tauri-apps/plugin-log": "github:tauri-apps/tauri-plugin-log.git#v2",
    ...
}
```

<s>It seems this commit (https://github.com/tauri-apps/plugins-workspace/commit/1b98b85a1f7b580bc6605a3a274b6a0a86530bd9) delete the normal export way.</s> (My mistake, I mix up `tauri-apps/plugins-workspace` and `tauri-apps/tauri-plugin-log`)

> If neither the old version, nor the new one work i really don't understand what we have to change to make it work tbh.

@FabianLars Well, the old version works for me (commit: https://github.com/tauri-apps/tauri-plugin-log/commit/f504850328f81e6d5a93c1fef88669875ad52874). The new one doesn't work for type recognition, but it can be bundle. 

It seems this commit (https://github.com/tauri-apps/tauri-plugin-log/commit/9ec9463e2e3701852527ff6c61462a94cc91b31f) delete the normal export way. The other plugin pakcage may have same issue.

**Comment by amrbashir** [comment]
looks like `moduleResolution: "node"` doesn't handle the `exports` field well, gonna add these fields back then I guess
