### ISSUE TITLE
[window-state] macOS spams resize event

### ISSUE THREAD

**Issue by ImUrX** [tauri-apps/plugins-workspace#77]
For some reason macOS spams the resize events which basically kills the performance of the application
See tauri-apps/tao#641

**Comment by Megamannen** [comment]
+1

Same here (not verified it's that event that gets spammed). If this plugin is active the application basically freezes for us)

**Comment by FabianLars** [comment]
Actually i think this should be fixed with https://github.com/tauri-apps/plugins-workspace/pull/104, which in turn re-introduced https://github.com/tauri-apps/plugins-workspace/issues/254 😩
