### ISSUE TITLE
Could not find a declaration file for module '@tauri-apps/api/primitives'. 

### ISSUE THREAD

**Issue by songjiachao** [tauri-apps/plugins-workspace#798]
<img width="1090" alt="iShot_2023-12-05_19 53 32" src="https://github.com/tauri-apps/plugins-workspace/assets/70792885/2a56f80c-4785-4adf-a376-656da0914919">

**Comment by FabianLars** [comment]
I'm not sure how that is related to this repository?

Anyway, in your tsconfig.json file try changing the `moduleResolution` setting to `"Bundler"` (only required until the next api release).
If that doesn't fix it please post the output of `pnpm tauri info`

**Comment by songjiachao** [comment]
Thank You
