### ISSUE TITLE
[sql] Can't seem to get SQL plugin to work

### ISSUE THREAD

**Issue by espositofulvio** [tauri-apps/plugins-workspace#82]
I tried copy-pasting the code from the README but it looks like Builder doesn't implement Default anymore and there's no ::init() method like other plugins provide, so the following doesn't work:

```rust
fn main() {
    tauri::Builder::default()
        .plugin(tauri_plugin_sql::Builder::default()) // default() is not implemented
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

// this also doesn't work
fn main() {
    tauri::Builder::default()
        .plugin(tauri_plugin_sql::init()) // init() is not provided
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
```

Also Builder can be actually constructed as the only member isn't public. How can I initialize the plugin?

**Comment by FabianLars** [comment]
`Builder` should implement `Default` now. Thanks for the report!
