### ISSUE TITLE
[store]: value should not wrapped by quotation marks

### ISSUE THREAD

**Issue by AlphaFoxz** [tauri-apps/plugins-workspace#821]
# Version:
- tauri-plugin-store = "2.0.0-alpha"  #v2.0.0-alpha.5

# Expected: rust can read value from store correctly.
I need to read some custom settings when startup. the value written by frontend.

# Actual: The string value is wrapped by quotation marks

# Code: 
```rust
let mut store = StoreBuilder::new(".settings.dat").build(app.handle().clone());
store.load().unwrap();
let v = &store.get("targetDir").unwrap();
eprintln!("{}", v.to_string());
// v.to_string() got "\"D:/project_name\""
// but this value in my storefile is {"targetDir": "D:/project_name"}
```

**Comment by FabianLars** [comment]
Calling `to_string` on a serde_json [Value](https://docs.rs/serde_json/1.0.108/serde_json/value/enum.Value.html) converts it to a json string. What you're looking for is [`v.as_str()`](https://docs.rs/serde_json/1.0.108/serde_json/value/enum.Value.html#method.as_str)
