### ISSUE TITLE
Localhost plugin example does not work

### ISSUE THREAD

**Issue by kirill-konshin** [tauri-apps/plugins-workspace#838]
I have used code from the example https://github.com/tauri-apps/plugins-workspace/tree/v1/plugins/localhost to launch a new `http://localhost` window instead of `tauri://localhost`:

```rs
// Prevents additional console window on Windows in release, DO NOT REMOVE!!
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

use tauri::{utils::config::AppUrl, window::WindowBuilder, WindowUrl};

fn main() {
  let port = portpicker::pick_unused_port().expect("failed to find unused port");

  let mut context = tauri::generate_context!();
  let url = format!("http://localhost:{}", port).parse().unwrap();
  let window_url = WindowUrl::External(url);
  // rewrite the config so the IPC is enabled on this URL
  context.config_mut().build.dist_dir = AppUrl::Url(window_url.clone());

  tauri::Builder::default()
    .plugin(tauri_plugin_localhost::Builder::new(port).build())
    .setup(move |app| {
      WindowBuilder::new(
        app,
        "main".to_string(),
        if cfg!(dev) {
          Default::default()
        } else {
          window_url
        }
      )
      .title("Localhost Example")
      .build()?;
      Ok(())
    })
    .run(context)
    .expect("error while running tauri application");
}
```

And I am getting the error:

```
thread 'main' panicked at src/main.rs:32:6:
error while running tauri application: Setup(SetupError(WindowLabelAlreadyExists("main")))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

If I change `"main".to_string()` to something else — I am getting a second window in addition to `main`, but my goal is to replace the main window with `http://localhost:xxxx` one.

The issue I am trying to solve with localhost is that YouTube Iframe Embed does not work with custom protocol origins.

It would be great to have a way to serve the site at localhost while not exposing the port and without custom protocol. Here's an example how I solved it previously using Electron:

```js
const { protocol } = require('electron');

const localhostUrl = 'http://localhost:3000';

protocol.interceptBufferProtocol('http', (request, callback) => {
    if (request.url.includes(localhostUrl)) {
        let fileUrl = request.url.replace(localhostUrl, '');
        if (fileUrl === '/') fileUrl = 'index.html';
        return callback(fs.readFileSync(path.join(indexPath, fileUrl)));
    }
    fetch(request.url, request).then((res) => res.buffer()).then(callback).catch(callback);
});
```

**Comment by FabianLars** [comment]
You have 2 options, either remove the window from tauri.conf.json: https://github.com/tauri-apps/plugins-workspace/issues/160#issuecomment-1431290561 (that's what we intended), or modify the config in code: https://github.com/tauri-apps/plugins-workspace/issues/148#issuecomment-1692776095 (works, but the output of generate_context is considered unstable, which didn't matter in any of the 1.x releases but still)

**Comment by kirill-konshin** [comment]
@FabianLars Both options worked, thanks! I suggest to modify the readme to make it clearer.
