### ISSUE TITLE
[SQL] add_migrations call is required and shouldn't be

### ISSUE THREAD

**Issue by espositofulvio** [tauri-apps/plugins-workspace#84]
Hi, this is following the fix for the missing derive Default on the Builder. If add_migrations is never called, the plugin panics on line [351](https://github.com/tauri-apps/plugins-workspace/blob/dev/plugins/sql/src/plugin.rs#L351):

```rust
app.manage(Migrations(Mutex::new(self.migrations.take().unwrap())));
```

The workaround is the following:

```rust
fn main() {
    tauri::Builder::default()
        .plugin(tauri_plugin_sql::Builder::default().add_migrations("", vec![]).build())
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
```

but I guess there's a potential bug also on line https://github.com/tauri-apps/plugins-workspace/blob/dev/plugins/sql/src/plugin.rs#L342 if there's a preloaded db and no migrations. I would gladly help and fix it myself with a pull request, but I'm still not very confident with Rust.

**Comment by FabianLars** [comment]
Should work now too, thanks again!

L342 shouldn't cause any errors because `if let Some()` should take care of the case where there are no migrations for that database.
