### ISSUE TITLE
[fs] 2.0.0-alpha.6 bug

### ISSUE THREAD

**Issue by vangork** [tauri-apps/plugins-workspace#846]
1. writeTextFile in non-append mode won't truncate the existing contents.
2. if WriteFileOptions is not set in writeTextFile call,  it will panic at https://github.com/tauri-apps/plugins-workspace/blob/38b5d37b5447e19931b1048a3d88fdca44fe0a22/plugins/fs/src/commands.rs#L600

**Comment by zhangsan946** [comment]
For the latest release of 2.0.0-alpha.7, `WriteFileOptions` of `create` is described to be `true` on js doc, but its real default value is `false` on the rust backend during initialization. @amrbashir
