### ISSUE TITLE
[http]The custom headers parameter added on the HTTP request cannot be accepted on the server, involving versions 1 and 2

### ISSUE THREAD

**Issue by lingoh** [tauri-apps/plugins-workspace#850]
const res: any = await fetch(
    "https://my.api.com/api",
    {
      method: "GET",
      headers:{
cookie: 'a=b'
},
    }
  );

**Comment by amrbashir** [comment]
Please explain your issue a bit more.

**Comment by lingoh** [comment]
> Please explain your issue a bit more.

For example, if fetch requests address A and sends custom header parameters, the service at address A cannot receive these custom parameters because @ tauri apps_ In plugin http. js, fetch uses the return value of new request to pass, but in the middle, it passes an invoice. Does this lead to invalid parameter passing

**Comment by amrbashir** [comment]
I am not an expert in servers or how cookies work but I tried your example with the browser `fetch` and it shows the same behavior as `fetch` from our http plugin. Also other headers can be seen just fine.
 
That said, I will close this issue as the behavior is consistent with the browser.

**Comment by lingoh** [comment]
@amrbashir The fetch here is import {fetch} from "@tauri-apps/plugin-http";

It's not that the browser comes with a fetch.

The server cannot receive custom parameters

**Comment by amrbashir** [comment]
yeah I understand that. I am saying that the browser `fetch` and `{fetch} from "@tauri-apps/plugin-http"` both have the same behavior, they both don't show the `cookie` header on the server while other headers show just fine.

**Comment by lingoh** [comment]
Other heads cannot receive it either

**Comment by amrbashir** [comment]
from my testing, other headers showed up just fine, can you give more examples about these headers?
