### ISSUE TITLE
[store] Question: How to set default values for a Store

### ISSUE THREAD

**Issue by prayag17** [tauri-apps/plugins-workspace#868]
I am trying to create a settingsStore that holds all user settings for my app, I wanted to set default values for some options but was unable to find a way to set a default value in the Store.

**Comment by FabianLars** [comment]
This can only be done in Rust. Also we do have really short examples in the function comments but without a docs.rs release that's hard to find, sorry about that. Here's the gist of it
```rs
use tauri_plugin_store::StoreBuilder;
use serde_json::json;
use std::collections::HashMap;

fn main() {
    tauri::Builder::default()
        .setup(|app| {
            let mut defaults = HashMap::new();

            // Add your default values
            defaults.insert("foo".to_string(), "bar".into());

           let mut store = StoreBuilder::new(app.handle(), "store.bin".parse()?).defaults(defaults).build();

           // register the plugin here instead of on the tauri::Builder
           app.plugin(tauri_plugin_store::Builder::default().store(store).build())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
```

You could also insert the values into the created store directly but using `defaults` allows you to reset to the default state at runtime if needed.
Also, you still need to call `store.load()` to get the values that were saved on disk, but you can do that in js too.

**Comment by prayag17** [comment]
Ohk thanks
