### ISSUE TITLE
plugin-http send request with maxRedirections=0  return error

### ISSUE THREAD

**Issue by sMythicalBird** [tauri-apps/plugins-workspace#883]
```typescript
    import {fetch} from '@tauri-apps/plugin-http';

    async function test() {
        const url = "https://www.baidu.com/"
        const res = await fetch(url, {
            method: "get",
            maxRedirections: 0
        })
        console.log(res.headers)
    }
```
catch `error sending request for url (https://www.baidu.com/): error trying to connect: operation timed out`

**Comment by FabianLars** [comment]
- And it works fine if you set maxRedirections to a higher number or null?
- Does setting a high connectTimeout change anything?
- Do you have a proxy set up? I'm not sure how they work but maybe the http client interprets the proxy as a redirect 🤔

**Comment by sMythicalBird** [comment]
> * And it works fine if you set maxRedirections to a higher number or null?
> * Does setting a high connectTimeout change anything?
> * Do you have a proxy set up? I'm not sure how they work but maybe the http client interprets the proxy as a redirect 🤔
 
when i  don‘t set  maxRedirections=0,itwork;
when i set  maxRedirections=0 and  connectTimeout=30000 it's stil dont work
i dont set proxy

The code above is my code.

**Comment by amrbashir** [comment]
tested using your code and it worked just fine for me, what OS are you trying on?

**Comment by sMythicalBird** [comment]
> tested using your code and it worked just fine for me, what OS are you trying on?

I'm sorry for so late reply to you.  I use win10 version 22H2  19045.3930

![image](https://github.com/tauri-apps/plugins-workspace/assets/76856797/039289d5-d9a5-4336-8ed8-be836ed1ff36)

![image](https://github.com/tauri-apps/plugins-workspace/assets/76856797/7f09e2c9-b54d-479e-8dbe-12c22428bd3e)

![image](https://github.com/tauri-apps/plugins-workspace/assets/76856797/02916416-0662-4454-8d74-4a88ad6f957f)

**Comment by amrbashir** [comment]
I believe this is something related to your network configuration as it works fine for me on Windows as well, are you using proxies or vpns?

**Comment by sMythicalBird** [comment]
> I believe this is something related to your network configuration as it works fine for me on Windows as well, are you using proxies or vpns?

It is not my network configuration problem; it is the npm  package problem;
![image](https://github.com/tauri-apps/plugins-workspace/assets/76856797/de3d6d25-de71-47bc-9f70-49c7d7b4747b)


I see the code in github is normal

**Comment by amrbashir** [comment]
I see, this is already fixed, thanks, will be available in the next release
