### ISSUE TITLE
[websocket] Use TLS Client certificate

### ISSUE THREAD

**Issue by jnugh** [tauri-apps/plugins-workspace#917]
We are working on a project that requires TLS client certificates during the TLS handshake. There is currently no way to configure anything TLS related for websockets as far as I can tell (somewhat related to #694 as well).

I was wondering if you'd accept a PR that introduces such a configuration. Tungstenite has an API that allows to pass a TLS Connector (`connect_async_tls_with_config`) that can be created using `native-tls::TlsConnector`.

I did some testing and something like this would work:
https://github.com/jnugh/plugins-workspace/commit/037b58c4b5763569f20deec69bd56560de19ba31

A user could just add a `TlsConfig` using manage and it would be used for new WebSocket connections and pass whatever is needed.

I could create a PR for this if you'd like.

**Comment by FabianLars** [comment]
Sounds reasonable to me, a PR would be much appreciated :)
