### ISSUE TITLE
[store] Where are files stored for store plugin? Persistence works weird.

### ISSUE THREAD

**Issue by HuakunShen** [tauri-apps/plugins-workspace#92]
I tried to use [tauri-plugin-store](https://github.com/tauri-apps/tauri-plugin-store). 
Data persist for page reload, but is lost after restarting. 
However, if I compile the app and run it, the data persistence work.
Where are the data files stored on disk? I would like to manually debug this. Couldn't find the answer in the plugin's source code.

**Comment by FabianLars** [comment]
It uses this function to get the path: https://docs.rs/tauri/1.2.3/tauri/api/path/fn.app_dir.html (click on the config_dir link to see path examples)

**Comment by HuakunShen** [comment]
@FabianLars Hi, thanks! I found the store files. It's under `Library/Application Support`.

But I still cannot persist data in dev mode. A production build works. In dev mode, no file is created at all, and data is lost after restart.

Is this behaviour expected? Or is there a way I can solve it.

**Comment by FabianLars** [comment]
No this behavior is not expected and wasn't reported before as far as i know.

But it can make sense to an extend. Maybe it doesn't have a change to save the file when the app is killed in dev. Did you try manually saving the store with `store.save()` once in a while?

**Comment by HuakunShen** [comment]
> No this behavior is not expected and wasn't reported before as far as i know.
> 
> 
> 
> But it can make sense to an extend. Maybe it doesn't have a change to save the file when the app is killed in dev. Did you try manually saving the store with `store.save()` once in a while?

No I didn't run save. Didn't see this method in README. Is this documented somewhere? Is there an official docs for the plugins?

Thanks!

**Comment by FabianLars** [comment]
Not yet no, but that's part of the reason we merged all the plugins into one repo. Until we have the docs set up you can check the js source which at least have doc comments: https://github.com/tauri-apps/plugins-workspace/blob/dev/plugins/store/guest-js/index.ts

**Comment by HuakunShen** [comment]
Thanks! @FabianLars 
I got the problem fixed by running `.save()` on each update.
