### ISSUE TITLE
plugin http scope not allow

### ISSUE THREAD

**Issue by songjiachao** [tauri-apps/plugins-workspace#928]
<img width="880" alt="image" src="https://github.com/tauri-apps/plugins-workspace/assets/70792885/641152f2-4bcf-49b8-95df-4deb25f81450">

error while running tauri application: PluginInitialization("http", "invalid type: map, expected unit")

**Comment by FabianLars** [comment]
The old allowlist and scope configs were replaced with a permissions system: https://beta.tauri.app/guides/upgrade-migrate/from-tauri-1/#migrate-permissions. Please read through it and get back to us if you have further questions.

**Comment by songjiachao** [comment]
I'm sorry. I have read this document many times, but I still don't know how to add permissions in my Tauri app。Such as hosts plugin. 

<img width="1340" alt="image" src="https://github.com/tauri-apps/plugins-workspace/assets/70792885/17f8acb9-61c4-4c32-bf25-c78839a8af7f">

![image](https://github.com/tauri-apps/plugins-workspace/assets/70792885/16cddf23-bdd8-4028-a510-e22a43686706)

**Comment by FabianLars** [comment]
For custom plugins we're working on docs here: https://beta.tauri.app/guides/plugins/#command-permissions and most importantly for a start, the auto generations: https://beta.tauri.app/guides/plugins/#autogenerated-permissions

**Comment by songjiachao** [comment]
Thanks, but my plugin is not a plugin project . It just a single file in my tauri project  and use`Builder::new("hosts")` to invoke_handler.
<img width="1124" alt="image" src="https://github.com/tauri-apps/plugins-workspace/assets/70792885/f7ce7b74-b449-4cb4-a579-e1ef838ee60a">

in `lib.rs` use `.plugin(hosts::init())`

<img width="1135" alt="image" src="https://github.com/tauri-apps/plugins-workspace/assets/70792885/d81805d4-7795-4de9-ae02-6a3cad3f11f5">


I don't know how to define this permissions.

I try to add hosts.toml in permissions folder like https://beta.tauri.app/guides/plugins/#permission-files

<img width="880" alt="image" src="https://github.com/tauri-apps/plugins-workspace/assets/70792885/e1ce2191-4f40-403b-8a47-d4afef0c6083">



but i don't work .

<img width="464" alt="image" src="https://github.com/tauri-apps/plugins-workspace/assets/70792885/3ecea9a9-3a32-4761-857e-f334ba3112b4">

**Comment by songjiachao** [comment]
@FabianLars   I write a demo by using `cargo create-tauri-app --beta`。I have tried one more day，But I still don't know how to add permission for `greet.hello`. can you help me fix this error。

![image](https://github.com/tauri-apps/plugins-workspace/assets/70792885/05077040-d178-4897-bf92-a2e00f545e60)

This is the demo.
[tauri-app.zip](https://github.com/tauri-apps/plugins-workspace/files/14164244/tauri-app.zip)

**Comment by FabianLars** [comment]
Hi, i spoke with @lucasfernog and it seems like inline plugins are not supported in v2 beta yet. We will try to look into it though. Thank you for bringing it to our attention.

**Comment by songjiachao** [comment]
It’s really great, I can’t wait to experience it！ Thank you very much.

**Comment by nakajimayoshi** [comment]
Hey, came across this issue while struggling through this. I think this an opportunity to improve the documentation, as after reading through the capabilities/permissions setup docs several times I'm still not able to get a buildable application. 

Some examples of how it can be improved:

1) Include a real-world example that fetches from both a localhost api and a remote api server 
2) visual file hierarchy image 

In addition, both the npm and cargo plugin add commands should be able to scaffold these permissions/capabilities automatically.

**Comment by Quietly-20201113** [comment]
So two months have passed and the problem has not been solved yet??
