### ISSUE TITLE
Update tauri_plugin_stronghold v2 to use iota_stronghold v2?

### ISSUE THREAD

**Issue by andrewweston** [tauri-apps/plugins-workspace#938]
Do you have any plans to update v2 of the `tauri_plugin_stronghold` plugin to use `iota_stronghold` v2? We need to be able to sign using the secp256k1 alg available in iota v2.

I am happy to make a PR if that helps?

**Comment by FabianLars** [comment]
Yes but in my to-do list it's after going through the last v1 prs and switching the default branch to v2 but I'm also out of office for at least another week so if you'd like to accelerate this, a PR would indeed be appreciated :)

**Comment by FabianLars** [comment]
https://github.com/tauri-apps/plugins-workspace/pull/1480
