### ISSUE TITLE
Rename event from `WatchEventKindModify` is typed as `kind: "name"` but it's `kind: "rename"` at runtime

### ISSUE THREAD

**Issue by Legend-Master** [tauri-apps/plugins-workspace#943]
https://github.com/tauri-apps/plugins-workspace/blob/dac8b6331ca1a90df5e5dac27a209445fd6e5124/plugins/fs/guest-js/index.ts#L1153

![image](https://github.com/tauri-apps/plugins-workspace/assets/68118705/29eb31ef-08bd-4981-bcbb-2a7d29af9f4c)

**Comment by amrbashir** [comment]
That's a sneaky one, seems like notify-rs has a `serde(rename = "rename")` on that event https://docs.rs/notify/6.1.1/src/notify/event.rs.html#164

**Comment by Legend-Master** [comment]
Fixed in #947
