### ISSUE TITLE
Dialog type doesn't work when calling v2 dialog from js side

### ISSUE THREAD

**Issue by Legend-Master** [tauri-apps/plugins-workspace#944]
```js
message('1', { type: 'warning' })
```

![image](https://github.com/tauri-apps/plugins-workspace/assets/68118705/93e46c16-4eef-4cda-aa54-379e574ef394)

**Comment by Legend-Master** [comment]
Fixed in #945 

Strange that GitHub didn't close this automatically

**Comment by FabianLars** [comment]
> Strange that GitHub didn't close this automatically

It's because v1 is still the default branch. Only merges to the default branch can auto close issues. I will switch default branches soon but i'll have to go through the open PRs before that first.

**Comment by Legend-Master** [comment]
Got it, never noticed that before, thanks
