### ISSUE TITLE
In the v2 version document, the download method of the global shortcut key plug-in is misspelled.

### ISSUE THREAD

**Issue by czfadmin** [tauri-apps/plugins-workspace#946]
The document cargo dependency download document command in the global shortcut key is spelled incorrectly, it should be
`tauri-plugin-global-shortcut = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v2" }` instead of `
tauri-plugin-shortcut = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v2" }`, otherwise download failure will occur.
![image](https://github.com/tauri-apps/plugins-workspace/assets/13393959/da1ff7f7-e3e5-4d53-a664-351c67863998)

**Comment by amrbashir** [comment]
Thank you, should be fixed now
