### ISSUE TITLE
[http][v2] When fetch return the 204 status code, new Response() throw an error

### ISSUE THREAD

**Issue by ppbl** [tauri-apps/plugins-workspace#957]
If the status code is 204, the Response() constructor does not allow setting the body.

- In chrome, error: `Uncaught TypeError: Failed to construct 'Response': Response with null body status cannot have body`
- In safari, error: `TypeError: Response cannot have a body with the given status`

https://github.com/tauri-apps/plugins-workspace/blob/2f0e30852acf5d84e65b4ae16fd7c1f5d648c55b/plugins/http/guest-js/index.ts#L158-L166

Try
```ts
const body = await invoke<ArrayBuffer>('plugin:http|fetch_read_body', {
    rid: responseRid,
})
const resData = body.byteLength ? new Uint8Array(body) : null
const res = new Response(resData, { 
```
or
```ts
const res = new Response(status === 204 ? null : new Uint8Array(body), {
```
can fix this issue, unsure which one is more suitable

**Comment by amrbashir** [comment]
first fix sounds better imo, thanks
