### ISSUE TITLE
NFC plugin init error

### ISSUE THREAD

**Issue by pedroaal** [tauri-apps/plugins-workspace#963]
I was making an app with tauri v2, but I noticed when using the nfc plugin it returns a plugin error.

error[E0425]: cannot find function `init` in crate `tauri_plugin_nfc`
  --> src/lib.rs:11:35
   |
11 |         .plugin(tauri_plugin_nfc::init())
   |                                   ^^^^ not found in `tauri_plugin_nfc`
   |

[dependencies]
tauri = { version = "2.0.0-beta", features = [] }
tauri-plugin-shell = "2.0.0-beta"
tauri-plugin-nfc = "2.0.0-beta"
serde_json = "1.0"

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_shell::init())
        .plugin(tauri_plugin_nfc::init())
        .invoke_handler(tauri::generate_handler![greet])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

**Comment by gato25** [comment]
Have you found solution ?

**Comment by pedroaal** [comment]
Hi, thank for answer!

Yep, I just mess up the migration from v1 to v2, although I followed the migration docs step by step, I also close the ticket.
