### ISSUE TITLE
[http][v2] not able to pass `User-Agent` in the fetch header

### ISSUE THREAD

**Issue by vangork** [tauri-apps/plugins-workspace#966]
It seems that the headers param would accept any key value pair but simply ignored `User-Agent`
```
const response = await fetch("some_url", {
    headers: {
        "User-Agent": "some_string",
    },
    method: "get",
});
```
Afterwards, the user-agent would always be set to `tauri` by:
```
if !headers.contains_key(header::USER_AGENT.as_str()) {
    request = request.header(header::USER_AGENT, HeaderValue::from_static("tauri"));
}
```

**Comment by FabianLars** [comment]
Hmm, it's probably case sensitive (something we'll have to fix if it is). Can you check if it works if you write `"user-agent": "some_string"` in your frontend?

**Comment by vangork** [comment]
Not caused by case.  some-key, Some-key, Some-Key, some-Key passed from frontend be converted to `some-key` when reaching to backend. I tested many header keys including "user-agen", "user-agenta", all of them work. But just "user-agent" would disappear from `headers` on the backend. @FabianLars

**Comment by amrbashir** [comment]
The issue is that on chromium browsers, they still disallow `User-Agent` headers even though it is not forbidden, will open a PR to fix that.
