### ISSUE TITLE
window-state restore slowly

### ISSUE THREAD

**Issue by thewh1teagle** [tauri-apps/plugins-workspace#974]
There's an issue with `window-state` plugin in both MacOS and Winodws,
It restores the window after it's visible.
And let's say that the size of the window before restoring (when creating the window)
is 500x500,
Then when it restore it to 1000x1000 Windows / MacoS kicks in resizing animation and it happens slowly,
Result: when you open windows it takes half second until the size restored and you see animation of the resize changes

Looks like the window restoration happens after the window visible and that's cause the issue.
Possible solutions:
`window-state` will set the window to visible after it ends?
Not sure, but at least there should be some workaround

**Comment by amrbashir** [comment]
Seems like you didn't set `visible: false` for your window in tauri.conf.json

**Comment by thewh1teagle** [comment]
If I set it to `visible: false` then it doesn't show up at all.
And if I set empty windows array and create it with `WindowBuilder` with `visible(false)` and then calling `.show()` it hangs.

**Comment by amrbashir** [comment]
> If I set it to `visible: false` then it doesn't show up at all.

That's weird, could you try removing the cache, can be found in `$HOME/Library/Application Support/<identifier>/.window-state`

**Comment by thewh1teagle** [comment]
@amrbashir 
It was the cache but more important I learned that the way to create windows in a good way, is like you mentioned - set them to `visible: false` and let `tauri-state` set to visible when ready.

I didn't saw any mention about that in the Docs / window-state readme. so I guess that by default most people will experience the same thing unless they know that window-state set it to visible true eventually.

Btw. 
What if I don't want that `window-state` will set it to visible true? possible?

Update:
On MacOS, if the window is full screen, the animation still happens when `visible: false`

**Comment by amrbashir** [comment]
> I didn't saw any mention about that in the Docs / window-state readme. so I guess that by default most people will experience the same thing unless they know that window-state set it to visible true eventually.

I think we used to have it but we might have lost it during a PR on accident.


> What if I don't want that `window-state` will set it to visible true? possible?

Not sure what you mean by that but you can configure the plugin to restore and save certain states if needed.

> On MacOS, if the window is full screen, the animation still happens when visible: false

Can't help with that unfortunately since I don't have a macOS, please open another issue
