### ISSUE TITLE
plugin-single-state 2.0.0-beta.1 doesn't compile on Linux

### ISSUE THREAD

**Issue by Gawdl3y** [tauri-apps/plugins-workspace#980]
plugin-single-state 2.0.0-beta.1 fails to compile on Linux due to a broken import.
The import is on [line 13 of linux.rs](https://github.com/tauri-apps/plugins-workspace/blob/v2/plugins/single-instance/src/platform_impl/linux.rs#L13). Based on looking at [the zbus source for this module](https://github.com/dbus2/zbus/blob/main/zbus/src/blocking/mod.rs) and [the docs for zbus::blocking::connection::Builder](https://docs.rs/zbus/4.1.0/zbus/blocking/connection/struct.Builder.html), it looks like it *should* be using `zbus::blocking::connection::Builder` rather than `zbus::blocking::Builder`.

```
   Compiling tauri-plugin-single-instance v2.0.0-beta.1
error[E0432]: unresolved import `zbus::blocking::Builder`
  --> /home/schuyler/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-plugin-single-instance-2.0.0-beta.1/src/platform_impl/linux.rs:13:16
   |
13 |     blocking::{Builder, Connection},
   |                ^^^^^^^ no `Builder` in `blocking`
   |
   = help: consider importing one of these items instead:
           crate::platform_impl::plugin::Builder
           std::thread::Builder
           tauri::Builder
           tauri::plugin::Builder
           zbus::blocking::connection::Builder
           zbus::blocking::proxy::Builder
           zbus::connection::Builder
           zbus::match_rule::Builder
           zbus::message::Builder
           zbus::proxy::Builder

For more information about this error, try `rustc --explain E0432`.
error: could not compile `tauri-plugin-single-instance` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
       Error failed to build app: failed to build app
```

**Comment by lucasfernog** [comment]
looks like i was using a hidden deprecated re-export: https://docs.rs/zbus/4.0.1/src/zbus/blocking/mod.rs.html#51
and they renamed it on 4.1.0: https://docs.rs/zbus/4.1.0/src/zbus/blocking/mod.rs.html#51
I'll open a PR fixing it
