### ISSUE TITLE
[store] mobile support

### ISSUE THREAD

**Issue by Rigidity** [tauri-apps/plugins-workspace#987]
Hello, I've run into a panic with `tauri-plugin-store`.

This happens on the Android emulator, but not on Linux desktop. I'm using the Tauri 2.0 beta so I can have mobile support.

I have this setup function:
```rs
pub fn setup_app(app: &mut App) -> Result<(), Box<dyn Error>> {
    let store = StoreBuilder::new("app_data.bin").build(app.handle().clone());
    let app_data: AppData = Mutex::new(AppDataInner::new(store)?);
    app.manage(app_data);

    Ok(())
}
```

And when running in the Android emulator, it crashes now with
```
 Tauri plugin: pluginId: path, command: getDataDir
2024-02-23 16:10:36.357 23941-23965 RustStdoutStderr        com.tauri.sage                I  thread '<unnamed>' panicked at /home/rigidity/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-2.0.0-beta.4/src/app.rs:965:11:
2024-02-23 16:10:36.357 23941-23965 RustStdoutStderr        com.tauri.sage                I  Failed to setup app: error encountered during setup hook: data store error: No such file or directory (os error 2)
2024-02-23 16:10:36.357 23941-23965 RustStdoutStderr        com.tauri.sage                I  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2024-02-23 16:10:36.358 23941-23965 RustStdoutStderr        com.tauri.sage                I  attempt to unwind out of `rust` with err: Any { .. }
```

For what it's worth, there were some other file not found errors and warnings as well, not just this. Not sure if that part is normal or not.

**Comment by Rigidity** [comment]
The error occurs on `load()` and if I check if the file exists and don't call load if it doesn't, it seems to work as expected.

I'll keep digging and perhaps make a PR.

**Comment by Rigidity** [comment]
The issue is not mobile support, it's using it purely from the Rust side isn't as ergonomic and doesn't handle saving or loading by default if you manually create the store without having the plugin manage it. And when loading you should check if the file exists first.

**Comment by FabianLars** [comment]
i really thought the plugin doesn't support mobile because the file systems works so different on mobile. But i guess we can update the readme table about that then 😅 

Also, load() is not supposed to panic if the file doesn't exist, but just return an error. Are you unwrapping the load result or does it really panic internally? Your code only shows the StoreBuilder which doesn't interact with the file system at all as you noticed already.

**Comment by Rigidity** [comment]
> i really thought the plugin doesn't support mobile because the file systems works so different on mobile. But i guess we can update the readme table about that then 😅 
> 
> 
> 
> Also, load() is not supposed to panic if the file doesn't exist, but just return an error. Are you unwrapping the load result or does it really panic internally? Your code only shows the StoreBuilder which doesn't interact with the file system at all as you noticed already.

Yes, I was unwrapping it. Handling it properly fixes the issue also.

It does seem to work on mobile for me as long as the file is within the app directory.

**Comment by amrbashir** [comment]
> It does seem to work on mobile for me as long as the file is within the app directory.

Can you check if #1011 makes this a bit easier?
